export function enrichCompleteExplanation(code: string, title: string, definition: string, base: string[], focus: string[], traps: string[], practical: string): string[] {
  const area = code.startsWith('1.1') ? 'arquitetura do sistema financeiro' : code.startsWith('1.2') ? 'economia e política econômica' : code.startsWith('1.3') ? 'matemática e decisões financeiras' : code.startsWith('1.4') ? 'infraestrutura e regulação' : code.startsWith('2.1.1') ? 'investimentos e produtos' : code.startsWith('2.1.2') ? 'fundos e veículos de investimento' : code.startsWith('2.2') ? 'previdência' : code.startsWith('2.3') ? 'crédito' : code.startsWith('2.4') ? 'serviços bancários' : code.startsWith('2.5') ? 'seguros e proteção' : code.startsWith('3.') ? 'relacionamento, planejamento e conduta' : 'inovação e novos temas'
  const paragraphs = [...base,
    'O que você precisa entender de verdade\nAntes de decorar a definição, traduza ' + title + ' para uma pergunta prática: “qual problema econômico, financeiro ou regulatório este conceito resolve?”. Em ' + area + ', essa pergunta é mais útil do que memorizar uma lista de termos. A definição central é: ' + definition,
    'Como raciocinar quando o enunciado muda\nA prova pode trocar o nome do produto, colocar o conceito dentro de uma história de cliente ou apresentar informações que parecem secundárias. O caminho é identificar o objeto, a variável que mudou, quem assume o risco e qual regra ou mecanismo está sendo testado. Para ' + title + ', comece pela função do conceito e só depois procure a alternativa que traduz essa função.',
    'Exemplo guiado\nConsidere o seguinte raciocínio: ' + practical + ' Primeiro identifique o fato principal; depois separe as informações relevantes das distrações; em seguida aplique a definição de ' + title + '; por fim, verifique se a conclusão respeita prazo, risco, custos e condições do caso. Essa sequência evita escolher uma alternativa apenas porque ela repete palavras do enunciado.',
    'Onde normalmente nasce a confusão\nOs erros mais comuns aparecem quando dois conceitos têm nomes parecidos ou quando uma regra válida para um produto é transferida para outro. Em vez de decorar apenas “A é diferente de B”, pergunte qual atributo muda: emissor, risco, liquidez, tributação, prazo, função institucional, forma de remuneração ou responsabilidade. Se o atributo não estiver no enunciado, não invente uma premissa.',
    'Como isso vira questão de prova\nUma questão contextualizada costuma fornecer um objetivo, uma situação e algumas restrições. Seu trabalho é transformar o texto em uma decisão. Para ' + title + ', procure especialmente estes sinais: ' + focus.join(' ') + ' Quando a alternativa usar palavras absolutas como “sempre”, “nunca”, “garante” ou “independentemente”, confirme se o conceito realmente permite uma afirmação tão ampla.',
    'Checklist de resolução\n1) O que está sendo perguntado? 2) Qual é o conceito central? 3) Qual informação do caso muda a resposta? 4) Quem assume o risco ou a obrigação? 5) Existe alguma condição ou exceção? 6) A alternativa explica o mecanismo ou apenas repete um termo? Se você conseguir responder essas seis perguntas, normalmente consegue eliminar boa parte das alternativas sem depender de memorização mecânica.',
    'Pegadinhas que você deve reconhecer\n' + traps.join(' ') + ' O objetivo não é decorar a pegadinha, mas entender por que ela é errada. Sempre que errar uma questão sobre ' + title + ', registre qual distinção você confundiu e volte ao conceito correspondente.',
    'Fechamento da aula\nVocê domina ' + title + ' quando consegue explicar o conceito para outra pessoa, aplicar a lógica em um caso novo e identificar por que uma alternativa plausível está errada. A definição é apenas o começo. Depois da leitura, faça o mini quiz; se errar, volte exatamente ao parágrafo que explica o mecanismo do erro.'
  ]
  return paragraphs
}