import { module1 } from '../module-1'
import { macro1Definitions } from './macro-1-definitions'
import { lessonSources, type LessonSourceId } from './sources'
import type { CPALesson, LessonComparison, LessonFormula } from './types'

const verifiedAt='2026-09-14'
const formulas:Record<string,LessonFormula[]>={
'1.3.1':[{name:'Relação exata entre taxa nominal, real e inflação',expression:'1 + i_nominal = (1 + i_real) × (1 + inflação)',explanation:'Para isolar a taxa real, divida 1 + taxa nominal por 1 + inflação e subtraia 1.'}],
'1.3.2':[{name:'Juros simples',expression:'M = C × (1 + i × n)',explanation:'O juro incide sempre sobre o capital inicial C.'},{name:'Juros compostos',expression:'M = C × (1 + i)^n',explanation:'Cada período incorpora os juros acumulados ao capital.'}],
'1.3.3.2.3':[{name:'Valor futuro',expression:'VF = VP × (1 + i)^n',explanation:'Capitaliza o valor presente até a data futura.'},{name:'Valor presente',expression:'VP = VF / (1 + i)^n',explanation:'Desconta um valor futuro para hoje.'},{name:'Valor Presente Líquido',expression:'VPL = Σ FC_t/(1+k)^t − Investimento inicial',explanation:'Um VPL positivo indica valor acima da taxa mínima k, dadas as premissas.'}],
'1.3.3.5.2':[{name:'Taxa Interna de Retorno',expression:'0 = Σ FC_t/(1+TIR)^t − Investimento inicial',explanation:'A TIR é a taxa que zera o VPL; sua interpretação exige cuidado com fluxos não convencionais.'}],
'1.3.3.5.5':[{name:'CMPC / WACC',expression:'CMPC = w_d × k_d × (1−T) + w_e × k_e',explanation:'Combina custo da dívida após efeito tributário quando aplicável e custo do capital próprio pelos respectivos pesos.'}],
'1.3.3.6.1':[{name:'Retorno de um ativo',expression:'R = (Preço final − Preço inicial + Rendimentos) / Preço inicial',explanation:'Inclui valorização e rendimentos recebidos no período.'}],
'1.3.3.6.2':[{name:'Retorno esperado da carteira',expression:'E(R_p) = Σ w_i × E(R_i)',explanation:'O retorno esperado é a média ponderada dos retornos esperados pelos pesos.'}],
'1.3.4.1':[{name:'Fisher',expression:'1 + i_nominal = (1 + i_real) × (1 + inflação)',explanation:'A aproximação i_real ≈ i_nominal − inflação funciona melhor para taxas pequenas; a relação exata é multiplicativa.'}],
'1.3.4.3':[{name:'Juros simples',expression:'J = C × i × n',explanation:'Crescimento linear dos juros.'},{name:'Juros compostos',expression:'M = C × (1+i)^n',explanation:'Crescimento exponencial do montante.'}],
'1.3.5':[{name:'Desconto comercial simples',expression:'D = N × d × n',explanation:'O desconto D incide sobre o valor nominal N.'},{name:'Valor atual',expression:'A = N − D',explanation:'Valor recebido após deduzir o desconto.'}],
'1.3.6':[{name:'Payback simples',expression:'Payback = momento em que o fluxo acumulado ≥ investimento inicial',explanation:'Com fluxos irregulares, some entradas período a período até recuperar o desembolso.'}],
'1.3.7':[{name:'SAC — amortização',expression:'A = Principal / número de parcelas',explanation:'A amortização é constante; os juros caem com o saldo devedor.'},{name:'Price — prestação',expression:'PMT = PV × [i(1+i)^n] / [(1+i)^n − 1]',explanation:'Com taxa fixa e pagamentos periódicos, a prestação é constante.'}],
'1.3.8.1':[{name:'Desconto bancário simples',expression:'D = N × d × n',explanation:'O desconto é calculado sobre o valor nominal; o valor liberado é N − D, antes de outros encargos.'}]
}
const comparisons:Record<string,LessonComparison[]>={
'1.1.1.1.1':[{left:'CMN',right:'Banco Central do Brasil (BCB)',explanation:'O CMN formula diretrizes e normas; o BCB executa, regula e supervisiona dentro de suas competências.'}],
'1.1.1.1.2':[{left:'CNSP',right:'SUSEP',explanation:'O CNSP é normativo no sistema de seguros privados; a SUSEP é a supervisora do segmento.'}],
'1.1.1.1.3':[{left:'CNPC',right:'PREVIC',explanation:'O CNPC regula a previdência complementar fechada; a PREVIC supervisiona as entidades fechadas.'}],
'1.1.2.1.1':[{left:'Banco Central do Brasil (BCB)',right:'CMN',explanation:'O BCB executa e supervisiona; o CMN estabelece diretrizes superiores para o sistema monetário, creditício e cambial.'}],
'1.1.2.1.2':[{left:'CVM',right:'Banco Central do Brasil (BCB)',explanation:'A CVM tem foco no mercado de valores mobiliários; o BCB supervisiona instituições e mercados sob sua competência.'}],
'1.1.2.1.3':[{left:'SUSEP',right:'PREVIC',explanation:'A SUSEP supervisiona seguros e previdência aberta; a PREVIC supervisiona previdência complementar fechada.'}],
'1.1.3.1.1':[{left:'Banco',right:'Instituição de pagamento',explanation:'Bancos podem fazer intermediação financeira conforme suas autorizações; instituição de pagamento tem foco em serviços de pagamento e não vira banco apenas por movimentar recursos.'}],
'1.1.3.1.13':[{left:'Seguradora',right:'Resseguradora',explanation:'A seguradora assume o risco do segurado; a resseguradora assume parte do risco cedido pela seguradora.'}],
'1.1.3.1.14':[{left:'EAPC',right:'EFPC',explanation:'A entidade aberta oferece planos ao público; a entidade fechada atende grupos vinculados a patrocinadores ou instituidores.'}],
'1.1.4.3':[{left:'FGC',right:'FGCoop',explanation:'Ambos são mecanismos de garantia, mas atendem universos de instituições participantes diferentes e seguem regras próprias.'}],
'1.2.3.1':[{left:'Política fiscal',right:'Política monetária',explanation:'Fiscal usa receitas e despesas públicas; monetária atua principalmente sobre juros, liquidez e condições monetárias.'}],
'1.2.4.1':[{left:'Expansionista',right:'Contracionista',explanation:'A expansionista afrouxa condições monetárias; a contracionista as aperta para moderar demanda e pressões inflacionárias.'}],
'1.2.4.7':[{left:'Meta Selic',right:'Selic efetiva',explanation:'A meta é a referência decidida pelo Copom; a efetiva resulta das operações realizadas no mercado correspondente.'}],
'1.2.5.5':[{left:'Câmbio nominal',right:'Câmbio real',explanation:'O nominal é a cotação observada; o real ajusta o nominal por níveis relativos de preços.'}],
'1.2.7':[{left:'Risco de crédito',right:'Risco de mercado',explanation:'Crédito é o risco de não pagamento; mercado é a perda por variação de preços, taxas ou fatores de mercado.'}],
'1.3.2':[{left:'Juros simples',right:'Juros compostos',explanation:'Nos simples a base permanece o principal inicial; nos compostos os juros acumulados entram na base seguinte.'}],
'1.3.3.5.1':[{left:'Prazo médio',right:'Vencimento',explanation:'Vencimento é a data final; prazo médio pondera quando o principal efetivamente retorna.'}],
'1.3.3.6.1':[{left:'Retorno histórico',right:'Retorno esperado',explanation:'Histórico descreve o passado; esperado é uma estimativa prospectiva e incerta.'}],
'1.3.4.2':[{left:'Prefixada',right:'Pós-fixada',explanation:'Prefixada fixa a taxa conhecida na contratação; pós-fixada depende do indexador definido.'}],
'1.3.7':[{left:'SAC',right:'Price',explanation:'SAC tem amortização constante e parcelas decrescentes; Price tem prestação constante sob condições fixas.'}],
'1.4.1.3':[{left:'Contraparte central',right:'Depositário central',explanation:'A contraparte central administra risco de contraparte ao se interpor nas operações; o depositário mantém registro central da titularidade dos ativos.'}],
'1.4.3.1':[{left:'Risco sistêmico',right:'Risco individual',explanation:'O sistêmico envolve propagação e ameaça ao funcionamento do sistema; o individual pode permanecer restrito a uma entidade ou operação.'}],
'1.4.6':[{left:'B3',right:'Selic',explanation:'A B3 oferece diversas infraestruturas de mercado; o Selic é a infraestrutura central de títulos públicos federais.'}],
'1.4.12.1.3.1':[{left:'Conheça sua clientela',right:'Suitability',explanation:'KYC identifica e qualifica o cliente e riscos do relacionamento; suitability avalia adequação de produtos e operações ao perfil.'}]
}

function sourceIdsFor(code:string):LessonSourceId[]{
 if(code==='1.1.1.1.1')return['ANBIMA_PD','CMN','BCB_SFN']; if(code==='1.1.1.1.2'||code==='1.1.2.1.3')return['ANBIMA_PD','SUSEP']; if(code==='1.1.1.1.3')return['ANBIMA_PD','CNPC','PREVIC']; if(code==='1.1.2.1.2')return['ANBIMA_PD','CVM']; if(code==='1.1.2.1.4'||code==='1.1.3.1.16')return['ANBIMA_PD','PREVIC'];
 if(code.startsWith('1.1.3.1.12'))return['ANBIMA_PD','B3','BCB_SFN']; if(['1.1.3.1.13','1.1.3.1.14','1.1.3.1.15','1.1.3.1.17'].includes(code))return['ANBIMA_PD','SUSEP']; if(code.startsWith('1.1.4.1'))return['ANBIMA_PD','ANBIMA_DISTRIBUICAO']; if(code.startsWith('1.1'))return['ANBIMA_PD','BCB_SFN'];
 if(code==='1.2.3.4')return['ANBIMA_PD','PLANALTO_LRF']; if(code.startsWith('1.2.5'))return['ANBIMA_PD','BCB_CAMBIO']; if(code.startsWith('1.2.6'))return['ANBIMA_PD','BCB_POLITICA','IBGE']; if(code.startsWith('1.2'))return['ANBIMA_PD','BCB_POLITICA','BCB_SELIC']; if(code.startsWith('1.3'))return['ANBIMA_PD','BCB_SELIC'];
 if(code.startsWith('1.4.1')||['1.4.4','1.4.5','1.4.6','1.4.7'].includes(code))return['ANBIMA_PD','BCB_SPB','B3']; if(code.startsWith('1.4.2')||code.startsWith('1.4.3'))return['ANBIMA_PD','BCB_ESTABILIDADE','BCB_BASILEIA']; if(code.startsWith('1.4.10'))return['ANBIMA_PD','CVM_RES30']; if(code==='1.4.11')return['ANBIMA_PD','PLANALTO_LIBERDADE']; if(code.startsWith('1.4.12'))return['ANBIMA_PD','ANBIMA_DISTRIBUICAO']; return['ANBIMA_PD','BCB_SFN']
}
function group(code:string){return code.startsWith('1.1')?'arquitetura do Sistema Financeiro Nacional':code.startsWith('1.2')?'política econômica e indicadores':code.startsWith('1.3')?'operações e matemática financeira':'regulação e infraestrutura de mercado'}
function beginner(code:string,title:string,def:string){if(code.startsWith('1.1'))return`Pense no Sistema Financeiro Nacional como uma rede com três papéis: quem cria regras, quem supervisiona e quem opera. ${title} aparece nessa rede com uma função específica. ${def} Para a CPA, entenda o papel antes de decorar a sigla.`;if(code.startsWith('1.2'))return`Economia funciona como decisões conectadas. ${def} Em vez de memorizar isoladamente, pergunte: se isso mudar, quem sente o efeito e por qual caminho?`;if(code.startsWith('1.3'))return`Aqui a ideia é colocar tempo, taxa e fluxo de dinheiro na mesma base. ${def} Antes da conta, identifique prazo, periodicidade e o que a questão realmente pede.`;return`Mercados precisam de regras, infraestrutura e controles de risco. ${def} Na CPA, identifique quem registra, liquida, supervisiona ou protege a operação e qual risco é tratado.`}
function focus(code:string,title:string){if(code.startsWith('1.1'))return[`Identificar qual entidade ou participante exerce a função descrita em um caso sobre ${title}.`,'Distinguir órgão normativo, supervisor e operador quando a questão trocar atribuições.','Aplicar a função institucional a uma situação de cliente ou mercado.'];if(code.startsWith('1.2'))return[`Interpretar o efeito provável de uma mudança econômica envolvendo ${title}.`,'Diferenciar causa, instrumento, indicador e consequência.','Relacionar política econômica a juros, inflação, câmbio, crédito, atividade ou expectativas sem assumir relações mecânicas.'];if(code.startsWith('1.3'))return[`Escolher o conceito ou cálculo adequado para uma situação envolvendo ${title}.`,'Converter corretamente taxa e período antes de calcular.','Interpretar o resultado financeiro, não apenas chegar a um número.'];return[`Reconhecer a função correta de ${title} em uma operação ou obrigação regulatória.`,'Separar infraestrutura, supervisão, autorregulação e mitigação de risco.','Identificar o risco ou conflito que a regra procura reduzir.']}
function traps(code:string,title:string){if(code.startsWith('1.1'))return[`Não atribua a ${title} a função de outra entidade do mesmo subsistema.`,'Normativo, supervisor, autorregulador e operador não são sinônimos.','Sigla semelhante não substitui a competência descrita no enunciado.'];if(code.startsWith('1.2'))return[`Não trate o efeito de ${title} como automático e isolado; expectativas e defasagens importam.`,'Taxa, índice e meta podem ter nomes próximos e funções diferentes.','Cuidado com alternativas que invertem causa e consequência.'];if(code.startsWith('1.3'))return[`Não aplique fórmula de ${title} sem alinhar taxa e período.`,'Nominal, efetivo, real, bruto e líquido respondem a perguntas diferentes.','Conta correta com interpretação econômica errada continua sendo resposta errada.'];return[`Não confunda ${title} com outra etapa da infraestrutura ou com o supervisor.`,'Garantia, registro, compensação, liquidação, custódia e supervisão são funções diferentes.','Enquadramentos dependem do critério normativo vigente, não de percepção subjetiva.']}
function defaultComparison(code:string):LessonComparison[]{if(code.startsWith('1.1'))return[{left:'Normatização',right:'Supervisão/Operação',explanation:'Normatizar estabelece diretrizes; supervisionar fiscaliza; operar presta o serviço.'}];if(code.startsWith('1.2'))return[{left:'Indicador',right:'Instrumento de política',explanation:'Indicador mede uma condição; instrumento é usado pela autoridade para influenciá-la.'}];if(code.startsWith('1.3'))return[{left:'Fórmula',right:'Interpretação',explanation:'A fórmula organiza a conta; a decisão exige entender risco, retorno, prazo e fluxo.'}];return[{left:'Infraestrutura/regra',right:'Participante',explanation:'A infraestrutura ou regra organiza e reduz riscos; o participante executa sua atividade dentro dela.'}]}
function practical(code:string,title:string){if(code.startsWith('1.1'))return`Um cliente pergunta quem define uma regra, quem fiscaliza e quem presta o serviço ligado a ${title}. A resposta correta vem da função de cada participante, não da sigla mais conhecida.`;if(code.startsWith('1.2'))return`Juros, inflação ou câmbio mudam e um investidor pergunta o impacto. Use ${title} para explicar o canal de transmissão, a direção provável e quais outras variáveis também importam.`;if(code.startsWith('1.3'))return`Dois investimentos parecem pagar taxas parecidas, mas têm prazos e fluxos diferentes. ${title} ajuda a colocá-los na mesma base antes da comparação.`;return`Uma operação atravessa participantes e infraestruturas antes da liquidação. Em ${title}, identifique a função concreta e o risco, obrigação ou conflito tratado.`}
function quiz(code:string,title:string,def:string,f:string[],t:string[]){return[{question:`Qual alternativa resume melhor ${title}?`,options:[def,'É apenas uma expressão comercial, sem função econômica ou regulatória específica.','Garante rentabilidade positiva a qualquer investidor.','Aplica-se somente fora do Sistema Financeiro Nacional.'],correctIndex:0,explanation:def},{question:`Em questão contextualizada sobre ${title}, qual abordagem é adequada?`,options:[f[0],'Escolher a sigla mais conhecida mesmo com função diferente.','Ignorar prazo, risco e contexto.','Assumir que toda relação econômica é automática.'],correctIndex:0,explanation:f[0]},{question:`Qual cuidado é importante ao estudar ${title}?`,options:[t[0],'Tratar conceitos próximos como sinônimos.','Ignorar a fonte oficial quando houver regra vigente.','Memorizar só a sigla e ignorar a função.'],correctIndex:0,explanation:t[0]}]}

const parents=new Set(module1.flatMap((item)=>item.parentCode?[item.parentCode]:[]))
const units=module1.filter((item)=>!parents.has(item.pdCode))
export const macro1Lessons:CPALesson[]=units.map((unit)=>{const def=macro1Definitions[unit.pdCode];if(!def)throw new Error(`Conteúdo ausente para ${unit.pdCode}`);const title=unit.title.replace(/\.$/,'');const f=focus(unit.pdCode,title);const t=traps(unit.pdCode,title);const essentials=[title,def.split(/[.;]/)[0],`Enquadramento no PD ${unit.pdCode}`,unit.pdCode.startsWith('1.1')?'Normatizar ≠ supervisionar ≠ operar':unit.pdCode.startsWith('1.2')?'Direção do impacto e canal de transmissão':unit.pdCode.startsWith('1.3')?'Taxa, prazo e fluxo na mesma base temporal':'Função da infraestrutura/regra e risco mitigado'];return{certification:'CPA',programVersion:'1.2',pdCode:unit.pdCode,parentCode:unit.parentCode,title,oneSentence:def,beginnerExplanation:beginner(unit.pdCode,title,def),completeExplanation:[`${def} Esse item pertence ao bloco de ${group(unit.pdCode)} do Programa Detalhado CPA 1.2.`,unit.pdCode.startsWith('1.1')?'Separe função normativa, função supervisora e atividade operacional. Observe competência, público e mercado atendido.':unit.pdCode.startsWith('1.2')?'Juros, inflação, câmbio, crédito, atividade e expectativas interagem; avalie direção, canal e defasagem.':unit.pdCode.startsWith('1.3')?'Taxa e prazo precisam estar na mesma periodicidade e os fluxos no tempo correto; interpretação vem antes da fórmula.':'Infraestruturas e regras reduzem assimetria e riscos; compare papéis para não atribuir a uma entidade a função de outra.',`Conecte ${title} à decisão de um cliente, instituição ou regulador; isso vale mais do que decorar uma definição solta.`],essentialConcepts:essentials,examFocus:f,practicalExample:practical(unit.pdCode,title),comparisons:comparisons[unit.pdCode]??defaultComparison(unit.pdCode),formulas:formulas[unit.pdCode]??[],traps:t,reviewSummary:[`${unit.pdCode} · ${title}.`,def,unit.pdCode.startsWith('1.1')?'Pergunte: quem normatiza, quem supervisiona e quem opera?':unit.pdCode.startsWith('1.2')?'Pergunte: qual variável muda, por qual canal e com qual efeito provável?':unit.pdCode.startsWith('1.3')?'Pergunte: taxa, prazo e fluxo estão na mesma base?':'Pergunte: qual função, qual risco e qual entidade são descritos?'],flashcards:[{front:`O que é ${title}?`,back:def},{front:`Qual ideia central memorizar no PD ${unit.pdCode}?`,back:essentials[1]},{front:`Como ${title} pode aparecer na prova?`,back:f[0]},{front:`Qual pegadinha evitar em ${unit.pdCode}?`,back:t[0]}],miniQuiz:quiz(unit.pdCode,title,def,f,t),officialSources:sourceIdsFor(unit.pdCode).map((id)=>lessonSources[id]),searchTerms:Array.from(new Set(([unit.title,def,...essentials,...f,...t].join(' ').match(/[A-Za-zÀ-ÿ0-9.-]{2,}/g)??[]).map((term)=>term.toLowerCase()))),lastVerified:verifiedAt}})
if(macro1Lessons.length!==105)throw new Error(`Macrotema 1 deveria possuir 105 aulas; foram geradas ${macro1Lessons.length}.`)
export const macro1LessonMap=new Map(macro1Lessons.map((lesson)=>[lesson.pdCode,lesson]))
