export const macro2ServicesInsuranceDefinitions: Record<string,string> = {
'2.4.1.1':'Conta corrente pode receber salários e outros créditos, mas conta-salário é produto específico voltado ao pagamento de remuneração e possui regras próprias de movimentação e portabilidade.',
'2.4.1.2.1':'Depósitos à vista elegíveis podem contar com cobertura do FGC dentro dos limites e condições vigentes, mas saldo acima do limite continua exposto ao risco da instituição.',
'2.4.1.2.2':'Depósito compulsório é parcela de determinados recursos captados que instituições devem recolher ao Banco Central, funcionando como instrumento prudencial e de política monetária.',
'2.4.1.3':'Boleto bancário é instrumento de cobrança com dados padronizados que permite pagamento e liquidação por instituições participantes, devendo o cliente conferir emissor, valor e vencimento.',
'2.4.1.4':'Serviços digitais bancários permitem contratação, movimentação, atendimento e pagamentos por canais eletrônicos, ampliando conveniência e exigindo cuidados adicionais de segurança e autenticação.',
'2.4.1.5.1':'Pix é o arranjo de pagamentos instantâneos brasileiro, criado para transferências e pagamentos em poucos segundos, disponível continuamente e liquidado em infraestrutura operada pelo Banco Central.',
'2.4.1.5.2':'No Pix, chaves facilitam a iniciação do pagamento, participantes encaminham a ordem e a liquidação ocorre no SPI; tarifas e limites dependem do tipo de cliente e regras aplicáveis.',
'2.4.1.5.3':'Pix pode ser usado para transferências e pagamentos de pessoas e empresas, incluindo QR Code e outras formas de iniciação previstas no arranjo.',
'2.4.1.5.4':'Para pessoas jurídicas, Pix facilita pagamentos e recebimentos com integração a sistemas, QR Codes e conciliação, sujeito às condições comerciais e regras do participante.',
'2.4.1.6.1':'Tarifas bancárias só podem ser cobradas quando autorizadas pelas regras aplicáveis e informadas ao cliente; determinados serviços essenciais possuem gratuidade mínima.',
'2.4.1.7.1':'Atendimento bancário combina canais presenciais e digitais e deve observar regras de funcionamento, disponibilidade e tratamento adequado ao consumidor conforme a localidade e o serviço.',
'2.4.2.1':'Conta internacional facilita manter saldo, pagar, receber e converter moedas, mas envolve risco cambial, custos, tributação e regras de disponibilidade diferentes de uma conta doméstica.',
'2.4.2.2':'Operações internacionais podem sofrer IOF com alíquotas diferentes conforme natureza da operação, por isso o cliente deve identificar finalidade antes de estimar o custo.',
'2.4.2.3':'Investimentos mantidos no exterior podem gerar obrigações de declaração e tributação no Brasil; o investidor residente deve considerar regras fiscais brasileiras além da tributação no país do ativo.',
'2.4.3.1':'Correspondentes cambiais podem atuar em operações autorizadas em nome de instituições, dentro de limites, procedimentos de identificação e controles definidos pela regulação.',
'2.4.3.2':'Compra e venda de moeda estrangeira em instituições autorizadas exige identificação, registro e observância das regras cambiais aplicáveis à finalidade e ao valor da operação.',
'2.4.3.3':'Recompra de moeda estrangeira ocorre quando a instituição readquire moeda anteriormente vendida ou remanescente de viagem, segundo regras, documentação e condições comerciais vigentes.',
'2.5.1.1':'Seguro de vida inteira busca proteção por prazo indeterminado enquanto o contrato estiver vigente e pode combinar características de proteção e formação de reserva conforme o produto.',
'2.5.1.2':'Seguro de vida temporário cobre o risco por período definido e tende a concentrar o prêmio na proteção durante aquele prazo, cessando a cobertura ao fim se não houver renovação.',
'2.5.1.3':'Seguro de vida tradicional transfere determinados riscos pessoais à seguradora mediante pagamento de prêmio, com capital segurado, beneficiários, coberturas e exclusões definidos em contrato.',
'2.5.2.1':'Seguro automóvel protege contra eventos cobertos ligados ao veículo e responsabilidade civil conforme apólice, franquia, limites e exclusões contratadas.',
'2.5.2.2':'Seguro residencial cobre riscos previstos para imóvel e conteúdo, podendo incluir assistências e responsabilidade civil; a extensão depende das coberturas efetivamente contratadas.',
'2.5.2.3':'Seguro prestamista quita ou amortiza obrigação financeira em eventos cobertos do devedor, protegendo simultaneamente o contratante e o credor dentro dos limites da apólice.'
}
