export const macro1Definitions: Record<string,string> = {
'1.1.1.1.1':'O Conselho Monetário Nacional (CMN) é o órgão normativo superior do Sistema Financeiro Nacional para as políticas monetária, de crédito e cambial, enquanto o Banco Central executa e supervisiona grande parte dessas diretrizes.',
'1.1.1.1.2':'O Conselho Nacional de Seguros Privados (CNSP) fixa diretrizes e normas para seguros, resseguros, capitalização e previdência complementar aberta, cuja supervisão cabe à Superintendência de Seguros Privados (SUSEP).',
'1.1.1.1.3':'O Conselho Nacional de Previdência Complementar (CNPC) exerce a função regulatória sobre o regime de previdência complementar operado pelas entidades fechadas, enquanto a Superintendência Nacional de Previdência Complementar (PREVIC) supervisiona esse segmento.',
'1.1.2.1.1':'O Banco Central do Brasil (BCB) executa políticas definidas no âmbito do Sistema Financeiro Nacional e autoriza, regula e supervisiona instituições sob sua competência, com foco também na estabilidade e no funcionamento do sistema.',
'1.1.2.1.2':'A Comissão de Valores Mobiliários (CVM) regula, desenvolve e fiscaliza o mercado de valores mobiliários, buscando proteger investidores e promover um mercado íntegro e eficiente.',
'1.1.2.1.3':'A Superintendência de Seguros Privados (SUSEP) supervisiona e fiscaliza os mercados de seguros, resseguros, capitalização e previdência complementar aberta.',
'1.1.2.1.4':'A Superintendência Nacional de Previdência Complementar (PREVIC) supervisiona e fiscaliza as entidades fechadas de previdência complementar e seus planos.',
'1.1.3.1.1':'Bancos e caixas econômicas intermedeiam recursos, oferecem contas, crédito, pagamentos e outros serviços, conectando poupadores, tomadores e o sistema de pagamentos.',
'1.1.3.1.2':'Cooperativas de crédito prestam serviços financeiros aos associados sob modelo cooperativo; bancos cooperativos ampliam a integração dessas cooperativas com o restante do sistema financeiro.',
'1.1.3.1.3':'Instituições de pagamento viabilizam serviços de pagamento e movimentação de recursos em arranjos de pagamento, sem que isso as transforme automaticamente em bancos.',
'1.1.3.1.4':'Administradoras de consórcios organizam grupos de autofinanciamento para aquisição de bens ou serviços, administrando contribuições, assembleias e contemplações.',
'1.1.3.1.5':'Corretoras e distribuidoras intermedeiam operações e distribuem produtos financeiros e valores mobiliários, conectando investidores ao mercado conforme as autorizações aplicáveis.',
'1.1.3.1.6':'Fintechs usam tecnologia para oferecer ou viabilizar serviços financeiros; o termo descreve um modelo de negócio e não, sozinho, uma categoria regulatória única.',
'1.1.3.1.7':'Sociedades de crédito, financiamento e investimento, conhecidas como financeiras, têm atuação típica no financiamento ao consumo e em outras modalidades de crédito autorizadas.',
'1.1.3.1.8':'Companhias hipotecárias atuam em operações vinculadas ao financiamento imobiliário e ao mercado de créditos imobiliários dentro do marco regulatório aplicável.',
'1.1.3.1.9':'Agências de fomento apoiam projetos e atividades econômicas em sua área de atuação, oferecendo financiamento orientado ao desenvolvimento.',
'1.1.3.1.10':'Sociedades de crédito ao microempreendedor e à empresa de pequeno porte direcionam crédito e serviços a atividades produtivas de menor porte, dentro dos limites regulatórios.',
'1.1.3.1.11':'Sociedades de Crédito Imobiliário (SCI) são instituições voltadas a operações relacionadas ao financiamento imobiliário e à captação permitida para esse segmento.',
'1.1.3.1.12':'A B3 S.A. — Brasil, Bolsa, Balcão (B3) provê infraestrutura para negociação, registro, compensação, liquidação e depósito centralizado de ativos e valores mobiliários.',
'1.1.3.1.13':'Seguradoras assumem riscos mediante contratos de seguro; resseguradoras recebem, por resseguro, parte dos riscos assumidos por seguradoras.',
'1.1.3.1.14':'Entidades Abertas de Previdência Complementar (EAPC) oferecem planos de previdência complementar acessíveis ao público, sob supervisão da SUSEP.',
'1.1.3.1.15':'Sociedades de capitalização comercializam títulos de capitalização, produtos com regras próprias de acumulação, sorteios e resgate que não devem ser confundidos com investimentos tradicionais.',
'1.1.3.1.16':'Entidades Fechadas de Previdência Complementar (EFPC), também chamadas fundos de pensão, administram planos destinados a grupos vinculados a patrocinadores ou instituidores, sob supervisão da PREVIC.',
'1.1.3.1.17':'Corretoras de seguros fazem a intermediação entre clientes e seguradoras, auxiliando na contratação de seguros dentro das regras do setor.',
'1.1.4.1':'A Associação Brasileira das Entidades dos Mercados Financeiro e de Capitais (ANBIMA) representa instituições e exerce autorregulação em atividades e mercados cobertos por seus códigos.',
'1.1.4.2':'A Associação dos Analistas e Profissionais de Investimento do Mercado de Capitais (APIMEC), a Planejar — Associação Brasileira de Planejamento Financeiro — e a Associação Nacional das Corretoras de Valores, Câmbio e Mercadorias (ANCORD) são entidades ligadas a categorias e atividades profissionais distintas, com funções próprias de certificação, representação ou autorregulação.',
'1.1.4.3':'O Fundo Garantidor de Créditos (FGC) e o Fundo Garantidor do Cooperativismo de Crédito (FGCoop) mantêm mecanismos de proteção para determinadas obrigações de instituições participantes, sujeitos a produtos, limites e regras de elegibilidade.',
'1.1.5':'O Sistema de Pagamentos Brasileiro (SPB) reúne regras, procedimentos e infraestruturas que permitem transferir recursos, liquidar obrigações e reduzir riscos nas transações financeiras.',
'1.2.1.1':'O fluxo circular da renda mostra como famílias, empresas, governo e mercados trocam bens, serviços, fatores de produção, renda e gastos, fazendo as decisões de um agente afetarem os demais.',
'1.2.2.1':'O mercado monetário concentra operações de curto prazo ligadas à liquidez da economia e à transmissão da política monetária.',
'1.2.2.2':'O mercado cambial reúne operações de compra e venda de moedas e transferências internacionais, formando taxas de câmbio conforme regras e condições de mercado.',
'1.2.2.3':'O mercado de crédito conecta agentes superavitários e deficitários por meio de empréstimos e financiamentos, com preço refletido principalmente em juros, prazos e risco de crédito.',
'1.2.2.4':'O mercado de capitais aproxima emissores e investidores por meio de valores mobiliários, permitindo captação de recursos e negociação de instrumentos como ações e debêntures.',
'1.2.3.1':'Política fiscal é o uso de receitas, despesas e financiamento público para cumprir objetivos do Estado e influenciar atividade econômica, demanda e trajetória da dívida.',
'1.2.3.2':'Uma política fiscal pode ser expansionista ou contracionista conforme a combinação de gastos, tributos e resultados fiscais, sempre observada em conjunto com o ciclo econômico e as restrições orçamentárias.',
'1.2.3.3':'Déficits, dívida, inflação, juros e investimento se relacionam porque a forma de financiar o setor público altera demanda, risco, expectativas e condições financeiras.',
'1.2.3.4':'O financiamento do governo precisa respeitar regras fiscais e de responsabilidade na gestão das contas públicas, com impacto direto na sustentabilidade da dívida e na confiança dos agentes.',
'1.2.4.1':'Política monetária expansionista busca afrouxar condições monetárias, enquanto a contracionista busca apertá-las; ambas afetam juros, crédito, demanda e inflação.',
'1.2.4.2':'Operações de mercado aberto, redesconto e recolhimentos compulsórios são instrumentos pelos quais o Banco Central influencia liquidez e condições monetárias.',
'1.2.4.3':'Os canais de transmissão explicam como decisões monetárias chegam à economia por juros, crédito, preços de ativos, câmbio e expectativas.',
'1.2.4.4':'Mudanças nas condições monetárias alteram taxas de curto e longo prazo, valor dos ativos, custo do crédito, atividade e inflação por diferentes canais e com defasagens.',
'1.2.4.5':'O Comitê de Política Monetária (Copom) do Banco Central do Brasil define a meta para a Taxa Selic dentro do regime monetário, e essa decisão influencia preços de ativos, crédito, atividade e inflação.',
'1.2.4.6':'O regime de metas para a inflação orienta a política monetária em torno de uma meta oficial, enquanto expectativas de inflação influenciam decisões de preços, salários, juros e investimentos.',
'1.2.4.7':'A meta da Taxa Selic é definida pelo Comitê de Política Monetária (Copom); a Selic efetiva resulta das operações do mercado de reservas, e a Taxa DI, ligada aos depósitos interfinanceiros e aos Certificados de Depósito Interbancário (CDI), é referência privada próxima, mas não idêntica.',
'1.2.5.1':'Política cambial reúne ações e regras relacionadas ao mercado de câmbio e à gestão de condições externas, sem significar que o Banco Central fixe necessariamente uma cotação para a moeda.',
'1.2.5.2':'Regimes cambiais descrevem como a taxa de câmbio é determinada; reservas internacionais são ativos externos do país e o cupom cambial representa uma taxa de juros em dólares implícita em operações no mercado doméstico.',
'1.2.5.3':'O cupom cambial influencia o custo relativo de posições em moeda estrangeira e pode afetar decisões de hedge, arbitragem e investimento.',
'1.2.5.4':'O swap cambial é um derivativo usado para trocar exposições financeiras, permitindo administrar risco relacionado à variação cambial sem envolver necessariamente entrega física de moeda.',
'1.2.5.5':'Taxa nominal é a cotação observada; taxa real ajusta diferenças de preços, PTAX é uma taxa de referência calculada pelo Banco Central, e as expressões comercial/turismo refletem contextos distintos de operação.',
'1.2.6.1':'O Produto Interno Bruto (PIB) mede o valor dos bens e serviços finais produzidos em uma economia em determinado período e pode ser analisado por consumo, investimento, governo e setor externo.',
'1.2.6.2':'O Índice Nacional de Preços ao Consumidor Amplo (IPCA), o Índice Geral de Preços – Mercado (IGP-M), o Índice de Preços ao Produtor Amplo (IPA) e o Índice de Preços ao Consumidor da Fipe (IPC-Fipe) medem universos e etapas de preços diferentes e não devem ser tratados como indicadores intercambiáveis.',
'1.2.6.3':'A taxa de desemprego mede a parcela da força de trabalho que procura e não encontra ocupação, sendo relevante para avaliar folga do mercado de trabalho, renda e pressão sobre a atividade.',
'1.2.6.4':'A Taxa Selic, a Taxa de Depósitos Interfinanceiros (DI) e a Taxa Referencial (TR) são referências distintas: a Selic está ligada à política monetária e ao mercado de títulos públicos, a DI ao mercado interfinanceiro e a TR segue metodologia própria para usos previstos em lei e contratos.',
'1.2.7':'Risco de liquidez é a dificuldade de vender ou honrar obrigações sem perdas relevantes; risco de crédito é a possibilidade de inadimplência; risco de mercado decorre de oscilações de preços, taxas e fatores de mercado.',
'1.3.1':'A taxa nominal é a taxa expressa sem descontar a inflação, enquanto a taxa real representa o ganho de poder de compra; um indexador é a referência usada para atualizar valores ao longo do tempo.',
'1.3.2':'Juros simples incidem sempre sobre o principal inicial, enquanto juros compostos incorporam os juros acumulados à base de cálculo, gerando crescimento exponencial.',
'1.3.3.1':'Em ativos de crédito privado, o fluxo ao investidor pode combinar pagamentos de juros e amortizações do principal conforme as regras de cada emissão.',
'1.3.3.2.1':'Um fluxo de pagamentos organiza valores e datas de entradas e saídas, permitindo comparar contratos somente quando taxa e tempo são tratados de forma consistente.',
'1.3.3.2.2':'Fluxo de caixa representa cronologicamente entradas e saídas; em títulos, cupons remuneram o capital e amortizações devolvem principal conforme a estrutura contratual.',
'1.3.3.2.3':'Valor Presente traz fluxos futuros para hoje, Valor Futuro leva valores atuais adiante e o Valor Presente Líquido (VPL) soma fluxos descontados menos o investimento inicial.',
'1.3.3.3':'Taxa de desconto é a taxa usada para converter valores futuros em equivalentes presentes, refletindo o custo de oportunidade e, conforme o caso, risco do fluxo.',
'1.3.3.4':'Taxa bruta mede retorno antes de impostos e outros descontos considerados, enquanto taxa líquida mostra o que efetivamente permanece para o investidor após esses efeitos.',
'1.3.3.5.1':'Vencimento é a data final contratual; prazo médio considera a distribuição temporal dos fluxos de principal e não deve ser confundido automaticamente com o vencimento.',
'1.3.3.5.2':'A Taxa Interna de Retorno (TIR) é a taxa que zera o Valor Presente Líquido dos fluxos de um investimento.',
'1.3.3.5.3':'Custo de oportunidade é o retorno ou benefício da melhor alternativa sacrificada quando se escolhe uma decisão financeira.',
'1.3.3.5.4':'Taxa livre de risco é uma referência teórica/prática de retorno com risco de crédito mínimo, usada como base para avaliar prêmios de risco.',
'1.3.3.5.5':'O Custo Médio Ponderado de Capital (CMPC), também conhecido pela sigla inglesa WACC (Weighted Average Cost of Capital), combina o custo das fontes de dívida e de capital próprio segundo seus pesos na estrutura de financiamento.',
'1.3.3.5.6.1':'Alavancagem financeira usa capital de terceiros para ampliar a capacidade de investimento, mas também aumenta sensibilidade do resultado ao custo da dívida e ao desempenho dos ativos.',
'1.3.3.6.1':'Retorno histórico de um ativo mede o que ocorreu no passado; retorno esperado é uma estimativa prospectiva e não uma promessa de rentabilidade.',
'1.3.3.6.2':'O retorno de uma carteira depende dos pesos de cada ativo e de seus retornos; para risco, também importa como os ativos se movimentam em conjunto.',
'1.3.4.1':'Taxas nominal, efetiva e real medem coisas diferentes: a nominal pode ser cotada em uma base, a efetiva incorpora a capitalização do período e a real desconta o efeito da inflação.',
'1.3.4.2':'Taxa prefixada é conhecida no momento da contratação; pós-fixada depende da evolução de um indexador ou referência definida no contrato.',
'1.3.4.3':'Juros simples crescem linearmente sobre o principal inicial; juros compostos acumulam juros sobre juros e dominam grande parte das operações financeiras de longo prazo.',
'1.3.5':'No desconto comercial simples, o desconto é calculado sobre o valor nominal futuro do título, e não sobre seu valor presente.',
'1.3.6':'Payback é o tempo necessário para recuperar o desembolso inicial pelos fluxos gerados pelo investimento, sendo uma métrica simples que não substitui análise de valor presente.',
'1.3.7':'No Sistema de Amortização Constante (SAC), a amortização do principal é constante e as parcelas tendem a cair; no sistema Price, as prestações são constantes quando taxa e condições permanecem fixas.',
'1.3.8.1':'Desconto bancário simples antecipa um recebível subtraindo um desconto calculado sobre o valor nominal e o prazo restante até o vencimento.',
'1.4.1.1.1':'O Sistema de Pagamentos Brasileiro (SPB) reúne infraestruturas, regras e participantes que processam e liquidam pagamentos e transferências, contribuindo para segurança e eficiência do sistema financeiro.',
'1.4.1.1.2':'O Sistema de Pagamentos Instantâneos (SPI) é a infraestrutura central operada pelo Banco Central para liquidação das transações Pix entre participantes.',
'1.4.1.2.1':'O Sistema Especial de Liquidação e de Custódia (Selic) é a infraestrutura em que se registram e liquidam, entre outras operações, títulos públicos federais.',
'1.4.1.3':'Uma contraparte central se interpõe entre compradores e vendedores em mercados elegíveis, tornando-se contraparte das operações e administrando riscos de liquidação e contraparte.',
'1.4.1.4':'Um depositário central mantém registro centralizado da titularidade de ativos desmaterializados e dá suporte à movimentação e à liquidação desses ativos.',
'1.4.1.5':'Uma entidade registradora registra informações sobre operações e ativos, aumentando rastreabilidade e transparência conforme a regulação aplicável.',
'1.4.2.1':'O Comitê de Estabilidade Financeira (Comef), os recolhimentos compulsórios e as Linhas Financeiras de Liquidez — Linha de Liquidez Imediata (LLI) e Linha de Liquidez a Termo (LLT) — integram mecanismos usados pelo Banco Central para monitorar riscos e administrar condições de liquidez e estabilidade.',
'1.4.3.1':'Risco sistêmico é o risco de problemas em instituições, mercados ou infraestruturas se propagarem e comprometerem o funcionamento do sistema financeiro e da economia.',
'1.4.3.2':'Basileia I, II e III são marcos internacionais que evoluíram requisitos de capital, gestão de riscos, liquidez e alavancagem para aumentar a resiliência dos bancos.',
'1.4.4':'Clearing houses apoiam registro, compensação e liquidação de operações e podem administrar garantias e risco de contraparte conforme o mercado e a infraestrutura.',
'1.4.5':'Risco de contraparte é a possibilidade de a outra parte de uma operação não cumprir suas obrigações, podendo gerar perda e efeito em cadeia em mercados interligados.',
'1.4.6':'B3 e Selic exercem papéis distintos na infraestrutura: a B3 opera ambientes e serviços de mercado, enquanto o Selic é central para custódia e liquidação de títulos públicos federais.',
'1.4.7':'Portabilidade de custódia permite transferir a posição de determinados ativos entre instituições, observando procedimentos, titularidade e regras operacionais aplicáveis.',
'1.4.8':'Desintermediação financeira ocorre quando poupadores e tomadores se conectam com menos intermediação bancária tradicional, por exemplo via emissão direta de valores mobiliários.',
'1.4.9':'A BSM Supervisão de Mercados (BSM) atua na autorregulação e supervisão dos mercados administrados pela B3, monitorando participantes e práticas conforme suas competências.',
'1.4.10.1.1':'A regulação da CVM distingue investidores profissionais, qualificados e outras categorias porque determinados produtos, ofertas e dispensas pressupõem diferentes níveis de conhecimento, patrimônio ou enquadramento.',
'1.4.10.1.2':'O enquadramento de investidores profissionais, qualificados e não residentes deve seguir os critérios objetivos da Resolução CVM 30 e não pode ser presumido apenas pela experiência percebida do cliente.',
'1.4.11':'A Lei nº 13.874/2019, conhecida como Lei de Liberdade Econômica, estabelece garantias de livre iniciativa e princípios para a atuação do Estado sobre atividades econômicas.',
'1.4.12.1.1':'O Código ANBIMA de Distribuição define seu objetivo e abrangência para atividades de distribuição realizadas pelas instituições participantes dentro do escopo de autorregulação.',
'1.4.12.1.2':'Os princípios gerais de conduta do Código ANBIMA de Distribuição orientam atuação ética, diligente, transparente e compatível com os interesses dos clientes.',
'1.4.12.1.3.1':'Conheça sua clientela (KYC) reúne procedimentos para identificar, qualificar e manter informações do cliente adequadas às obrigações regulatórias e aos riscos do relacionamento.',
'1.4.12.1.3.2':'Suitability é o processo de verificar se produtos, serviços e operações são adequados ao perfil, objetivos, situação financeira e conhecimento do cliente conforme as regras aplicáveis.',
'1.4.12.1.3.3':'Publicidade de produtos de investimento deve ser clara, equilibrada e compatível com as regras de divulgação, sem induzir o investidor a conclusões enganosas sobre retorno e risco.',
'1.4.12.1.3.4':'Transparência na remuneração exige informar, conforme as regras aplicáveis, como o canal de distribuição é remunerado e quais conflitos de interesse podem decorrer desse modelo.',
'1.4.12.1.3.5':'Serviços de intermediação no exterior exigem atenção ao papel da instituição brasileira, às informações prestadas e às regras aplicáveis à oferta ou encaminhamento do cliente.',
'1.4.12.1.3.6':'Transferência de produtos de investimento deve seguir procedimentos que preservem titularidade, informações e continuidade operacional entre instituições.',
'1.4.12.1.3.7':'Apuração de valores de referência busca oferecer parâmetros consistentes para determinados produtos, com metodologia e transparência compatíveis com as regras da autorregulação.',
'1.4.12.1.3.8':'Na distribuição para o segmento private, além das regras gerais, aplicam-se requisitos específicos de atendimento e estrutura definidos pela autorregulação ANBIMA.'
}
