export const macro2InvestmentDefinitions: Record<string,string> = {
'2.1.1.1.1.1':'A NTN-B paga IPCA mais uma taxa real e, na versão com juros semestrais, distribui cupons ao longo do caminho; a NTN-B Principal acumula a remuneração e concentra o pagamento no vencimento.',
'2.1.1.1.1.2':'A LFT é o título público pós-fixado ligado à Selic, por isso seu valor tende a oscilar menos com mudanças de juros do que títulos prefixados ou indexados longos, embora venda antecipada continue sujeita a preço de mercado.',
'2.1.1.1.1.3':'A LTN é o título público prefixado sem cupons: o investidor compra por preço inferior ao valor de resgate e conhece a taxa contratada se carregar o papel até o vencimento.',
'2.1.1.1.1.4':'O Tesouro Direto é a plataforma oficial de negociação de títulos públicos federais para pessoas físicas, com preços e taxas atualizados e possibilidade de compra e resgate conforme suas regras operacionais.',
'2.1.1.1.2':'Tesouro Prefixado, Selic, IPCA+, Educa+ e RendA+ são formas comerciais de títulos públicos com indexadores, fluxos e objetivos diferentes; a escolha depende de prazo, objetivo, tolerância à oscilação e necessidade de liquidez.',
'2.1.1.1.3.1':'O CDB é um depósito a prazo emitido por banco para captar recursos, com remuneração prefixada, pós-fixada ou híbrida e cobertura do FGC quando elegível e dentro dos limites vigentes.',
'2.1.1.1.3.2':'RDB e RDC são depósitos a prazo usados por instituições autorizadas e cooperativas para captação; diferem do CDB principalmente em regras de emissão e negociação, embora compartilhem lógica de crédito do emissor.',
'2.1.1.1.3.3':'A LCI é um título bancário lastreado em créditos imobiliários; para pessoa física, seus rendimentos são tratados como isentos de IR nas regras atualmente aplicáveis e o produto pode ter cobertura do FGC quando elegível.',
'2.1.1.1.3.4':'A LCA é um título bancário ligado ao financiamento do agronegócio; para pessoa física, seus rendimentos são tratados como isentos de IR nas regras atualmente aplicáveis e o produto pode ter cobertura do FGC quando elegível.',
'2.1.1.1.3.5':'A LCD é uma letra de crédito voltada ao financiamento do desenvolvimento, incluída entre os produtos cobertos pelo FGC quando atendidos os critérios do fundo e sujeita às regras próprias de emissão e tributação.',
'2.1.1.1.4.1':'Debênture de infraestrutura é título de dívida corporativa destinado ao financiamento de projetos enquadrados em infraestrutura, com benefícios tributários previstos em lei para determinadas emissões e investidores.',
'2.1.1.1.4.2':'Debênture conversível pode ser convertida em ações conforme as condições da emissão; debênture permutável permite trocar o título por ações ou outros ativos previstos, transferindo parte do potencial de valorização ao investidor.',
'2.1.1.1.5':'CRI é valor mobiliário de securitização lastreado em recebíveis imobiliários; o risco principal depende da estrutura e dos créditos que sustentam a emissão, e não há garantia ordinária do FGC.',
'2.1.1.1.6':'CRA é valor mobiliário de securitização lastreado em recebíveis do agronegócio; seu risco vem da estrutura, dos devedores e das garantias da emissão, sem cobertura ordinária do FGC.',
'2.1.1.1.7':'Rating é uma opinião de agência classificadora sobre risco de crédito relativo de emissor ou emissão; ele ajuda na comparação, mas não elimina risco nem garante pagamento.',
'2.1.1.1.8.1':'A poupança direciona parcela relevante de seus recursos ao financiamento habitacional e integra o Sistema Financeiro da Habitação; depósitos elegíveis contam com proteção do FGC dentro das regras vigentes.',
'2.1.1.1.8.2':'A poupança não cobra taxa de administração e, para pessoa física, tem rendimento isento de IR; custos indiretos aparecem principalmente como custo de oportunidade frente a alternativas.',
'2.1.1.1.8.3':'A rentabilidade da poupança segue regra legal ligada à Selic e à TR, enquanto seus principais riscos práticos são crédito da instituição acima da cobertura, inflação e perda de oportunidade.',
'2.1.1.1.8.4':'A data de aniversário da poupança é a data mensal em que o depósito completa novo período de remuneração; sacar antes dela pode fazer o valor retirado perder a remuneração daquele ciclo.',
'2.1.1.1.9':'A TR é uma taxa de referência calculada segundo metodologia oficial e usada em contratos e aplicações específicas, como a poupança; ela não deve ser confundida com Selic ou CDI.',
'2.1.1.1.10':'A TLP é a Taxa de Longo Prazo usada como referência em financiamentos de longo prazo, especialmente em operações do BNDES, combinando componente real e atualização conforme sua metodologia.',
'2.1.1.1.11':'Aplicações de renda fixa tributáveis de pessoa física seguem, em geral, tabela regressiva de IR que reduz a alíquota conforme aumenta o prazo, enquanto alguns títulos possuem isenção específica prevista em lei.',
'2.1.1.1.12':'O IOF sobre aplicações financeiras funciona de forma regressiva nos resgates de curtíssimo prazo e chega a zero após o período previsto na tabela vigente; ele é distinto do Imposto de Renda.',
'2.1.1.2.1':'Renda variável reúne ativos cujo retorno futuro não é conhecido de forma contratualmente predeterminada, pois depende de preços, resultados, eventos corporativos e condições de mercado.',
'2.1.1.2.2.1.1':'Sociedade limitada divide seu capital em quotas e segue regime societário próprio; sociedade anônima divide o capital em ações e possui estrutura de governança e regras específicas para companhias abertas ou fechadas.',
'2.1.1.2.2.1.2':'Companhia aberta possui valores mobiliários admitidos ao mercado e se submete à regulação da CVM; companhia fechada não acessa o mercado público de valores mobiliários da mesma forma.',
'2.1.1.2.2.1.3':'Empresa listada possui valores mobiliários negociados em ambiente organizado de mercado conforme requisitos aplicáveis; empresa não listada não tem seus valores mobiliários negociados dessa forma.',
'2.1.1.2.2.1.4':'Ações ordinárias e preferenciais representam direitos societários diferentes; units agrupam valores mobiliários, BDRs representam valores mobiliários emitidos no exterior e bônus de subscrição conferem direito de subscrever ações nas condições estabelecidas.',
'2.1.1.2.2.1.5':'Capital próprio vem dos sócios e acionistas e participa do risco residual do negócio; capital de terceiros vem de credores e gera obrigação contratual de pagamento.',
'2.1.1.2.2.1.6':'IPO é a oferta pública inicial que leva uma companhia ao mercado de capitais; OPA é oferta pública para aquisição de ações, usada em situações como aquisição relevante ou fechamento de capital conforme a regulação.',
'2.1.1.2.2.1.7':'Follow-on é uma oferta pública posterior ao IPO para distribuir novas ações ou ações já existentes, podendo captar recursos para a companhia quando a oferta é primária.',
'2.1.1.2.2.1.8':'No mercado primário, recursos da emissão chegam ao emissor quando há emissão nova; no secundário, investidores negociam entre si ativos já emitidos.',
'2.1.1.2.2.2.1':'A AGE delibera matérias extraordinárias previstas em lei ou estatuto, como mudanças relevantes de capital, estatuto ou reorganizações, fora do conjunto típico da assembleia anual.',
'2.1.1.2.2.2.2':'A AGO ocorre nos prazos legais para matérias recorrentes como contas da administração, demonstrações financeiras, destinação do resultado e eleição de administradores quando aplicável.',
'2.1.1.2.2.2.3':'Dividendos são parcela do lucro ou de reservas distribuída aos acionistas conforme legislação, estatuto e deliberações societárias; não constituem retorno garantido.',
'2.1.1.2.2.2.4':'Juros sobre Capital Próprio são forma de remuneração aos acionistas sujeita ao tratamento societário e tributário vigente; para o investidor, deve-se observar o valor líquido após tributação aplicável.',
'2.1.1.2.2.2.5':'Restituição de capital devolve aos acionistas parte do capital social nas hipóteses societárias permitidas e não deve ser confundida com distribuição ordinária de lucro.',
'2.1.1.2.2.2.6':'Grupamento reduz a quantidade de ações e eleva proporcionalmente o valor unitário teórico; desdobramento aumenta a quantidade e reduz proporcionalmente o valor unitário, sem criar riqueza por si só.',
'2.1.1.2.2.2.7':'Bonificação entrega novas ações ou direitos ao acionista em decorrência de capitalização de reservas ou lucros, alterando quantidade de ativos sem representar ganho econômico automático.',
'2.1.1.2.2.2.8':'Subscrição dá ao acionista direito de participar de uma nova emissão, normalmente preservando proporcionalmente sua participação se exercer o direito nas condições e prazos definidos.',
'2.1.1.2.2.3':'Ibovespa, IBrX 100 e IBrX 50 são índices de mercado com metodologias e universos diferentes usados para representar carteiras teóricas e acompanhar segmentos amplos do mercado acionário brasileiro.',
'2.1.1.2.3.1.1':'Segmentos de listagem da B3 estabelecem conjuntos adicionais de práticas de governança e requisitos de negociação; não são a mesma coisa que classe de ação.',
'2.1.1.2.3.1.2':'O conselho de administração orienta a estratégia e supervisiona a gestão da companhia nos limites legais e estatutários, representando papel distinto da diretoria executiva.',
'2.1.1.2.3.1.3':'Tag along protege acionistas em determinadas mudanças de controle, drag along pode obrigar minoritários a vender junto com o controlador quando previsto, e free float é a parcela de ações efetivamente disponível para negociação.',
'2.1.1.3.1':'Ganhos líquidos em renda variável seguem alíquotas específicas conforme o tipo de operação; operações comuns e day trade possuem tratamentos distintos, e o IRRF pode funcionar como antecipação.',
'2.1.1.3.2':'A legislação prevê hipóteses de isenção em renda variável, como o limite mensal de vendas de ações no mercado à vista para pessoa física, mas a isenção não vale para todas as operações ou produtos.',
'2.1.1.3.3':'Prejuízos em operações de renda variável podem ser compensados com ganhos futuros dentro das regras e categorias permitidas, exigindo controle separado quando a legislação diferencia modalidades como day trade.',
'2.1.1.3.4':'O IOF não é o tributo típico sobre ganho em operações comuns de ações em bolsa; quando a questão tratar tributação de renda variável, é essencial separar IR sobre ganhos, IRRF e hipóteses específicas de IOF.',
'2.1.1.4.1':'O COE combina componentes financeiros e derivativos para produzir um payoff ligado a cenários de mercado; entender o ativo de referência, barreiras e fórmula de remuneração é mais importante do que decorar um nome comercial.',
'2.1.1.4.2':'COEs podem ser emitidos com valor nominal protegido ou valor nominal em risco; proteção nominal reduz a perda do principal conforme as condições do certificado, mas não elimina risco de crédito do emissor.',
'2.1.1.4.3':'A tributação do COE segue o tratamento vigente aplicável aos seus rendimentos, devendo o investidor comparar retorno líquido, prazo e risco de crédito, e não apenas o payoff bruto.',
'2.1.2.1':'Fundos reúnem recursos de vários investidores em uma estrutura coletiva com política de investimento, prestadores de serviço, riscos, taxas e público-alvo definidos em documentos oficiais.',
'2.1.2.2.1':'A Resolução CVM 175 organiza constituição, funcionamento e comunicação dos fundos; regulamento e anexos da classe devem deixar claras regras, riscos, serviços e informações relevantes.',
'2.1.2.2.2':'Fundo de investimento é uma comunhão de recursos organizada sob forma condominial para aplicação coletiva em ativos, com direitos e obrigações definidos pela regulamentação e pelos documentos da estrutura.',
'2.1.2.2.3':'O fundo é constituído sob forma de condomínio e sua estrutura e classes seguem registro e supervisão da CVM conforme a Resolução 175 e anexos aplicáveis.',
'2.1.2.2.4':'A Resolução CVM 175 permite estruturar fundos em classes e subclasses, segregando direitos, obrigações, patrimônio e características de investidores dentro do mesmo fundo quando previsto.',
'2.1.2.2.5':'Segregação patrimonial significa que cada classe possui patrimônio separado das demais e dos prestadores de serviço, limitando a propagação de obrigações conforme o regime aplicável.',
'2.1.2.2.6':'Cota representa fração ideal do patrimônio da classe de fundo e seu valor varia conforme patrimônio líquido, quantidade de cotas e critérios de cálculo previstos.',
'2.1.2.2.7':'Classe aberta admite resgate de cotas conforme regras do regulamento; classe fechada normalmente não permite resgate antes do término, embora as cotas possam ser negociadas quando admitidas a mercado.',
'2.1.2.2.8':'Emissão é o processo de criação de novas cotas da classe, observando regras do regulamento, oferta e limites aplicáveis.',
'2.1.2.2.9':'Subscrição é o compromisso de adquirir cotas; integralização é a efetiva entrega de recursos ou ativos admitidos para formar o patrimônio da classe.',
'2.1.2.2.10':'Resgate é a saída do cotista mediante conversão e pagamento das cotas em classe aberta; amortização devolve parcela do valor da cota sem necessariamente extinguir a posição.',
'2.1.2.2.11':'Distribuição é a atividade de oferta e colocação de cotas junto a investidores, sujeita às regras de oferta, suitability, transparência e remuneração aplicáveis.',
'2.1.2.2.12':'No investimento por conta e ordem, um distribuidor atua perante o fundo em nome próprio por conta de clientes, mantendo controles individualizados e responsabilidades de identificação e informação.',
'2.1.2.2.13':'A participação política do investidor por conta e ordem deve preservar seus direitos de manifestação e voto conforme as regras do fundo e os procedimentos do distribuidor.',
'2.1.2.2.14':'Fundos devem divulgar informações periódicas e eventuais que permitam ao cotista acompanhar patrimônio, riscos, política e eventos relevantes conforme a regulação.',
'2.1.2.2.15':'Comunicações aos cotistas devem observar canais, prazos e conteúdos previstos na regulamentação e nos documentos da classe, garantindo acesso tempestivo às informações relevantes.',
'2.1.2.2.16':'A divulgação de informações e resultados deve ser consistente, verificável e compatível com a política da classe, evitando criar percepção enganosa sobre desempenho futuro.',
'2.1.2.2.17':'Divulgação de cota e rentabilidade apresenta valor da participação e desempenho histórico; rentabilidade passada não representa garantia de resultado futuro.',
'2.1.2.2.18.1':'Assembleia geral de cotistas delibera matérias comuns ao fundo quando a regulamentação ou regulamento exigem decisão coletiva dos investidores.',
'2.1.2.2.18.2':'Assembleia especial de cotistas trata matérias específicas de determinada classe ou subclasse, respeitando a segregação e os direitos daquele grupo de investidores.',
'2.1.2.2.19.1':'Administração e gestão são serviços essenciais da estrutura do fundo segundo a Resolução CVM 175, com responsabilidades próprias e não intercambiáveis.',
'2.1.2.2.19.2':'A administração fiduciária cuida da estrutura, funcionamento, controles e obrigações do fundo e das classes dentro de suas competências regulatórias.',
'2.1.2.2.19.3':'A gestão decide a alocação e negociação dos ativos da carteira dentro da política de investimento e dos limites aplicáveis, assumindo responsabilidade pelas decisões de investimento.',
'2.1.2.2.19.4':'Negociação em mercados organizados deve respeitar regras de mercado, melhores práticas de execução, controles e limites da política de investimento da classe.',
'2.1.2.2.20.1':'Taxa de administração remunera serviços previstos na estrutura do fundo e deve ser divulgada conforme a regulamentação e documentos da classe.',
'2.1.2.2.20.2':'Taxa de ingresso é cobrada no momento da aplicação quando prevista; ela reduz o valor efetivamente convertido em investimento e deve estar claramente informada.',
'2.1.2.2.20.3':'Taxa de saída pode ser cobrada no resgate ou saída conforme regras da classe, afetando o valor líquido recebido pelo investidor.',
'2.1.2.2.20.4':'Taxa máxima de distribuição estabelece limite de remuneração vinculada à distribuição quando aplicável e deve ser apresentada com transparência nos documentos do fundo.',
'2.1.2.2.20.5':'Acordos de remuneração entre prestadores precisam observar transparência, conflitos de interesse e limites regulatórios para não distorcer a recomendação ao cliente.',
'2.1.2.2.21':'Vedações da Resolução CVM 175 limitam condutas e operações que poderiam criar conflitos, uso indevido de patrimônio ou descumprimento da política da classe.',
'2.1.2.2.22':'Obrigações dos prestadores incluem cumprir regulamentação, regulamento, controles, divulgação e deveres perante investidores dentro das respectivas competências.',
'2.1.2.2.23':'Normas de conduta exigem diligência, lealdade, tratamento adequado de conflitos e atuação no interesse da classe e dos cotistas dentro das responsabilidades de cada prestador.',
'2.1.2.2.24':'Encargos são despesas que podem ser debitadas diretamente do patrimônio da classe quando expressamente autorizadas pela regulamentação; demais despesas devem seguir o regime aplicável ao prestador responsável.',
'2.1.2.2.25.1':'Com responsabilidade limitada, o cotista responde pelas obrigações da classe até o limite do valor das cotas subscritas, conforme previsão e regras da estrutura.',
'2.1.2.2.25.2':'Com responsabilidade ilimitada, a estrutura admite responsabilidade do cotista além do valor das cotas nas hipóteses e condições definidas nos documentos e na regulamentação.',
'2.1.2.2.25.3':'Patrimônio líquido negativo ocorre quando as obrigações superam os ativos da classe e aciona procedimentos específicos de administração, comunicação e deliberação previstos na regulamentação.',
'2.1.2.2.25.4':'A insolvência da classe trata a incapacidade patrimonial de cumprir obrigações segundo o regime jurídico próprio introduzido para classes de fundos, sem confundir a classe com seus prestadores.',
'2.1.2.3.1':'No FIF, a prestação de serviços segue a Resolução CVM 175 e o Anexo Normativo I, distribuindo responsabilidades entre administrador, gestor e demais prestadores contratados.',
'2.1.2.3.2':'Administrador, gestor e custodiante exercem funções distintas no FIF: estrutura e controles, decisões de investimento e guarda/controle de ativos, respectivamente, conforme seus contratos e deveres regulatórios.',
'2.1.2.3.3.1':'As vedações do FIF limitam operações ou condutas incompatíveis com o regime da classe, sua política de investimento e os deveres dos prestadores.',
'2.1.2.3.4':'Distribuição e subscrição de cotas de FIF devem respeitar público-alvo, documentos, suitability, regras de oferta e procedimentos de integralização.',
'2.1.2.3.5.1':'Ativos financeiros no Brasil elegíveis à carteira de FIF são definidos pela regulamentação e devem respeitar política, risco e limites da classe.',
'2.1.2.3.5.2':'Investimentos no exterior por FIF são permitidos dentro das condições, limites e controles da regulamentação e da política da classe.',
'2.1.2.3.5.3':'Limites por emissor controlam concentração de crédito e exposição a uma mesma contraparte ou grupo, reduzindo dependência excessiva de um único emissor.',
'2.1.2.3.5.4':'Limites por modalidade controlam quanto da carteira pode ser alocado em determinadas categorias de ativos, preservando o enquadramento e o perfil de risco da classe.',
'2.1.2.3.5.5':'Gestor e demais responsáveis devem monitorar limites de concentração e reenquadrar a carteira conforme regras e prazos quando houver desenquadramento.',
'2.1.2.3.6.1':'Fundo de renda fixa tem como principal fator de risco a variação de taxas de juros, índices de preços ou ambos, devendo respeitar os critérios de enquadramento da regulamentação.',
'2.1.2.3.6.2':'Fundo de ações mantém exposição predominante ao mercado acionário conforme os percentuais e ativos elegíveis definidos na regulamentação.',
'2.1.2.3.6.3':'Fundo cambial mantém exposição predominante ao fator de risco de moeda estrangeira ou variação cambial segundo o enquadramento regulatório.',
'2.1.2.3.6.4':'Fundo multimercado combina diferentes fatores de risco e estratégias sem ficar restrito a um único enquadramento de renda fixa, ações ou câmbio.',
'2.1.2.3.6.5':'FI-Infra direciona sua política a ativos ligados a projetos de infraestrutura e segue requisitos específicos de carteira e tributação previstos em lei e regulamentação.',
'2.1.2.3.6.6':'Fundos destinados à garantia de locação imobiliária seguem finalidade específica de garantir obrigações de contratos de locação, com política e ativos compatíveis com esse objetivo.',
'2.1.2.3.6.7':'Concentração em crédito privado indica exposição relevante a títulos emitidos por agentes privados e exige atenção reforçada a risco de crédito, liquidez e divulgação.',
'2.1.2.3.7':'Um FIF pode investir em cotas de outros fundos dentro de limites e regras de enquadramento, transferindo parte da exposição econômica para as carteiras dos fundos investidos.',
'2.1.2.3.8':'Exposição ao risco de capital mede a possibilidade de perdas decorrentes de posições que podem produzir perda superior ao patrimônio disponível, exigindo controles e limites regulatórios.',
'2.1.2.3.9':'Classes restritas são destinadas a públicos específicos e podem ter flexibilizações ou regras próprias compatíveis com o nível de sofisticação e enquadramento dos investidores.',
'2.1.2.3.10':'Encargos de FIF são despesas debitáveis da classe quando autorizadas pela Resolução CVM 175 e seu Anexo I; despesas fora desse rol seguem responsabilidade definida pela norma.',
'2.1.3.1':'A tributação de fundos depende da classificação tributária, carteira, prazo e eventos como resgate, amortização ou tributação periódica, devendo ser lida separadamente da classificação regulatória do fundo.',
'2.1.3.2.1':'IOF em fundos e aplicações de renda fixa pode incidir em resgates de curtíssimo prazo conforme tabela regressiva, chegando a zero depois do prazo definido na legislação.',
'2.1.3.2.2':'O IR sobre fundos varia por categoria e prazo; fundos de longo prazo usam tabela regressiva, fundos de curto prazo têm tabela própria e fundos de ações possuem tratamento específico.',
'2.1.4.1':'FII é condomínio de investimento imobiliário cujas cotas, quando negociadas em mercado organizado, permitem exposição a ativos imobiliários sem compra direta do imóvel e seguem regime próprio de classe fechada.',
'2.1.4.2':'FIIs podem carregar risco de liquidez das cotas, crédito dos devedores, vacância dos imóveis, concentração e oscilação de valor dos ativos; a combinação depende da carteira concreta.',
'2.1.4.3':'Distribuições de FIIs decorrem dos resultados e regras legais do fundo, não são dividendos garantidos e podem variar com aluguéis, juros, inadimplência, vacância e eventos da carteira.',
'2.1.4.4':'FIIs podem cobrar taxas previstas em seus documentos e realizar novas emissões por subscrição; o investidor deve avaliar diluição, preço de emissão, custos e uso dos recursos.',
'2.1.4.5':'FII de tijolo concentra imóveis físicos e renda imobiliária, fundo de papel concentra títulos e recebíveis imobiliários, e fundo híbrido combina essas exposições.',
'2.1.4.6':'A tributação de FIIs diferencia rendimentos distribuídos e ganho na negociação ou resgate de cotas, com condições específicas para benefícios fiscais e regras sujeitas à legislação vigente.'
}
