export const macro2PrevidenciaCreditoDefinitions: Record<string,string> = {
'2.2.1.1':'PGBL é plano de previdência complementar aberta em que, atendidas as condições legais, contribuições podem ser deduzidas da base tributável dentro do limite aplicável; no resgate ou benefício, a tributação incide sobre o valor recebido segundo o regime escolhido.',
'2.2.1.2':'VGBL é seguro de pessoas com cobertura por sobrevivência usado para acumulação de longo prazo; não gera a mesma dedução fiscal do PGBL e, em regra, o IR incide apenas sobre os rendimentos no resgate ou benefício.',
'2.2.2.1':'No regime progressivo de previdência, a tributação segue a lógica da tabela progressiva do IR, com antecipação na fonte e ajuste conforme a situação fiscal da pessoa, sendo mais aderente quando renda tributável futura tende a ser menor.',
'2.2.2.2':'No regime regressivo de previdência, a alíquota diminui conforme o prazo de cada contribuição, favorecendo horizontes longos e sendo definitiva na fonte conforme as regras vigentes.',
'2.2.3.1':'Planos de previdência possuem fase de acumulação, em que contribuições formam a reserva, e fase de benefícios, em que o patrimônio é convertido em renda ou pagamento conforme a modalidade contratada.',
'2.2.3.2':'Taxas em previdência podem remunerar administração do fundo ou cobrir carregamento/saída quando previstas; elas reduzem o resultado líquido e devem ser comparadas com a política e o serviço oferecido.',
'2.2.3.3':'Portabilidade permite transferir recursos entre planos compatíveis sem caracterizar resgate, preservando a finalidade previdenciária e seguindo regras de carência, regime tributário e titularidade aplicáveis.',
'2.2.3.4.1':'Renda Mensal Vitalícia paga benefício enquanto a pessoa assistida viver, cessando conforme as condições do contrato e sem prazo certo de duração.',
'2.2.3.4.2':'Renda Mensal Vitalícia com prazo mínimo garantido paga enquanto a pessoa vive e mantém pagamentos aos beneficiários pelo período mínimo contratado se ocorrer falecimento antes do prazo.',
'2.2.3.4.3':'Renda Mensal Vitalícia com reversão a beneficiário indicado mantém renda à pessoa assistida e, após seu falecimento, reverte percentual ou valor ao beneficiário conforme o plano.',
'2.2.3.4.4':'Renda Mensal Vitalícia reversível ao cônjuge com continuidade aos menores combina proteção vitalícia com reversão sucessiva, conforme percentuais e condições definidos no contrato.',
'2.2.3.4.5':'Renda mensal temporária paga benefício por período determinado enquanto a pessoa estiver viva, cessando no fim do prazo ou no falecimento conforme as condições previstas.',
'2.2.3.4.6':'Renda mensal por prazo certo paga durante número fixo de meses, independentemente da sobrevivência da pessoa assistida, observada a indicação de beneficiários e regras do plano.',
'2.2.3.4.7':'Pagamento único liquida a reserva previdenciária de uma vez, substituindo a conversão em renda periódica e concentrando o impacto financeiro e tributário no evento.',
'2.3.1.1':'Rating de crédito, score e comprovação de renda são instrumentos para avaliar capacidade e probabilidade de pagamento; nenhum deles, isoladamente, substitui análise completa de crédito.',
'2.3.1.2':'Empréstimo disponibiliza recursos sem vinculação obrigatória a um bem específico; financiamento costuma ter destinação definida e pode usar o bem financiado como garantia; leasing envolve arrendamento com regras próprias.',
'2.3.1.3':'O SCR reúne informações de operações de crédito reportadas ao Banco Central e auxilia instituições e clientes na avaliação de endividamento e histórico, respeitando regras de acesso e atualização.',
'2.3.2.1':'Cartão de crédito oferece limite para compras e pode gerar juros elevados quando a fatura não é paga integralmente; pagamento parcial leva saldo a modalidades de financiamento segundo regras vigentes.',
'2.3.2.2':'A taxa efetiva do refinanciamento de fatura depende do saldo financiado, prazo e encargos; comparar CET e valor total a pagar é mais útil do que olhar apenas a taxa nominal.',
'2.3.3.1':'Cheque especial é crédito rotativo vinculado à conta corrente; juros e IOF incidem sobre o valor e período efetivamente utilizados, tornando uso prolongado normalmente caro.',
'2.3.4.1':'No crédito consignado, parcelas são descontadas diretamente de renda ou benefício e a margem consignável limita o comprometimento permitido conforme a legislação aplicável.',
'2.3.4.2':'O consignado costuma ter juros menores e prazos mais longos que crédito pessoal sem garantia porque a forma de pagamento reduz o risco de inadimplência para o credor.',
'2.3.5.1':'No CDC, um bem pode servir como garantia ou estar vinculado à operação, reduzindo risco do credor e influenciando taxa, prazo e condições de retomada em caso de inadimplência.',
'2.3.5.2':'CDC financia consumo com prazo e destinação definidos; avaliar valor financiado, entrada, CET, prazo e valor total é essencial antes de comparar propostas.',
'2.3.6':'Crédito imobiliário financia aquisição, construção ou reforma de imóveis com prazos longos e garantias específicas, exigindo análise de renda, entrada, sistema de amortização, juros e custos acessórios.',
'2.3.7':'Capital de giro financia necessidades operacionais de empresas, como estoques, fornecedores e ciclo financeiro; prazo e estrutura devem ser compatíveis com a geração de caixa do negócio.',
'2.3.8':'Consórcio é autofinanciamento coletivo administrado por empresa autorizada, sem promessa de contemplação imediata; o participante paga parcelas e concorre a crédito por sorteio ou lance conforme as regras do grupo.'
}
