import { useCallback, useEffect, useMemo, useState } from 'react'
import { CheckCircle2, ChevronDown, ChevronRight, Circle, CircleDot, Star } from 'lucide-react'
import { Link } from 'react-router-dom'
import metadata from '../../content/cpa/metadata.json'
import { cpaCurriculum } from '../../content/cpa/curriculum'
import { cpaLessonMap } from '../../content/cpa/lessons'
import type { CurriculumUnit } from '../../content/cpa/schema'
import { Badge } from '../components/ui/Badge'
import { Card } from '../components/ui/Card'
import { Progress } from '../components/ui/Progress'
import { STORAGE_CHANGED_EVENT, reportStorageError } from '../lib/storage/events'
import { getAllLessonProgress } from '../lib/storage/repositories/learningRepository'
import type { LessonStatus } from '../lib/storage/types'

type TreeNode=CurriculumUnit&{children:TreeNode[]}
const statusMeta={not_started:{label:'Não iniciado',symbol:'○',icon:Circle,className:'text-slate-400'},in_progress:{label:'Em andamento',symbol:'◔',icon:CircleDot,className:'text-amber-500'},completed:{label:'Estudado',symbol:'✓',icon:CheckCircle2,className:'text-emerald-500'},mastered:{label:'Dominado',symbol:'★',icon:Star,className:'text-violet-500'}} satisfies Record<LessonStatus,{label:string;symbol:string;icon:typeof Circle;className:string}>
function buildTree(items:CurriculumUnit[]){const nodes=new Map(items.map((item)=>[item.pdCode,{...item,children:[] as TreeNode[]}]));const roots:TreeNode[]=[];for(const node of nodes.values()){if(node.parentCode)nodes.get(node.parentCode)?.children.push(node);else roots.push(node)}return roots}
function leafCodes(node:TreeNode):string[]{return node.children.length?node.children.flatMap(leafCodes):[node.pdCode]}
function aggregate(node:TreeNode,statuses:Map<string,LessonStatus>):LessonStatus{if(!node.children.length)return statuses.get(node.pdCode)??'not_started';const children=node.children.map((x)=>aggregate(x,statuses));if(children.every((x)=>x==='mastered'))return'mastered';if(children.every((x)=>x==='completed'||x==='mastered'))return'completed';if(children.some((x)=>x!=='not_started'))return'in_progress';return'not_started'}
function Node({node,statuses,expanded,onToggle,depth=0}:{node:TreeNode;statuses:Map<string,LessonStatus>;expanded:Set<string>;onToggle:(x:string)=>void;depth?:number}){const has=node.children.length>0;const open=expanded.has(node.pdCode);const status=aggregate(node,statuses);const meta=statusMeta[status];const Icon=meta.icon;const lesson=cpaLessonMap.has(node.pdCode);const title=<><span className="mr-2 font-mono text-xs font-bold text-emerald-700 dark:text-emerald-300">{node.pdCode}</span><span className={depth<2?'text-sm font-semibold':'text-sm text-slate-700 dark:text-slate-200'}>{node.title}</span>{node.weight?<span className="ml-2 text-xs font-semibold text-slate-500">{node.weight}%</span>:null}</>;return <div><div className="flex items-start gap-2 border-b border-slate-100 py-3 pr-3 dark:border-white/[0.06]" style={{paddingLeft:`${12+Math.min(depth,7)*18}px`}}>{has?<button onClick={()=>onToggle(node.pdCode)} className="mt-0.5 grid h-6 w-6 shrink-0 place-items-center rounded-lg text-slate-400 hover:bg-slate-100 dark:hover:bg-white/10">{open?<ChevronDown className="h-4 w-4"/>:<ChevronRight className="h-4 w-4"/>}</button>:<span className="h-6 w-6 shrink-0"/>}<div className="min-w-0 flex-1">{lesson?<Link className="hover:text-emerald-700 dark:hover:text-emerald-300" to={`/conteudos/${node.pdCode}`}>{title}</Link>:has?<button onClick={()=>onToggle(node.pdCode)} className="text-left">{title}</button>:title}</div><span className={`inline-flex shrink-0 items-center gap-1.5 pt-0.5 text-xs font-medium ${meta.className}`}><Icon className="h-3.5 w-3.5"/><span className="hidden sm:inline">{meta.label}</span><span className="sm:hidden">{meta.symbol}</span></span></div>{has&&open?node.children.map((child)=><Node key={child.pdCode} node={child} statuses={statuses} expanded={expanded} onToggle={onToggle} depth={depth+1}/>):null}</div>}
export function CurriculumPage(){const tree=useMemo(()=>buildTree(cpaCurriculum),[]);const [expanded,setExpanded]=useState(()=>new Set(['1','2','3','4']));const [statuses,setStatuses]=useState<Map<string,LessonStatus>>(new Map());const load=useCallback(async()=>setStatuses(new Map((await getAllLessonProgress()).map((row)=>[row.pdCode,row.status]))),[]);useEffect(()=>{void load().catch(reportStorageError);const listener=()=>void load().catch(reportStorageError);window.addEventListener(STORAGE_CHANGED_EVENT,listener);return()=>window.removeEventListener(STORAGE_CHANGED_EVENT,listener)},[load]);function toggle(code:string){setExpanded((current)=>{const next=new Set(current);next.has(code)?next.delete(code):next.add(code);return next})}const cards=tree.map((root)=>{const leaves=leafCodes(root);const studied=leaves.filter((code)=>{const s=statuses.get(code);return s==='completed'||s==='mastered'}).length;return{root,total:leaves.length,studied,progress:leaves.length?Math.round(studied/leaves.length*100):0}});return <div className="mx-auto max-w-6xl space-y-6"><div><div className="mb-2 flex flex-wrap items-center gap-2"><Badge>CPA · PD {metadata.programVersion}</Badge><span className="text-sm text-slate-500">Vigência: 01/01/2026</span></div><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Trilha de Estudos</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">A hierarquia completa do Programa Detalhado permanece visível. O progresso é local e todos os 445 PDs terminais possuem aula completa, mini quiz, flashcards e fontes oficiais.</p></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({root,total,studied,progress})=><Card key={root.pdCode} className="p-4"><div className="flex items-center justify-between"><span className="font-mono text-xs font-bold text-emerald-600 dark:text-emerald-300">{root.pdCode}</span><span className="text-sm font-black">{root.weight}%</span></div><p className="mt-2 min-h-10 text-sm font-semibold leading-5">{root.title}</p><div className="mt-4"><Progress value={progress}/></div><p className="mt-2 text-xs text-slate-500">{studied} / {total} itens terminais estudados · {progress}%</p></Card>)}</div><div className="flex flex-wrap gap-4 text-xs">{Object.values(statusMeta).map((item)=>{const Icon=item.icon;return <span key={item.label} className={`inline-flex items-center gap-1.5 ${item.className}`}><Icon className="h-3.5 w-3.5"/>{item.symbol} {item.label}</span>})}</div><div className="space-y-4">{tree.map((root)=><Card key={root.pdCode} className="overflow-hidden p-0"><Node node={root} statuses={statuses} expanded={expanded} onToggle={toggle}/></Card>)}</div><p className="text-xs leading-5 text-slate-500">Fonte: ANBIMA — Programa Detalhado CPA, versão {metadata.programVersion}, revisão de 04/06/2025, vigente desde 01/01/2026. Última verificação: 20/09/2026.</p></div>}
