import { Link } from 'react-router-dom'
import { ArrowRight, BookOpen, CheckCircle2, Clock3, Target } from 'lucide-react'
import { useDashboardData } from '../features/dashboard/useDashboardData'
import { useDailyStudy } from '../hooks/useDailyStudy'
import { nextModule, moduleStateLabels, MASTERY_RULE } from '../lib/course/progress'
import { practiceEvidence } from '../lib/qualityEvidence'
import { Card } from '../components/ui/Card'
import { Button } from '../components/ui/Button'
import { StatCard } from '../components/ui/StatCard'
import { Progress } from '../components/ui/Progress'
import { BackupReminder } from '../components/BackupReminder'
export function DashboardPage() {
  const {data:d,loading}=useDashboardData()
  const daily=useDailyStudy()
  if(loading||!d||!daily.data)return <Card><p role="status">Carregando seus módulos...</p></Card>
  const rows=daily.data.modules
  const current=nextModule(rows)
  const completed=rows.filter(row=>row.completed).length
  const mastered=rows.filter(row=>row.state==='mastered').length
  const samples=practiceEvidence(daily.data.attempts,daily.data.simulations)
  const unique=[...new Map(samples.filter(row=>Date.now()-Date.parse(row.at)<=30*86400000).map(row=>[row.questionId,row])).values()]
  const accuracy=unique.length?Math.round(unique.filter(row=>row.correct).length/unique.length*100):null
  const today=daily.sessions.today?.steps??daily.today
  const review=daily.sessions.review?.steps??daily.review
  const done=daily.sessions.today?.index===today.length&&today.length>0
  return <div className="mx-auto max-w-6xl space-y-6"><header><p className="text-sm font-semibold text-emerald-700 dark:text-emerald-300">CPA · sua trilha principal</p><h1 className="mt-2 text-3xl font-bold">Olá, {d.name}.</h1><p className="mt-2 text-slate-500">20 módulos para avançar. A biblioteca do edital e a Apostila V26 estão integradas à trilha.</p></header>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Progresso da trilha" value={`${completed}/20`} helper={`${mastered} com evidência de domínio`} icon={<CheckCircle2 className="h-5 w-5"/>}/><StatCard label="Leitura atual" value={`${current.read}/${current.total}`} helper={current.module.title} icon={<BookOpen className="h-5 w-5"/>}/><StatCard label="Acerto recente" value={accuracy===null?'—':`${accuracy}%`} helper={`${unique.length} questões distintas revisadas · 30 dias`} icon={<Target className="h-5 w-5"/>}/><StatCard label="Tempo ativo" value={`${d.studyHours}h`} helper={`${d.streak} dia(s) de sequência`} icon={<Clock3 className="h-5 w-5"/>}/></div>
    <div className="grid gap-5 lg:grid-cols-[1.3fr_1fr]"><Card className="border-emerald-400/30 bg-gradient-to-br from-emerald-400/10 to-sky-400/5"><p className="text-xs font-bold uppercase tracking-widest text-emerald-700 dark:text-emerald-300">Seu próximo passo</p><h2 className="mt-3 text-2xl font-bold">Sessão de hoje · {today.reduce((sum,s)=>sum+s.minutes,0)} min</h2><p className="mt-3 text-sm leading-7 text-slate-500">{today.filter(s=>s.type==='reading').length} partes de leitura · {today.filter(s=>s.type==='question').length} questões · {today.filter(s=>s.type==='flashcard').length} flashcards. Uma sequência pronta com base no seu histórico.</p>{daily.sessions.today?<Link to="/hoje" className="mt-6 inline-block"><Button>{done?'Ver sessão concluída':'Continuar sessão de hoje'}<ArrowRight className="h-4 w-4"/></Button></Link>:<div className="mt-6"><p className="mb-2 text-xs font-bold uppercase tracking-wide text-slate-500">Quanto tempo você tem?</p><div className="flex flex-wrap gap-2">{[10,25,45].map(minutes=><Link key={minutes} to={`/hoje?minutes=${minutes}`}><Button variant="secondary">{minutes} min</Button></Link>)}<Link to="/hoje"><Button>Minha meta<ArrowRight className="h-4 w-4"/></Button></Link></div></div>}</Card><Card><p className="text-xs font-semibold text-slate-500">Módulo atual · {moduleStateLabels[current.state]}</p><h2 className="mt-3 text-xl font-bold">{current.module.title}</h2><div className="my-4"><Progress value={current.read/current.total*100}/></div><p className="text-sm text-slate-500">{current.read}/{current.total} partes lidas · {current.exam?`Último simulado: ${current.exam.score}%`:'Simulado ainda não concluído'}</p><div className="mt-5 flex flex-wrap gap-3"><Link to={`/modulos/${current.module.id}`} className="text-sm font-bold text-emerald-700 dark:text-emerald-300">Continuar módulo →</Link><Link to={`/apostila/${current.module.id}`} className="text-sm font-bold text-sky-700 dark:text-sky-300">Ler apostila →</Link></div></Card></div>
    <Card><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-xl font-bold">Revisão de hoje</h2><p className="mt-2 text-sm leading-6 text-slate-500">{review.length?`${review.length} itens · ${review.reduce((sum,s)=>sum+s.minutes,0)} min estimados. Erros, memória e revisão espaçada em uma fila.`:'Sem pendências por enquanto. Sua leitura e prática alimentarão a revisão.'}</p></div><Link to="/revisao"><Button variant="secondary">Abrir revisão de hoje</Button></Link></div></Card>
    <BackupReminder/>
    <Card><h2 className="text-lg font-bold">Módulos que merecem atenção</h2><div className="mt-4 space-y-3">{rows.filter(row=>row.needsReview).slice(0,3).map(row=><Link key={row.module.id} to={`/modulos/${row.module.id}`} className="block rounded-xl bg-amber-400/10 p-3 text-sm font-semibold">{row.module.title} · precisa revisar →</Link>)}{!rows.some(row=>row.needsReview)&&<p className="text-sm text-slate-500">Nenhum alerta com evidência suficiente. Continue estudando para construir seu histórico.</p>}</div><details className="mt-5 text-xs leading-6 text-slate-500"><summary className="cursor-pointer font-semibold">Como medimos conclusão e domínio?</summary><p>Concluído: todas as partes lidas e um simulado finalizado, qualquer que seja a nota. Domínio: {MASTERY_RULE} É uma meta interna de estudo, sem previsão de aprovação.</p></details></Card>
    <details className="rounded-2xl border border-slate-200 p-5 dark:border-white/10"><summary className="cursor-pointer font-semibold">Biblioteca e cobertura detalhada do edital · {d.lessonsStudied}/{d.availableLessons}</summary><p className="my-4 text-sm leading-7 text-slate-500">Os 445 pontos formam a base detalhada da Apostila V26. O progresso individual abaixo continua independente dos 20 módulos e preserva seus dados anteriores.</p><div className="space-y-4">{d.themeProgress.map(theme=><div key={theme.macroCode}><p className="mb-2 text-sm">{theme.title} · {theme.studied}/{theme.total}</p><Progress value={theme.progress}/></div>)}</div><Link to="/edital" className="mt-5 inline-block text-sm font-semibold text-emerald-700 dark:text-emerald-300">Consultar mapa do edital →</Link></details>
  </div>
}
