import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, History, TrendingUp } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Badge } from '../components/ui/Badge'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { getSimulations } from '../lib/storage/repositories/simulationRepository'
import type { SimulationRecord } from '../lib/storage/types'

function formatDate(value:string){return new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value))}
function formatDuration(seconds:number){const minutes=Math.floor(seconds/60);return `${minutes} min`}

function EvolutionChart({rows}:{rows:SimulationRecord[]}){
  const points=rows.map((row,index)=>({x:rows.length===1?50:(index/(rows.length-1))*100,y:100-(row.payload.result?.scorePercent??0),score:row.payload.result?.scorePercent??0}))
  const path=points.map((point,index)=>`${index===0?'M':'L'} ${point.x} ${point.y}`).join(' ')
  return <div><div className="relative h-64 w-full overflow-hidden rounded-2xl bg-slate-50 p-4 dark:bg-white/[0.03]"><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="h-full w-full overflow-visible" role="img" aria-label="Gráfico de evolução de acertos nos simulados"><line x1="0" y1="30" x2="100" y2="30" stroke="currentColor" strokeOpacity="0.15" strokeDasharray="2 2"/><line x1="0" y1="50" x2="100" y2="50" stroke="currentColor" strokeOpacity="0.08" strokeDasharray="2 2"/><path d={path} fill="none" stroke="currentColor" strokeWidth="1.5" vectorEffect="non-scaling-stroke" className="text-emerald-500"/>{points.map((point,index)=><circle key={index} cx={point.x} cy={point.y} r="2" fill="currentColor" vectorEffect="non-scaling-stroke" className="text-emerald-500"/>)}</svg><div className="pointer-events-none absolute inset-y-4 left-4 flex flex-col justify-between text-[10px] text-slate-400"><span>100%</span><span>70%</span><span>50%</span><span>0%</span></div></div><div className="mt-3 flex items-center justify-between text-xs text-slate-500"><span>{rows.length?formatDate(rows[0].completedAt!):''}</span><span>{rows.length>1?formatDate(rows[rows.length-1].completedAt!):''}</span></div></div>
}

export function SimulationHistoryPage(){
  const [rows,setRows]=useState<SimulationRecord[]>([]);const [loading,setLoading]=useState(true);const [filter,setFilter]=useState<'all'|'official_exam'>('all')
  useEffect(()=>{void getSimulations().then((items)=>{setRows(items.filter((item)=>item.completedAt&&item.payload.result));setLoading(false)})},[])
  const filtered=useMemo(()=>rows.filter((row)=>filter==='all'||row.payload.mode===filter),[rows,filter])
  const chronological=useMemo(()=>[...filtered].sort((a,b)=>a.completedAt!.localeCompare(b.completedAt!)),[filtered])
  const best=filtered.length?Math.max(...filtered.map((row)=>row.payload.result?.scorePercent??0)):0
  const average=filtered.length?Math.round(filtered.reduce((sum,row)=>sum+(row.payload.result?.scorePercent??0),0)/filtered.length):0
  return <div className="mx-auto max-w-6xl space-y-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-2 flex items-center gap-2"><Badge>Histórico</Badge><span className="text-sm text-slate-500">salvo localmente</span></div><h1 className="text-3xl font-black tracking-tight sm:text-4xl">Evolução nos simulados</h1><p className="mt-2 text-sm text-slate-500">Acompanhe acertos ao longo do tempo sem depender de conta ou sincronização remota.</p></div><Link to="/simulados"><Button>Novo simulado</Button></Link></div>
  <div className="flex gap-2"><button onClick={()=>setFilter('all')} className={`rounded-xl border px-3 py-2 text-xs font-semibold ${filter==='all'?'border-emerald-400 bg-emerald-400/10 text-emerald-700 dark:text-emerald-300':'border-slate-200 dark:border-white/10'}`}>Todos</button><button onClick={()=>setFilter('official_exam')} className={`rounded-xl border px-3 py-2 text-xs font-semibold ${filter==='official_exam'?'border-emerald-400 bg-emerald-400/10 text-emerald-700 dark:text-emerald-300':'border-slate-200 dark:border-white/10'}`}>Modo Prova CPA</button></div>
  {loading?<Card><p className="py-10 text-center text-sm text-slate-500">Carregando histórico...</p></Card>:filtered.length===0?<Card><div className="py-12 text-center"><History className="mx-auto h-9 w-9 text-slate-300"/><h2 className="mt-3 font-bold">Ainda não há simulados concluídos</h2><p className="mt-1 text-sm text-slate-500">Conclua um simulado para começar seu gráfico de evolução.</p><Link to="/simulados"><Button className="mt-5">Começar agora</Button></Link></div></Card>:<><div className="grid gap-4 sm:grid-cols-3"><Card><p className="text-xs text-slate-500">Simulados</p><p className="mt-1 text-2xl font-black">{filtered.length}</p></Card><Card><p className="text-xs text-slate-500">Média</p><p className="mt-1 text-2xl font-black">{average}%</p></Card><Card><p className="text-xs text-slate-500">Melhor resultado</p><p className="mt-1 text-2xl font-black">{best}%</p></Card></div><Card><div className="flex items-center gap-2"><TrendingUp className="h-5 w-5 text-emerald-500"/><h2 className="font-bold">Gráfico de evolução</h2></div><div className="mt-5"><EvolutionChart rows={chronological}/></div></Card><div className="space-y-3">{filtered.map((row)=>{const result=row.payload.result!;return <Card key={row.id} className="flex flex-col gap-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><Badge>{row.payload.label}</Badge>{row.payload.mode==='official_exam'&&result.passed!==null?<span className={`text-xs font-bold ${result.passed?'text-emerald-600':'text-rose-600'}`}>{result.passed?'APROVADO':'REPROVADO'}</span>:null}</div><p className="mt-2 text-xs text-slate-500">{formatDate(row.completedAt!)} · {formatDuration(result.timeUsedSeconds)}</p></div><div className="flex items-center gap-5"><div className="text-right"><p className="text-2xl font-black">{result.correct}/{result.total}</p><p className="text-xs text-slate-500">{result.scorePercent}%</p></div><Link to={`/prova/${row.id}/resultado`}><Button variant="secondary">Detalhes <ArrowRight className="h-4 w-4"/></Button></Link></div></Card>})}</div></>}
  </div>
}
