import { reportStorageError } from '../lib/storage/events'
import { ArrowLeft, CheckCircle2, Clock3, Flag, RotateCcw, XCircle } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useEffect, useMemo, useState } from 'react'
import { getSimulationQuestions } from '../lib/storage/repositories/simulationRepository'
import { cpaLessonMap } from '../../content/cpa/lessons'
import { Badge } from '../components/ui/Badge'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { Progress } from '../components/ui/Progress'
import { getSimulation } from '../lib/storage/repositories/simulationRepository'
import type { SimulationRecord } from '../lib/storage/types'

const themeLabels:Record<string,string>={'1':'Tema 1','2':'Tema 2','3':'Tema 3','4':'Tema 4'}
const difficultyLabels={easy:'Fácil',medium:'Médio',hard:'Difícil'} as const
const formatDuration=(seconds:number)=>`${Math.floor(seconds/60)}min ${String(seconds%60).padStart(2,'0')}s`

export function SimulationResultPage(){
  const {simulationId}=useParams();const navigate=useNavigate();const [simulation,setSimulation]=useState<SimulationRecord|null>(null);const [loading,setLoading]=useState(true)
  useEffect(()=>{if(!simulationId)return;void getSimulation(simulationId).then((record)=>{if(!record){navigate('/simulados',{replace:true});return}if(!record.completedAt||!record.payload.result){navigate(`/prova/${record.id}`,{replace:true});return}setSimulation(record);setLoading(false)}).catch(reportStorageError)},[simulationId,navigate])
  const wrong=useMemo(()=>simulation?.payload.result?.questionResults.filter((row)=>!row.isCorrect&&row.selectedAnswer!==null)??[],[simulation])
  if(loading||!simulation||!simulation.payload.result)return <div className="grid min-h-screen place-items-center bg-slate-100 text-sm text-slate-500 dark:bg-[#07111c] dark:text-slate-300">Carregando resultado...</div>
  const result=simulation.payload.result;const official=simulation.payload.mode==='official_exam'&&result.cutoff!==null;const marked=simulation.payload.markedForReview
  return <div className="min-h-screen bg-slate-100 text-slate-950 dark:bg-[#07111c] dark:text-slate-100">
    <header className="border-b border-slate-200 bg-white dark:border-white/10 dark:bg-[#091621]"><div className="mx-auto flex max-w-6xl items-center gap-3 px-4 py-4 sm:px-6"><div className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-400 font-black text-slate-950">C</div><div><p className="text-sm font-black">Resultado · {simulation.payload.label}</p><p className="text-[11px] text-slate-500">CPA</p></div><Link className="ml-auto" to="/simulados"><Button variant="secondary"><ArrowLeft className="h-4 w-4"/>Voltar</Button></Link></div></header>
    <main className="mx-auto max-w-6xl space-y-6 p-4 sm:p-6 lg:p-8">
      <Card className={`overflow-hidden p-0 ${official?(result.passed?'border-emerald-300':'border-rose-300'):''}`}><div className="grid gap-6 p-6 sm:p-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-slate-400">Resultado</p><div className="mt-2 flex flex-wrap items-baseline gap-3"><span className="text-5xl font-black">{result.correct} / {result.total}</span><span className="text-lg font-bold text-slate-500">{result.scorePercent}%</span></div>{official?<div className={`mt-5 inline-flex items-center gap-2 rounded-2xl px-4 py-2 text-sm font-black ${result.passed?'bg-emerald-400/15 text-emerald-700 dark:text-emerald-300':'bg-rose-400/10 text-rose-700 dark:text-rose-300'}`}>{result.passed?<CheckCircle2 className="h-5 w-5"/>:<XCircle className="h-5 w-5"/>}{result.passed?'META LEGADA ATINGIDA':'META LEGADA NÃO ATINGIDA'}</div>:<Badge>Treino</Badge>}{official?<p className="mt-3 text-sm text-slate-500">Referência do treino legado: <strong>{result.cutoff}/50</strong></p>:<p className="mt-3 text-sm text-slate-500">Este modo de treino não possui corte oficial.</p>}</div><div className="grid grid-cols-2 gap-3 text-center"><div className="rounded-2xl bg-slate-100 p-4 dark:bg-white/[0.04]"><Clock3 className="mx-auto h-5 w-5 text-slate-400"/><p className="mt-2 text-lg font-black">{formatDuration(result.timeUsedSeconds)}</p><p className="text-xs text-slate-500">tempo utilizado</p></div><div className="rounded-2xl bg-slate-100 p-4 dark:bg-white/[0.04]"><Flag className="mx-auto h-5 w-5 text-amber-500"/><p className="mt-2 text-lg font-black">{result.markedCount}</p><p className="text-xs text-slate-500">marcadas</p></div></div></div></Card>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{['1','2','3','4'].map((theme)=>{const stats=result.themePerformance[theme]??{correct:0,total:0,percent:0};return <Card key={theme}><div className="flex items-center justify-between"><p className="font-bold">{themeLabels[theme]}</p><span className="text-lg font-black">{stats.percent}%</span></div><Progress value={stats.percent}/><p className="mt-2 text-xs text-slate-500">{stats.correct}/{stats.total} acertos</p></Card>})}</div>

      <div className="grid gap-6 lg:grid-cols-2"><Card><h2 className="font-bold">Desempenho por dificuldade</h2><div className="mt-4 space-y-4">{(['easy','medium','hard'] as const).map((difficulty)=>{const stats=result.difficultyPerformance[difficulty];return <div key={difficulty}><div className="mb-2 flex items-center justify-between text-sm"><span>{difficultyLabels[difficulty]}</span><strong>{stats.percent}% · {stats.correct}/{stats.total}</strong></div><Progress value={stats.percent}/></div>})}</div></Card><Card><h2 className="font-bold">Resumo da prova</h2><div className="mt-4 grid grid-cols-3 gap-3 text-center"><div className="rounded-xl bg-emerald-400/10 p-3"><p className="text-xl font-black text-emerald-700 dark:text-emerald-300">{result.correct}</p><p className="text-xs text-slate-500">certas</p></div><div className="rounded-xl bg-rose-400/10 p-3"><p className="text-xl font-black text-rose-700 dark:text-rose-300">{wrong.length}</p><p className="text-xs text-slate-500">erradas</p></div><div className="rounded-xl bg-slate-100 p-3 dark:bg-white/[0.04]"><p className="text-xl font-black">{result.unansweredCount}</p><p className="text-xs text-slate-500">em branco</p></div></div>{marked.length?<p className="mt-4 text-xs leading-5 text-slate-500">Marcadas para revisão: {marked.map((id)=>{const i=simulation.payload.questionIds.indexOf(id);return i>=0?i+1:null}).filter(Boolean).join(', ')}.</p>:<p className="mt-4 text-xs text-slate-500">Nenhuma questão foi marcada para revisão.</p>}</Card></div>

      <Card><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-bold">Desempenho por PD</h2><p className="mt-1 text-xs text-slate-500">Detalhamento por ponto do Programa Detalhado presente neste simulado.</p></div><Badge>{Object.keys(result.pdPerformance).length} PDs</Badge></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[560px] text-left text-sm"><thead className="text-xs uppercase tracking-[0.12em] text-slate-400"><tr><th className="pb-3">PD</th><th className="pb-3">Acertos</th><th className="pb-3">Total</th><th className="pb-3">%</th><th className="pb-3">Revisão</th></tr></thead><tbody>{Object.entries(result.pdPerformance).sort(([a],[b])=>a.localeCompare(b,undefined,{numeric:true})).map(([pd,stats])=><tr key={pd} className="border-t border-slate-100 dark:border-white/5"><td className="py-3 font-mono font-bold">{pd}</td><td>{stats.correct}</td><td>{stats.total}</td><td className={stats.percent<70?'font-bold text-rose-600':'font-bold text-emerald-600'}>{stats.percent}%</td><td><Link className="text-xs font-semibold text-emerald-700 hover:underline dark:text-emerald-300" to={cpaLessonMap.has(pd)?`/conteudos/${pd}`:'/trilha'}>{cpaLessonMap.has(pd)?'Abrir aula':'Ver trilha'}</Link></td></tr>)}</tbody></table></div></Card>

      <Card><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">Questões erradas</h2><p className="mt-1 text-xs text-slate-500">Respostas incorretas já foram adicionadas ao Caderno de Erros. Questões em branco permanecem separadas.</p></div><Link to="/erros"><Button variant="secondary">Abrir Caderno de Erros</Button></Link></div>{wrong.length===0?<div className="py-8 text-center"><CheckCircle2 className="mx-auto h-8 w-8 text-emerald-400"/><p className="mt-2 font-bold">Nenhuma resposta incorreta</p></div>:<div className="mt-5 space-y-4">{wrong.map((row)=>{const question=getSimulationQuestions(simulation).find((question)=>question.id===row.questionId);if(!question)return null;return <div key={row.questionId} className="rounded-2xl border border-slate-200 p-4 dark:border-white/10"><div className="flex flex-wrap gap-2"><Badge>{row.questionId}</Badge><Badge>PD {row.pdCode}</Badge></div><p className="mt-3 text-sm font-semibold leading-6">{question.prompt}</p><div className="mt-3 grid gap-2 md:grid-cols-2"><div className="rounded-xl bg-rose-400/10 p-3 text-xs"><strong>Sua resposta:</strong> {question.options[row.selectedAnswer!]}</div><div className="rounded-xl bg-emerald-400/10 p-3 text-xs"><strong>Correta:</strong> {question.options[row.correctAnswer]}</div></div><p className="mt-3 text-xs leading-5 text-slate-500">{question.explanation}</p><div className="mt-3 flex flex-wrap gap-2"><Link to={`/questoes?question=${encodeURIComponent(row.questionId)}`}><Button variant="secondary"><RotateCcw className="h-4 w-4"/>Refazer</Button></Link><Link to={cpaLessonMap.has(row.pdCode)?`/conteudos/${row.pdCode}`:'/trilha'}><Button variant="secondary">Revisar conteúdo</Button></Link></div></div>})}</div>}</Card>

      <div className="flex flex-wrap gap-2"><Link to="/simulados"><Button>Novo simulado</Button></Link><Link to="/simulados/historico"><Button variant="secondary">Ver histórico</Button></Link></div>
    </main>
  </div>
}
