import type { ReadingSection } from './readings'

export const deepReadingSections: Record<string, ReadingSection[]> = {
  'sistema-financeiro': [
    { id:'deep-fluxo-recursos', title:'1. Como o dinheiro circula pelo sistema', paragraphs:[
      'Uma forma eficiente de estudar o Sistema Financeiro Nacional é começar pelo fluxo econômico, e não pelas siglas. Existem agentes com recursos excedentes e agentes que precisam de recursos. O sistema cria mecanismos para que esses recursos sejam captados, transformados, transferidos, registrados e liquidados. Em uma operação de crédito bancário, por exemplo, o banco se coloca entre quem fornece recursos e quem toma crédito. Em uma emissão de debêntures, a empresa busca recursos diretamente junto aos investidores, embora continue dependendo de intermediários, infraestrutura e regras para que a operação funcione.',
      'Esse raciocínio ajuda a separar três perguntas que aparecem constantemente em questões contextualizadas: quem está entregando o recurso, quem assume a obrigação de devolvê-lo e qual instituição ou infraestrutura torna a operação possível? O canal utilizado pelo cliente não responde sozinho a essas perguntas. Comprar um produto no aplicativo de um banco não significa que o banco seja o emissor do ativo, assim como utilizar uma corretora não transforma a corretora em devedora do título comprado. A natureza econômica do instrumento vem antes do canal de distribuição.'
    ]},
    { id:'deep-estrutura-sfn', title:'2. Normatização, supervisão, autorregulação e operação', paragraphs:[
      'No estudo do SFN, pense em camadas. A camada normativa estabelece diretrizes e regras dentro da competência de cada órgão. A supervisão verifica o cumprimento dessas regras e acompanha a atuação das instituições. A autorregulação acrescenta padrões e compromissos para participantes que aderem aos códigos aplicáveis. Por fim, os participantes operacionais executam atividades como captar, emprestar, distribuir, custodiar, negociar, segurar ou administrar recursos. Uma mesma operação pode envolver várias dessas camadas ao mesmo tempo.',
      'O erro clássico é transformar a estrutura em uma lista de siglas sem função. Para evitar isso, associe cada entidade a uma pergunta: “quem estabelece a diretriz?”, “quem fiscaliza?”, “quem executa a atividade?” e “quem oferece a infraestrutura?”. O CMN, BCB, CVM, CNSP, Susep, CNPC e Previc aparecem em contextos diferentes. A ANBIMA também exerce autorregulação, mas não deve ser apresentada como equivalente a um regulador estatal. Em uma questão, a competência descrita no enunciado é mais importante do que a semelhança entre nomes.'
    ]},
    { id:'deep-mercados', title:'3. Os mercados dentro do sistema', paragraphs:[
      'O SFN pode ser observado por diferentes mercados. O mercado monetário está ligado à gestão da liquidez e às condições monetárias; o crédito conecta tomadores e provedores de financiamento; o câmbio envolve operações com moedas estrangeiras; o mercado de capitais permite captação e investimento por meio de valores mobiliários; seguros e previdência lidam com transferência de riscos e formação de recursos para objetivos de longo prazo. Esses mercados se relacionam: uma mudança nas condições monetárias pode alterar crédito, câmbio, preços de ativos e decisões de investimento.',
      'Para a prova, não é suficiente decorar o nome do mercado. O melhor método é identificar o problema econômico que ele resolve. Se a situação descreve uma empresa captando recursos de investidores por emissão de valores mobiliários, pense em mercado de capitais. Se descreve financiamento bancário, pense em crédito. Se envolve compra e venda de moeda estrangeira, pense em câmbio. Se envolve proteção contra eventos incertos mediante prêmio, pense em seguros. Esse mapa torna questões longas muito mais simples.'
    ]},
    { id:'deep-protecao', title:'4. Garantias, riscos e proteção ao investidor', paragraphs:[
      'Proteção ao investidor não significa ausência de risco. Uma garantia pode reduzir determinado risco de crédito dentro das condições previstas, mas não elimina risco de mercado, liquidez, fraude, inflação ou perda de oportunidade. Por isso, sempre identifique primeiro qual obrigação existe e qual entidade está obrigada a cumprir essa obrigação. Depois, verifique se há mecanismo de proteção aplicável, quais produtos estão abrangidos e quais limites e condições estão vigentes.',
      'O mesmo cuidado vale para fundos, ações e títulos públicos. O investidor precisa entender que o patrimônio de um fundo possui estrutura própria e que comprar uma cota não equivale a fazer um depósito no banco distribuidor. Uma ação sofre influência do desempenho e das expectativas sobre a companhia. Um título de dívida envolve risco de crédito do emissor e risco de mercado. Uma questão pode colocar produtos diferentes no mesmo aplicativo justamente para testar se você identifica a natureza de cada um.'
    ]},
    { id:'deep-caso-sfn', title:'5. Como resolver um caso de SFN na prova', paragraphs:[
      'Imagine uma cliente que mantém dinheiro em um banco, compra um título privado por uma plataforma de investimentos e contrata um seguro. O enunciado pergunta quem supervisiona cada atividade. Em vez de procurar uma sigla de memória, classifique primeiro a atividade: depósito e atividade bancária, distribuição ou negociação de valores mobiliários, e seguro. Em seguida, associe cada atividade ao supervisor competente. Se a questão perguntar pela garantia, mude a pergunta: agora você precisa identificar o instrumento e não apenas a instituição pela qual a compra foi realizada.',
      'Esse é o estilo de raciocínio que vale a pena levar para toda a matéria: classifique a situação antes de responder. A resposta correta geralmente surge de uma sequência lógica — atividade → instrumento → participante → competência → risco/proteção. Se uma alternativa afirma que “todo investimento comprado em banco tem FGC” ou que “autorregulação substitui o regulador”, pare: a frase generaliza uma regra que depende do instrumento ou mistura funções institucionais.'
    ]}
  ],
  'economia': [
    { id:'deep-inflacao', title:'1. Inflação: nível de preços, índices e poder de compra', paragraphs:[
      'Inflação não é simplesmente “um produto ficou mais caro”. É uma variação persistente do nível geral de preços, medida por índices construídos a partir de cestas e metodologias específicas. Por isso, a inflação divulgada por um índice pode ser diferente da inflação sentida por uma família. O peso de cada item na cesta importa. Para o investidor, a consequência central é a perda do poder de compra quando o retorno nominal de um investimento não acompanha a variação de preços.',
      'Uma questão pode apresentar uma aplicação que rende 10% ao ano e uma inflação de 6% e perguntar sobre o retorno real. A intuição correta é que o retorno real não deve ser obtido apenas subtraindo taxas em qualquer situação; a relação exata é multiplicativa. O investidor também precisa distinguir inflação corrente de expectativa de inflação. Expectativas influenciam contratos, preços, salários e decisões de investimento antes mesmo de o índice observado confirmar uma mudança.'
    ]},
    { id:'deep-juros', title:'2. Juros e política monetária', paragraphs:[
      'A taxa de juros funciona como preço do dinheiro ao longo do tempo. Quando as condições monetárias ficam mais restritivas, o custo de crédito tende a aumentar e a demanda agregada pode desacelerar. Quando ficam mais estimulativas, o financiamento tende a ficar menos restritivo e a atividade pode receber impulso. O efeito não é instantâneo nem mecânico: expectativas, câmbio, crédito, situação fiscal e condições externas também interferem.',
      'Na prova, diferencie a meta definida pela autoridade monetária das taxas efetivamente observadas no mercado. Também separe instrumento de objetivo. A autoridade pode usar instrumentos para influenciar liquidez e juros, enquanto inflação, atividade e estabilidade financeira são condições que entram na avaliação da política. Uma alternativa que trata qualquer aumento de juros como garantia de queda imediata da inflação costuma ignorar defasagens e expectativas.'
    ]},
    { id:'deep-fiscal', title:'3. Política fiscal e interação com a economia', paragraphs:[
      'Política fiscal envolve principalmente receitas e despesas do governo. A expansão de gastos ou redução de tributos pode aumentar a demanda em determinadas condições, enquanto medidas de contenção podem reduzir o impulso fiscal. O efeito sobre juros e inflação depende do contexto econômico, da forma de financiamento, das expectativas e da reação da política monetária. Por isso, não transforme “gasto maior” em uma regra universal de resultado.',
      'Para estudar, separe três conceitos: resultado fiscal, dívida e política fiscal. Resultado é o fluxo de receitas e despesas em determinado período; dívida é um estoque acumulado de obrigações; política fiscal é o conjunto de decisões sobre arrecadação e gasto. Questões podem misturar os termos para testar se o candidato percebe que um aumento temporário de despesa e uma trajetória persistente de dívida são fenômenos relacionados, mas não idênticos.'
    ]},
    { id:'deep-cambio', title:'4. Câmbio e transmissão para investimentos', paragraphs:[
      'A taxa de câmbio expressa o preço de uma moeda em termos de outra. Uma depreciação do real, por exemplo, pode encarecer produtos importados em reais e aumentar a receita em moeda doméstica de exportadores quando as demais condições permanecem constantes. Mas o efeito sobre uma empresa ou investimento depende de sua exposição líquida: quem importa insumos e vende no mercado doméstico pode sentir uma pressão diferente de quem exporta e recebe em dólares.',
      'Também é importante distinguir câmbio nominal de medidas de câmbio real. O câmbio real incorpora diferenças de preços e permite pensar em competitividade relativa. Para o investidor, a análise cambial precisa considerar inflação, juros domésticos e externos, fluxo comercial, fluxo financeiro e expectativas. Na prova, procure o canal de transmissão descrito no enunciado em vez de decorar que “dólar alto é bom” ou “dólar alto é ruim”.'
    ]},
    { id:'deep-indicadores', title:'5. Como ler indicadores econômicos sem decorar frases', paragraphs:[
      'Indicadores são sinais sobre diferentes partes da economia. PIB ajuda a acompanhar produção; inflação acompanha preços; desemprego informa sobre o mercado de trabalho; produção industrial ajuda a observar determinado segmento da atividade; indicadores fiscais mostram a posição das contas públicas. Nenhum deles conta sozinho a história completa. A pergunta correta é: qual variável o indicador mede, com qual metodologia e em qual horizonte?',
      'O método de estudo inspirado nas aulas preparatórias é transformar cada indicador em uma pequena cadeia causal. Se a inflação surpreende para cima, quais expectativas podem mudar? Se o desemprego aumenta, qual pode ser o efeito sobre renda e consumo? Se o câmbio se deprecia, quais empresas possuem exposição positiva ou negativa? A prova pode apresentar números em uma situação de cliente e pedir interpretação, e não apenas a definição do indicador.'
    ]}
  ],
  'matematica-financeira': [
    { id:'deep-taxas', title:'1. Taxa, período e equivalência', paragraphs:[
      'Antes de qualquer fórmula, alinhe a unidade de tempo. Uma taxa de 2% ao mês não pode ser comparada diretamente com uma taxa anual sem considerar a forma de capitalização. Em juros compostos, a taxa equivalente anual é obtida pela capitalização das taxas periódicas. Em juros simples, a lógica é linear e a transformação é diferente. Essa distinção é uma das principais fontes de erro em questões de matemática financeira.',
      'Taxa nominal, efetiva e real também respondem a perguntas diferentes. Uma taxa nominal pode representar uma convenção de divulgação; a efetiva representa a capitalização efetivamente considerada; a real procura retirar o efeito da inflação. A relação de Fisher é multiplicativa. Em uma questão, sublinhe a periodicidade, identifique se a taxa é nominal ou efetiva e só então escolha a fórmula.'
    ]},
    { id:'deep-compostos', title:'2. Juros simples x compostos: entenda o mecanismo', paragraphs:[
      'Nos juros simples, os juros de cada período são calculados sobre o capital inicial. Se R$ 1.000 forem aplicados a 2% ao mês por três meses, o juro será R$ 60 e o montante R$ 1.060. Nos compostos, os juros de cada período passam a fazer parte da base de cálculo seguinte. Com os mesmos valores, o montante será R$ 1.061,21. A diferença cresce conforme o prazo aumenta.',
      'Mais importante do que memorizar as fórmulas é reconhecer o verbo do enunciado. “Incide sempre sobre o principal” aponta para simples. “Reinveste os juros”, “capitaliza” ou “juros sobre juros” aponta para compostos. Em questões de crédito e investimento, confira ainda se a taxa e o período estão na mesma unidade. Uma fórmula correta aplicada com meses e anos misturados produz um resultado incorreto.'
    ]},
    { id:'deep-vp-vf', title:'3. Valor presente, valor futuro e fluxos', paragraphs:[
      'Valor presente é uma forma de trazer um fluxo futuro para uma data de referência usando uma taxa de desconto. Valor futuro faz o movimento inverso: capitaliza o valor atual. Quando existem vários fluxos, cada pagamento precisa ser trazido para a mesma data antes da comparação. Essa lógica está por trás de VPL, precificação e diversas decisões financeiras.',
      'Imagine duas alternativas: receber R$ 10 mil hoje ou R$ 12 mil daqui a dois anos. Não é possível decidir apenas comparando os valores nominais. É necessário considerar a taxa que representa o custo de oportunidade ou a taxa exigida. Em uma questão, desenhar uma linha do tempo costuma ser mais útil do que tentar lembrar uma fórmula de cabeça.'
    ]},
    { id:'deep-amortizacao', title:'4. SAC, Price e leitura das parcelas', paragraphs:[
      'No SAC, a amortização do principal é constante. Como os juros incidem sobre um saldo devedor que diminui, os juros caem e as prestações tendem a ser decrescentes. No sistema Price, a prestação é constante sob as condições contratuais usuais, mas a composição muda: no início há maior participação relativa de juros e, com o tempo, a amortização ganha espaço.',
      'Uma questão pode perguntar qual sistema gera maior parcela inicial ou como o saldo evolui. Não decore apenas “SAC cai, Price é constante”. Entenda por quê. Se o saldo devedor diminui mais rapidamente, a despesa financeira calculada sobre esse saldo também tende a cair mais rapidamente. Essa interpretação permite resolver perguntas conceituais mesmo quando nenhum número é fornecido.'
    ]},
    { id:'deep-desconto', title:'5. Desconto comercial, payback e interpretação', paragraphs:[
      'Desconto comercial simples aparece quando um valor nominal futuro é antecipado e o desconto é calculado sobre o valor nominal, de acordo com a convenção apresentada. O cuidado principal é não confundir desconto com juros de um empréstimo tradicional. Leia o enunciado para identificar qual é a base de cálculo e qual valor o cliente efetivamente recebe.',
      'Payback mede o tempo necessário para recuperar o desembolso inicial por meio dos fluxos de caixa acumulados. Ele é intuitivo, mas possui limitações: o payback simples não considera adequadamente o valor do dinheiro no tempo e ignora fluxos posteriores ao momento de recuperação. Uma alternativa pode apresentar um projeto com payback menor e ainda assim não ser superior sob todos os critérios de decisão. A prova testa a interpretação do indicador, não apenas a conta.'
    ]}
  ],
  'infraestrutura': [
    { id:'deep-spb', title:'1. SPB e a arquitetura dos pagamentos', paragraphs:[
      'O Sistema de Pagamentos Brasileiro existe para que transferências de recursos entre participantes ocorram de forma organizada, segura e final. Pense nele como uma infraestrutura: o usuário enxerga o pagamento, mas por trás existem mensagens, liquidação, participantes, controles e mecanismos de gestão de risco. O SPI, por exemplo, está associado à infraestrutura de pagamentos instantâneos, enquanto outras operações seguem estruturas diferentes.',
      'Na prova, diferencie pagamento, liquidação e custódia. Pagamento é a movimentação de recursos; liquidação é o processo pelo qual obrigações são efetivamente encerradas segundo a infraestrutura; custódia envolve guarda e controle de ativos. Uma questão pode colocar todos esses termos na mesma história justamente para testar se você sabe qual função pertence a cada etapa.'
    ]},
    { id:'deep-selic-b3', title:'2. Selic e B3: funções diferentes', paragraphs:[
      'O Selic é uma infraestrutura central para registro e liquidação de títulos públicos federais. A B3 opera diversas infraestruturas de negociação e pós-negociação para diferentes mercados e ativos. A forma mais segura de memorizar é associar o Selic ao universo de títulos públicos federais e a B3 ao conjunto mais amplo de mercados e infraestruturas do mercado de capitais brasileiro.',
      'Não confunda infraestrutura com órgão supervisor. Uma infraestrutura pode executar funções técnicas de registro, negociação, compensação ou liquidação, enquanto o supervisor exerce autoridade regulatória e fiscalizatória. Em um caso, pergunte primeiro “o que precisa acontecer com a operação?” e só depois “quem oferece essa infraestrutura?”'
    ]},
    { id:'deep-ccp', title:'3. Contraparte central, depositário e registradora', paragraphs:[
      'A contraparte central atua para administrar o risco de contraparte em operações elegíveis, interpondo-se na relação entre compradores e vendedores conforme as regras do mercado. O depositário central mantém registros centralizados relacionados à titularidade e movimentação de determinados ativos. A entidade registradora registra informações sobre operações ou ativos conforme o escopo regulatório aplicável. São funções diferentes, mesmo que possam aparecer próximas na mesma operação.',
      'Um bom exercício é imaginar uma ação negociada em mercado organizado. A questão pode perguntar quem registra, quem mantém a estrutura de titularidade, quem administra o risco de contraparte ou quem liquida. Em vez de associar tudo a uma única entidade, decomponha o ciclo da operação em negociação, registro, compensação, gerenciamento de risco e liquidação.'
    ]},
    { id:'deep-estabilidade', title:'4. Estabilidade financeira e risco sistêmico', paragraphs:[
      'Risco sistêmico é o risco de que problemas em uma instituição, mercado ou infraestrutura se propaguem e comprometam o funcionamento do sistema financeiro. Ele é diferente do risco individual de uma operação. Interconexões, alavancagem, concentração, liquidez e confiança podem transformar um problema localizado em um evento mais amplo.',
      'Instrumentos de estabilidade, como mecanismos de liquidez e exigências prudenciais, existem para reduzir a probabilidade e o impacto de choques. O depósito compulsório, linhas de liquidez e estruturas de monitoramento têm funções específicas e não devem ser tratados como equivalentes. Na prova, procure identificar qual problema a ferramenta pretende enfrentar: liquidez, solvência, propagação de risco ou comportamento prudencial.'
    ]},
    { id:'deep-distribuicao', title:'5. Distribuição e infraestrutura vistos pelo cliente', paragraphs:[
      'Para o cliente, a infraestrutura costuma ser invisível. Ele vê uma ordem, um pagamento ou uma transferência, enquanto as instituições e sistemas cuidam das etapas necessárias para registrar e liquidar a operação. O profissional de distribuição não precisa operar cada infraestrutura, mas precisa saber explicar de forma simples o que acontece e quais riscos permanecem.',
      'Em uma situação de atendimento, a melhor explicação evita jargões desnecessários. Se o cliente pergunta por que um ativo não aparece imediatamente em determinada conta, explique o fluxo operacional e os prazos aplicáveis. Se pergunta sobre segurança, diferencie risco operacional, risco de contraparte e proteção regulatória. A prova pode avaliar exatamente essa capacidade de conectar a infraestrutura à experiência do cliente.'
    ]}
  ],
  'renda-fixa': [
    { id:'deep-conceito-rf', title:'1. Renda fixa não significa retorno fixo', paragraphs:[
      'Em renda fixa, o investidor conhece as regras de remuneração ou os fluxos previstos no momento da contratação, mas isso não significa que o preço do título permaneça constante. Um título pode ser prefixado, pós-fixado ou híbrido e, ainda assim, ter seu preço de mercado alterado antes do vencimento. A diferença entre “regra de remuneração” e “preço de negociação” é fundamental.',
      'Se o investidor levar um título até o vencimento e as condições contratuais forem cumpridas, a lógica de retorno contratada é diferente daquela de quem vende o título antes. No mercado secundário, o preço depende das taxas exigidas pelos compradores naquele momento. Essa distinção explica por que um título pode apresentar rentabilidade negativa em determinado dia mesmo quando o emissor continua pagando corretamente.'
    ]},
    { id:'deep-mtm', title:'2. Marcação a mercado e curva de juros', paragraphs:[
      'Marcação a mercado significa atualizar o valor de um ativo pelo preço que seria obtido nas condições de mercado da data de referência. Quando a taxa exigida pelo mercado sobe, o preço de um título prefixado já emitido tende a cair, porque seus fluxos fixos se tornam menos atraentes em comparação com novas oportunidades. Quando a taxa cai, o movimento tende a ser inverso.',
      'O prazo e a estrutura dos fluxos influenciam a sensibilidade do preço. Quanto maior a exposição a fluxos distantes, maior tende a ser a sensibilidade a mudanças de taxa. Para a CPA, você não precisa transformar toda questão em um cálculo de duration, mas deve saber raciocinar: taxa sobe → preço do prefixado existente tende a cair; taxa cai → preço tende a subir, mantendo as demais condições constantes.'
    ]},
    { id:'deep-credito', title:'3. Risco de crédito e títulos privados', paragraphs:[
      'Quando você compra um título privado, está assumindo uma relação de crédito com o emissor. A análise deve considerar capacidade de pagamento, estrutura de garantias, prazo, setor, concentração e condições da emissão. Uma taxa prometida maior pode refletir maior risco de crédito ou menor liquidez; não é correto interpretar rendimento maior como “almoço grátis”.',
      'O profissional de distribuição precisa explicar que rating é uma informação, não uma garantia. A ausência de default histórico também não elimina risco futuro. Em títulos bancários, deve-se ainda separar o risco do emissor da eventual proteção do FGC, observando se o produto e a instituição se enquadram nas regras vigentes. Em debêntures e outros títulos de crédito privado, a estrutura de garantia e o risco do emissor são centrais.'
    ]},
    { id:'deep-publicos', title:'4. Títulos públicos e indexadores', paragraphs:[
      'Títulos públicos possuem diferentes formas de remuneração. Um título atrelado a uma taxa de referência acompanha determinado indexador; um prefixado estabelece uma taxa contratada; um híbrido combina componente de inflação com taxa real, conforme o instrumento. A pergunta correta não é “qual título é melhor?”, mas “qual fluxo e qual risco combinam com o objetivo e o horizonte do investidor?”.',
      'Para estudar, compare sempre quatro dimensões: indexador, prazo, volatilidade de preço antes do vencimento e objetivo do investidor. Uma reserva de curto prazo exige atenção a liquidez e oscilação. Um objetivo de longo prazo pode aceitar maior sensibilidade de preço se o investidor compreender que pretende carregar o título por determinado horizonte.'
    ]},
    { id:'deep-caso-rf', title:'5. Como analisar uma recomendação de renda fixa', paragraphs:[
      'Imagine um cliente dizendo: “Quero o investimento mais seguro e que pague a maior taxa”. A resposta profissional começa desmontando a frase. Segurança depende de qual risco está sendo considerado; taxa maior pode vir acompanhada de maior risco de crédito, prazo ou liquidez. O objetivo do cliente também importa. Um dinheiro que será usado em três meses não deve ser analisado da mesma forma que uma reserva para aposentadoria.',
      'Na prova, procure as palavras que revelam o risco relevante: “vender antes do vencimento” aponta para risco de mercado e liquidez; “emissor com dificuldade financeira” aponta para crédito; “taxa subiu depois da compra” aponta para marcação a mercado; “garantia” exige identificar o mecanismo específico. Essa leitura por gatilhos torna as questões de renda fixa muito mais rápidas.'
    ]}
  ],,
'renda-variavel': [
    { id:'deep-acoes', title:'1. Ação é participação, não promessa de rendimento', paragraphs:[
      'Uma ação representa uma participação no capital de uma companhia. O retorno do acionista pode vir da valorização do preço e de proventos distribuídos, mas nenhum desses componentes é garantido. O preço de mercado incorpora expectativas sobre lucros, crescimento, juros, risco e condições do setor. Por isso, uma ação não deve ser tratada como um título de dívida com juros contratados.',
      'Em uma questão, identifique primeiro a posição do investidor. Acionista participa economicamente do negócio e está exposto ao desempenho da companhia. Credor tem direito contratual de receber fluxos conforme o instrumento de dívida. Essa diferença ajuda a responder perguntas sobre risco, prioridade de recebimento, governança e retorno.'
    ]},
    { id:'deep-oferta', title:'2. Mercado primário, secundário e liquidez', paragraphs:[
      'No mercado primário, os recursos de uma emissão chegam ao emissor conforme a estrutura da oferta. No secundário, investidores negociam ativos que já foram emitidos. A existência de mercado secundário favorece liquidez e formação de preços, mas não significa que todo ativo será vendido imediatamente pelo preço desejado.',
      'Quando a questão apresenta IPO, emissão ou distribuição, pense em captação. Quando apresenta compra e venda entre investidores depois da emissão, pense em mercado secundário. O distribuidor pode participar da oferta sem ser o emissor. Essa separação é especialmente útil em situações de atendimento.'
    ]},
    { id:'deep-derivativos', title:'3. Derivativos: para que servem e por que existem', paragraphs:[
      'Derivativos são contratos cujo valor depende de outro ativo, taxa, índice ou variável de referência. Eles podem ser usados para proteção, transferência de risco, exposição direcional e estratégias de arbitragem, dependendo do contrato. O ponto central é que derivativo não é sinônimo de aposta; seu uso econômico pode reduzir riscos reais de uma empresa ou investidor.',
      'Em uma proteção cambial, por exemplo, uma empresa que receberá dólares no futuro pode usar um contrato para reduzir a incerteza do valor em reais. A proteção tem custo e pode limitar ganhos caso o mercado caminhe na direção oposta. Na prova, pergunte qual risco o agente possui antes de identificar o instrumento de hedge.'
    ]},
    { id:'deep-coe', title:'4. COE e estruturas de retorno', paragraphs:[
      'O COE combina características de diferentes exposições dentro de uma estrutura única, com regras de remuneração e cenários previamente definidos. O investidor não deve olhar apenas para a promessa de retorno: precisa entender o ativo de referência, cenários de ganho e perda, prazo, liquidez, custos e riscos da estrutura.',
      'Uma questão pode apresentar uma estrutura que paga determinado retorno se um índice atingir um nível, mas limita a participação em uma alta adicional. A leitura correta é montar os cenários. Pergunte o que acontece se o ativo subir muito, subir pouco, ficar estável e cair. Esse método é mais seguro do que tentar memorizar nomes de estruturas.'
    ]},
    { id:'deep-caso-rv', title:'5. Como pensar uma questão de renda variável', paragraphs:[
      'Se um cliente deseja proteger uma receita futura em moeda estrangeira, uma ação não resolve o problema apenas porque é negociada em bolsa. O instrumento precisa ter relação com o risco. Se outro cliente quer participar do crescimento de uma empresa e aceita oscilações de mercado, a lógica é diferente. A adequação depende do objetivo e do risco que está sendo assumido.',
      'O padrão de prova é contextual: a questão fornece uma situação, apresenta características de um instrumento e pergunta qual alternativa descreve melhor a solução. Identifique objetivo, horizonte, risco e fluxo antes de olhar as opções. Depois, elimine alternativas que tratam retorno potencial como garantia ou confundem emissão com negociação.'
    ]}
  ],
  'fundos': [
    { id:'deep-estrutura-fundos', title:'1. O que realmente acontece quando você compra uma cota', paragraphs:[
      'Um fundo reúne recursos de vários investidores e os administra segundo uma política definida em seus documentos. O cotista não escolhe individualmente cada ativo da carteira; ele compra uma participação econômica no patrimônio do fundo. A estrutura separa funções de administração, gestão, custódia, distribuição e outras atividades previstas nas regras aplicáveis.',
      'Essa separação é importante para entender riscos. O banco que distribuiu a cota não é automaticamente o gestor. O gestor toma decisões de investimento dentro da política. O administrador responde por funções administrativas e de funcionamento do fundo. A custódia envolve guarda e controle dos ativos. Em questões, procure a função descrita antes de escolher a instituição.'
    ]},
    { id:'deep-cotas', title:'2. Cota, patrimônio e rentabilidade', paragraphs:[
      'A cota representa uma fração do patrimônio do fundo. Quando os ativos da carteira variam de preço, o patrimônio e, consequentemente, o valor da cota podem mudar. Entradas e saídas de recursos também precisam ser processadas segundo as regras do fundo. A rentabilidade observada pelo cotista depende da evolução da carteira, das despesas e das condições de mercado.',
      'Não confunda rendimento da carteira com retorno líquido do cotista. Taxas e despesas reduzem o resultado disponível. Também não confunda rentabilidade passada com promessa futura. Um fundo que teve desempenho elevado em determinado período pode estar exposto a fatores que não se repetirão.'
    ]},
    { id:'deep-taxas', title:'3. Taxas e custos: quem paga o quê', paragraphs:[
      'Taxa de administração remunera a estrutura de administração e gestão conforme as regras do fundo. Taxa de performance, quando existente, depende do desempenho segundo critérios definidos. Outras despesas podem existir. O investidor deve olhar o regulamento, a lâmina e os documentos oficiais para entender como os custos impactam o patrimônio.',
      'A prova pode usar uma taxa como distração. Não basta reconhecer o nome; é preciso saber a finalidade. Taxa de administração não é uma multa por resgate. Taxa de performance não significa que o gestor receberá sempre um percentual do patrimônio. A incidência depende da estrutura e das regras aplicáveis.'
    ]},
    { id:'deep-classes', title:'4. Classes, políticas e riscos', paragraphs:[
      'A classificação de um fundo deve ser analisada junto à política de investimento, composição da carteira, prazo, liquidez e riscos. Duas classes com nomes parecidos podem ter exposições diferentes. O investidor precisa saber em quais ativos o fundo pode investir, quais limites existem e como funciona o resgate.',
      'Quando uma questão apresenta um objetivo de curto prazo e um fundo com ativos de baixa liquidez, a discussão deixa de ser apenas rentabilidade. Liquidez, volatilidade e compatibilidade com o horizonte tornam-se centrais. O mesmo vale para concentração de crédito: uma carteira com poucos emissores pode ter risco diferente de uma carteira mais diversificada.'
    ]},
    { id:'deep-caso-fundos', title:'5. Como estudar fundos para a prova', paragraphs:[
      'Leia cada questão em quatro camadas: estrutura do fundo, política de investimento, risco e custo. Se o enunciado falar de gestor, procure a função de decisão de investimento. Se falar de cotista, pense na cota e no patrimônio. Se falar de resgate, procure regras de liquidez e prazo de cotização/pagamento. Se falar de rentabilidade, verifique se é bruta ou líquida e qual período foi analisado.',
      'O objetivo não é decorar dezenas de nomes. É conseguir reconstruir a lógica do produto a partir dos documentos e do caso. Esse método também ajuda no atendimento: em vez de dizer que “fundo é seguro” ou “fundo rende X”, explique como a carteira, a estrutura e os riscos determinam o resultado.'
    ]}
  ],
  'fundos-imobiliarios': [
    { id:'deep-fii-estrutura', title:'1. O que é um FII e de onde vem seu resultado', paragraphs:[
      'Fundos imobiliários permitem exposição coletiva a ativos e estratégias ligadas ao setor imobiliário. A carteira pode conter imóveis físicos, recebíveis imobiliários ou estruturas relacionadas, conforme a política do fundo. O cotista participa do resultado econômico da carteira, mas não deve interpretar a cota como propriedade direta de cada imóvel.',
      'A origem da receita é importante. Um fundo de tijolo pode ter receitas de aluguel e valorização dos imóveis. Um fundo de recebíveis pode receber juros e amortizações de créditos imobiliários. A fonte do fluxo determina parte importante do risco. Uma carteira concentrada em poucos imóveis ou devedores possui perfil diferente de uma carteira diversificada.'
    ]},
    { id:'deep-fii-riscos', title:'2. Vacância, crédito, juros e liquidez', paragraphs:[
      'FIIs podem sofrer com vacância, inadimplência, mudanças nos preços dos imóveis, alterações nas taxas de juros, concentração e liquidez das cotas. Um imóvel vazio pode reduzir a receita de aluguel; um devedor com problemas pode afetar recebíveis; juros maiores podem alterar a atratividade relativa e o preço de mercado das cotas.',
      'Esses riscos não devem ser tratados isoladamente. Um FII pode ter boa qualidade física dos imóveis e, ainda assim, sofrer volatilidade de mercado. Pode ter distribuição recorrente e enfrentar queda de preço. A questão geralmente testa se o candidato distingue fluxo distribuído de retorno total.'
    ]},
    { id:'deep-fii-rendimento', title:'3. Rendimento não é o mesmo que retorno total', paragraphs:[
      'O cotista pode receber distribuições periódicas, mas o retorno total também depende da variação do preço da cota. Uma cota que distribui renda e perde valor no mercado pode apresentar resultado total diferente daquele sugerido apenas pelo rendimento recebido. Para comparar investimentos, é necessário considerar todos os componentes do retorno e os custos.',
      'Também é importante verificar as condições tributárias vigentes. A tributação pode depender do tipo de rendimento, da situação do investidor e das regras aplicáveis. A prova pode apresentar uma afirmação genérica sobre “FII é isento” para testar se o candidato percebe que benefícios fiscais possuem condições e não devem ser tratados como universais.'
    ]},
    { id:'deep-fii-leitura', title:'4. Como analisar um FII sem cair no yield isolado', paragraphs:[
      'Uma leitura mínima deve observar tipo de fundo, qualidade e localização dos ativos, concentração, vacância quando aplicável, perfil dos contratos, qualidade dos devedores em recebíveis, prazo dos ativos, liquidez e estrutura de custos. O preço da cota também deve ser analisado em relação ao patrimônio e às características da carteira, sem transformar um único múltiplo em resposta automática.',
      'Yield alto pode refletir risco alto, queda recente de preço, distribuição extraordinária ou características específicas da carteira. Portanto, não é correto concluir que “maior yield é melhor”. Em uma questão de adequação, volte ao objetivo e ao perfil do cliente antes de olhar apenas para a renda mensal.'
    ]},
    { id:'deep-caso-fii', title:'5. Caso de prova: renda mensal x segurança', paragraphs:[
      'Imagine um cliente que quer renda mensal, não aceita oscilações e precisa do dinheiro em seis meses. Um FII pode até distribuir rendimentos, mas a cotação pode variar e a liquidez pode não ser suficiente para garantir saída no preço desejado. O problema não é afirmar que FII é bom ou ruim; é verificar se suas características combinam com o objetivo apresentado.',
      'Essa forma de pensar é mais importante do que decorar uma lista de vantagens. A prova pode trocar o nome do produto e manter a mesma lógica: renda variável, liquidez, risco de mercado e horizonte precisam ser avaliados conjuntamente.'
    ]}
  ],
  'previdencia': [
    { id:'deep-previdencia', title:'1. Previdência como produto de acumulação de longo prazo', paragraphs:[
      'Previdência complementar é uma ferramenta de acumulação voltada a objetivos de longo prazo. O investidor realiza contribuições e, segundo o plano escolhido, acumula recursos que poderão ser utilizados conforme regras de resgate, benefício, portabilidade e tributação. O produto deve ser analisado como uma estrutura de planejamento, e não apenas como um investimento isolado.',
      'A principal diferença para um investimento comum está na combinação entre estrutura do plano, regime tributário, horizonte e possibilidade de sucessão ou beneficiários. Por isso, duas pessoas com a mesma renda podem ter decisões diferentes. O que importa é o objetivo, a forma de contribuição, o prazo e as características do plano.'
    ]},
    { id:'deep-pgbl-vgbl', title:'2. PGBL x VGBL: entenda a lógica antes da regra tributária', paragraphs:[
      'PGBL e VGBL são planos com estruturas distintas de tratamento tributário. A diferença mais importante para o estudo é entender sobre qual base o imposto incide no momento do recebimento/resgate segundo o regime escolhido. Não memorize apenas uma frase; associe o produto ao objetivo tributário e à forma como o cliente realiza suas contribuições.',
      'Na prática de atendimento, o profissional deve analisar a situação fiscal e o horizonte do cliente antes de apresentar a alternativa. A indicação não deve ser baseada em “PGBL sempre é melhor” ou “VGBL sempre é melhor”. A adequação depende da situação do investidor e das regras vigentes.'
    ]},
    { id:'deep-regimes', title:'3. Regimes de tributação e horizonte', paragraphs:[
      'Os regimes tributários devem ser estudados em conjunto com o horizonte de permanência. Em um regime em que a alíquota pode diminuir conforme o prazo, o tempo de acumulação torna-se relevante. Em outro, a tributação segue uma lógica diferente e pode fazer mais sentido para determinadas situações. A prova costuma apresentar um perfil de cliente e pedir a interpretação da regra.',
      'Evite decorar somente tabelas. Primeiro pergunte: o cliente pretende resgatar em curto ou longo prazo? Precisa de previsibilidade? Como serão as contribuições? Há intenção de benefício ou resgate? Depois aplique a regra. Quando houver alteração normativa, consulte a fonte oficial, pois tabelas tributárias são sensíveis a mudanças.'
    ]},
    { id:'deep-portabilidade', title:'4. Portabilidade, resgate e benefícios', paragraphs:[
      'Portabilidade não é simplesmente sacar um plano e aplicar o dinheiro novamente. É uma transferência entre planos conforme regras próprias, com efeitos diferentes de um resgate. O cliente precisa entender carência, custos, regime tributário, plano de destino e condições do contrato. Uma decisão aparentemente simples pode alterar o tratamento tributário ou a estrutura de benefícios.',
      'Também é importante distinguir fase de acumulação e fase de recebimento. Na acumulação, o foco está em contribuições, rentabilidade e custos. Na concessão do benefício, entram modalidade de renda, expectativa de duração, beneficiários e regras contratuais. Uma questão pode explorar exatamente essa mudança de perspectiva.'
    ]},
    { id:'deep-caso-prev', title:'5. Como resolver um caso de previdência', paragraphs:[
      'Imagine uma cliente com renda tributável, horizonte de quinze anos e objetivo de formar patrimônio para aposentadoria. Antes de falar em produto, você precisa conhecer a forma de declaração, contribuições, horizonte e necessidade de liquidez. Depois, compare PGBL e VGBL dentro das regras vigentes e avalie o regime tributário adequado ao horizonte.',
      'O ponto central para a prova é que previdência é um problema de planejamento. Se a cliente precisa do dinheiro em poucos meses, a análise muda. Se pretende formar renda para aposentadoria, o horizonte longo ganha importância. Se quer apenas uma aplicação de curto prazo, o produto pode não cumprir o objetivo. A resposta nasce do contexto, não do nome do plano.'
    ]}
  ],

};
