import type { LessonSourceId } from '../lessons/sources'
import { deepReadingSections } from './deep-readings'
import { masteryReadingSections } from './master-readings'
export interface ReadingSection { id: string; title: string; paragraphs: string[] }
export interface ModuleReading {
  objectives: string[]
  sections: ReadingSection[]
  example: { title: string; scenario: string; steps: string[]; conclusion: string }
  comparison: { headers: [string,string,string]; rows: [string,string,string][] }
  traps: string[]
  recall: { question: string; answer: string }[]
  sources: LessonSourceId[]
}
// Textos e exemplos originais. As fontes sustentam os conceitos; não há reprodução de apostilas.\n// V27.2 acrescenta uma camada de aprofundamento autoral inspirada na estrutura didática observada em cursos públicos, sem reproduzir suas apostilas, slides ou roteiros.
export const moduleReadings: Record<string,ModuleReading> = {
'sistema-financeiro': {
 objectives:['Distinguir quem cria regras, quem supervisiona e quem presta serviços.','Reconhecer a função da intermediação e os limites das garantias.'],
 sections:[
  {id:'fluxo',title:'Por que existe um sistema financeiro?',paragraphs:['Uma família que poupa e uma empresa que precisa investir têm necessidades diferentes de prazo, valor e risco. O sistema financeiro aproxima esses agentes. Um banco pode captar recursos e conceder crédito; uma empresa também pode obter recursos emitindo títulos para investidores. A existência de um intermediário não elimina o risco: muda quem assume cada obrigação.','Ao estudar uma operação, desenhe o caminho do dinheiro. Quem entrega recursos? Quem deve pagar de volta? Qual instrumento formaliza a relação? No CDB, o investidor é credor do banco emissor. Na ação, ele participa do capital de uma empresa. Essa diferença explica por que juros contratados, dividendos e garantias não podem ser tratados da mesma maneira.']},
  {id:'papeis',title:'O mapa das instituições',paragraphs:['Os órgãos normativos estabelecem diretrizes gerais. O CMN integra o segmento de moeda, crédito e câmbio; CNSP e CNPC se relacionam, respectivamente, com seguros e previdência complementar fechada. Supervisores fiscalizam instituições e mercados dentro de suas competências. BCB e CVM não são sinônimos: o primeiro tem atribuições centrais sobre o sistema bancário e a política monetária; a segunda, sobre o mercado de valores mobiliários.','Susep supervisiona seguros e previdência aberta; Previc, previdência complementar fechada. Bancos, cooperativas, corretoras, seguradoras e fundos de pensão atuam em atividades específicas. A B3 oferece infraestrutura de negociação e pós-negociação. A ANBIMA exerce autorregulação sobre participantes sujeitos a seus códigos; ela não substitui um regulador estatal.']},
  {id:'protecao',title:'Intermediário, emissor e proteção',paragraphs:['Comprar um produto pelo aplicativo de um banco não significa que o banco seja o emissor nem que todo produto tenha FGC. A proteção depende do instrumento, da instituição associada, do titular e dos limites vigentes. Cotas de fundos, ações e títulos públicos não recebem a garantia ordinária do FGC.','Separe ainda risco de crédito e risco de liquidez. Mesmo em um produto coberto, o acesso ao dinheiro após um evento de garantia pode não ser imediato. O atendimento adequado identifica o emissor, explica a natureza do investimento e consulta as regras da proteção antes de prometer segurança.']},
 ],
 example:{title:'Três aplicações no mesmo aplicativo',scenario:'Marina compra um CDB, uma ação e cotas de um fundo pelo banco onde recebe salário.',steps:['CDB: identificar o banco emissor e as condições da eventual cobertura.','Ação: Marina assume risco do negócio e do preço de mercado.','Fundo: o resultado depende da carteira e das regras da classe de cotas.'],conclusion:'O canal de compra é igual; a natureza jurídica, o risco e as garantias são diferentes.'},
 comparison:{headers:['Papel','Pergunta que responde','Exemplo'],rows:[['Normativo','Quais diretrizes devem ser seguidas?','CMN'],['Supervisor','Quem fiscaliza este segmento?','BCB, CVM, Susep ou Previc'],['Operador','Quem entrega o serviço financeiro?','Banco, corretora ou seguradora']]},
 traps:['FGC não cobre qualquer produto vendido em banco.','Autorregulação não substitui supervisão estatal.','Corretora que distribui um título não é necessariamente sua emissora.'],
 recall:[{question:'Quem supervisiona previdência aberta e fechada?',answer:'Susep na aberta; Previc na fechada.'},{question:'Como diferenciar CDB e ação?',answer:'O CDB representa crédito contra um banco; a ação representa participação societária.'}],sources:['BCB_SFN','CMN','CVM','SUSEP','PREVIC','FGC']
},
'economia': {
 objectives:['Relacionar inflação, juros, atividade e câmbio.','Interpretar efeitos prováveis sem transformar tendências em certezas.'],
 sections:[
  {id:'indicadores',title:'Comece pelo que cada indicador mede',paragraphs:['Inflação é a elevação do nível de preços, não a alta isolada de um produto. Um índice reúne uma cesta ponderada: por isso, a inflação medida pode ser diferente da experiência de uma família. O IPCA acompanha preços ao consumidor dentro de uma metodologia específica. Já o PIB mede a produção de bens e serviços finais em determinado período; não é o saldo de dinheiro do governo.','Se a renda nominal cresce menos que os preços, o poder de compra diminui. Desinflação significa que os preços continuam subindo, porém mais devagar. Deflação é uma variação negativa do índice. Esse vocabulário ajuda a interpretar notícias e a entender por que retorno nominal positivo não garante ganho real.']},
  {id:'politicas',title:'Três políticas, instrumentos diferentes',paragraphs:['Na política monetária, o Banco Central influencia as condições de liquidez e crédito. A meta Selic é definida pelo Copom; operações de mercado aberto e outros instrumentos ajudam a conduzir as condições monetárias. Juros mais altos tendem a encarecer financiamento e a moderar demanda, mas os efeitos têm defasagens e dependem do contexto.','A política fiscal envolve receitas, despesas e financiamento do setor público. Um aumento de gastos não é uma decisão do Copom. A política cambial trata do funcionamento do mercado de câmbio. Em um regime flutuante, a taxa responde à oferta e demanda de moeda estrangeira; intervenções do BC não tornam automaticamente o câmbio fixo.']},
  {id:'conexoes',title:'Leve a notícia até o investimento',paragraphs:['Uma elevação da taxa de desconto reduz o valor presente de um fluxo futuro fixo. Por isso, uma alta dos juros exigidos pelo mercado tende a reduzir o preço de um título prefixado já emitido. O retorno de um investimento pós-fixado pode acompanhar a evolução de seu indexador, respeitada a regra contratual.','A alta do dólar em reais encarece uma importação de valor fixo em dólares, mantidas as demais condições. Exportadores podem ter receitas favorecidas, mas insumos, dívidas e proteções cambiais também importam. Na prova, procure a variável alterada e mantenha as demais constantes antes de escolher a conclusão.']},
 ],example:{title:'A renda aumentou, mas a compra diminuiu',scenario:'Em um exemplo hipotético, o salário de uma pessoa sobe 4%, enquanto sua cesta de consumo sobe 6%.',steps:['Compare fatores: 1,04 ÷ 1,06 − 1.','O resultado é aproximadamente −1,89%.','A renda nominal aumentou, mas a renda real caiu.'],conclusion:'Subtrair taxas serve como aproximação; a relação entre fatores fornece a variação real exata.'},
 comparison:{headers:['Conceito','O que observa','Não confundir com'],rows:[['Inflação','Variação de preços','Nível de produção'],['Política fiscal','Receitas e despesas públicas','Decisão da meta Selic'],['Depreciação do real','Mais reais por unidade estrangeira','Queda automática das exportações']]},
 traps:['Desinflação não significa queda dos preços.','Meta Selic, Selic efetiva e taxa DI não são expressões idênticas.','Relações econômicas são condicionais: evite “sempre” e “necessariamente”.'],recall:[{question:'Quem define a meta Selic?',answer:'O Copom, no Banco Central.'},{question:'Por que juros afetam títulos já emitidos?',answer:'Mudam a taxa usada para trazer seus fluxos a valor presente.'}],sources:['BCB_POLITICA','BCB_SELIC','BCB_CAMBIO','IBGE']
},
'matematica-financeira': {
 objectives:['Converter taxas e trazer fluxos a uma mesma data.','Distinguir juros, amortização, VPL e TIR.'],
 sections:[
  {id:'capitalizacao',title:'Taxa, tempo e base de cálculo',paragraphs:['Juros simples incidem sobre o capital inicial: M = C × (1 + i × n). Nos compostos, cada período incorpora os juros à base seguinte: M = C × (1 + i)^n. Em ambos, taxa e prazo precisam estar na mesma unidade. Digitar 2 em vez de 0,02 muda completamente uma conta de 2%.','Taxas proporcionais dividem ou multiplicam uma taxa pelo número de períodos. Taxas equivalentes produzem o mesmo montante no regime de capitalização escolhido. Nos compostos, 1% ao mês equivale a (1,01)^12 − 1 ao ano, cerca de 12,68%; não a 12%. Antes de calcular, identifique se a questão fala em taxa nominal, efetiva ou real.']},
  {id:'fluxos',title:'Comparar pagamentos em datas diferentes',paragraphs:['Um real hoje e um real daqui a um ano não são diretamente comparáveis. Para antecipar um fluxo, use VP = VF ÷ (1 + i)^n. Para levar a valor futuro, multiplique pelo fator. A taxa representa a remuneração exigida ou o custo de oportunidade adotado no exercício, não uma certeza sobre o que acontecerá.','O valor presente líquido é a soma dos fluxos descontados, incluindo o investimento inicial negativo. VPL positivo indica criação de valor em relação à taxa escolhida. A TIR é a taxa que zera o VPL; em fluxos não convencionais pode haver múltiplas TIRs ou dificuldades de interpretação. Não basta procurar a maior taxa sem considerar escala e datas.']},
  {id:'dividas',title:'Entender a parcela de uma dívida',paragraphs:['A prestação reúne juros e amortização. Os juros remuneram o saldo devedor; a amortização reduz a dívida. No SAC, a amortização é constante e, com taxa fixa e sem outros ajustes, os juros diminuem com o saldo, produzindo prestações decrescentes. Na tabela Price, as prestações são constantes nessas condições, enquanto a amortização aumenta ao longo do tempo.','O custo efetivo total incorpora os encargos da operação, além dos juros. Uma prestação menor pode resultar apenas de prazo mais longo. Para comparar financiamentos, coloque valor liberado, datas, parcelas, tarifas e demais custos na mesma análise. Taxa real também exige base comum: (1 + taxa nominal) ÷ (1 + inflação) − 1.']},
 ],example:{title:'SAC em três períodos',scenario:'Uma dívida hipotética de R$ 3.000 será amortizada em três parcelas, com juros de 2% por período e sem outros custos.',steps:['Amortização: R$ 3.000 ÷ 3 = R$ 1.000 por período.','Juros sobre os saldos iniciais: R$ 60, R$ 40 e R$ 20.','Prestações: R$ 1.060, R$ 1.040 e R$ 1.020; saldo final zero.'],conclusion:'A prestação diminui porque a base dos juros cai, não porque a taxa muda.'},
 comparison:{headers:['Medida','Como pensar','Cuidado'],rows:[['Valor presente','Quanto vale hoje um fluxo futuro?','Usar taxa e tempo compatíveis'],['VPL','Valor criado acima da taxa exigida','Incluir investimento inicial'],['Amortização','Parte que reduz a dívida','Não confundir com prestação']]},
 traps:['Nos compostos, taxa anual equivalente não é a taxa mensal vezes 12.','Prazo menor não garante menor prestação.','VPL e TIR respondem perguntas diferentes.'],recall:[{question:'Quanto valem R$ 1.210 em dois períodos a 10%?',answer:'R$ 1.000: 1.210 ÷ 1,10².'},{question:'O que fica constante no SAC?',answer:'A amortização; a prestação pode variar.'}],sources:['ANBIMA_PD','BCB_SCR']
},
'infraestrutura': {
 objectives:['Distinguir negociação, compensação, liquidação e custódia.','Entender como controles e transparência reduzem riscos.'],
 sections:[
  {id:'caminho',title:'Da ordem à entrega',paragraphs:['Quando o cliente confirma uma compra, a operação ainda percorre etapas. Negociação define condições; compensação apura obrigações; liquidação realiza entrega de ativos e pagamento. Custódia mantém registros e guarda conforme a estrutura aplicável. Uma falha em qualquer etapa pode gerar perda ou impedir a conclusão da operação.','Pense em comprar um imóvel: assinar um acordo e registrar a transferência não são a mesma coisa. No mercado financeiro, sistemas especializados e regras de liquidação organizam essas responsabilidades. O SPB reúne infraestruturas e procedimentos de pagamentos; o sistema Selic está associado ao registro, à custódia e à liquidação de títulos públicos federais.']},
  {id:'risco',title:'Por que há garantias e capital?',paragraphs:['Risco de contraparte é o risco de a outra parte não cumprir o combinado. Em operações com contraparte central, ela se interpõe entre participantes e utiliza mecanismos como margens e garantias. Isso reduz certas exposições, mas não elimina todos os riscos. Garantia exigida pela câmara não é a mesma proteção do FGC.','Exigências prudenciais de capital buscam aumentar a capacidade das instituições de absorver perdas. Liquidez é capacidade de cumprir pagamentos quando vencem; solvência envolve a condição patrimonial de sustentar obrigações. Uma instituição pode ter ativos valiosos e, ainda assim, enfrentar falta imediata de caixa. Compulsórios e instrumentos de liquidez têm funções próprias nesse sistema.']},
  {id:'distribuicao',title:'A regra também chega ao atendimento',paragraphs:['A distribuição deve permitir que o cliente compreenda o produto. Publicidade, documentos e comunicação precisam ser coerentes: riscos, custos, prazos e condições não podem desaparecer porque a peça destaca um retorno atraente. Conhecer a infraestrutura ajuda a explicar por que uma venda não implica recebimento instantâneo do dinheiro.','A autorregulação estabelece padrões para participantes que aderem a seus códigos, em complemento às regras estatais. No caso prático, identifique qual responsabilidade está em discussão: decidir a carteira, distribuir o produto, custodiar o ativo ou liquidar a operação. Trocar esses papéis costuma produzir uma resposta plausível, porém incorreta.']},
 ],example:{title:'Compra confirmada, dinheiro ainda não entregue',scenario:'Uma cliente vende um ativo e deseja usar imediatamente o valor para pagar uma conta.',steps:['Verificar o prazo e o calendário de liquidação daquele mercado.','Separar saldo exibido após a negociação de recursos efetivamente disponíveis.','Explicar o procedimento sem prometer antecipação que não foi contratada.'],conclusion:'Preço negociado e disponibilidade financeira são informações distintas.'},
 comparison:{headers:['Etapa','Função','Pergunta prática'],rows:[['Negociação','Acordar a operação','O que foi comprado e por quanto?'],['Liquidação','Entregar ativo e dinheiro','Quando a obrigação é cumprida?'],['Custódia','Manter a posição registrada','Onde a titularidade é controlada?']]},
 traps:['Liquidez e solvência não são sinônimos.','Contraparte central não transforma qualquer ativo em investimento sem risco.','Sistema Selic e meta da taxa Selic são conceitos relacionados, mas diferentes.'],recall:[{question:'O que a margem procura proteger?',answer:'O cumprimento de obrigações da operação, conforme as regras da infraestrutura.'},{question:'Quem define os investimentos de um fundo?',answer:'O gestor, dentro da política da classe; não a câmara de liquidação.'}],sources:['BCB_SPB','BCB_BASILEIA','BCB_ESTABILIDADE','B3','ANBIMA_DISTRIBUICAO']
},
'renda-fixa': {
 objectives:['Identificar emissor, remuneração, prazo e liquidez.','Comparar risco de crédito, oscilação de preço e retorno líquido.'],
 sections:[
  {id:'contrato',title:'Renda fixa é uma regra, não um preço imóvel',paragraphs:['Um título de renda fixa estabelece condições de remuneração. O prefixado define uma taxa; o pós-fixado acompanha um indexador; o híbrido combina índice e parcela prefixada. Saber a regra não basta para conhecer o retorno de uma venda antecipada: o preço de mercado pode mudar.','Nos títulos públicos, o devedor é o Tesouro Nacional. CDBs representam captação bancária; debêntures, dívida de empresas. CRI e CRA ligam investidores a operações de recebíveis imobiliários e do agronegócio. Para cada produto, analise a estrutura de crédito e suas garantias, sem inferir proteção apenas pelo nome ou pela instituição distribuidora.']},
  {id:'preco',title:'O efeito dos juros no preço',paragraphs:['Se um título promete pagar um fluxo fixo, seu preço hoje é o valor presente desse pagamento. Quando o mercado passa a exigir uma taxa maior, é necessário pagar menos hoje para obter esse retorno. O inverso ocorre quando a taxa exigida cai. Prazos mais longos e a distribuição dos fluxos influenciam a sensibilidade do preço.','Tesouro Selic, Prefixado e IPCA+ atendem a estruturas de remuneração distintas. O IPCA+ combina inflação e taxa real contratada, mas pode oscilar antes do vencimento. Tesouro Renda+ e Educa+ possuem fluxos desenhados para recebimentos futuros. Não troque a análise de prazo e necessidade de caixa pela frase “é título público”.']},
  {id:'liquido',title:'Do anúncio ao que fica no bolso',paragraphs:['Compare valores líquidos no mesmo prazo. Na regra geral de renda fixa tributável, a tabela de IR sobre rendimentos varia de 22,5% até 180 dias a 15% acima de 720 dias, com faixas intermediárias de 20% e 17,5%. Há exceções por produto e titular, e o IOF pode afetar resgates muito curtos nas aplicações sujeitas a ele. Isenção não elimina risco nem torna qualquer taxa atraente.','A data de vencimento não é necessariamente a primeira data em que se pode resgatar. Carência, liquidez diária e mercado secundário são condições distintas. Na poupança, a data de aniversário importa para o crédito da remuneração. Rating expressa uma avaliação de risco de crédito e pode mudar; não é promessa de pagamento.']},
 ],example:{title:'Uma venda antecipada',scenario:'Um título hipotético pagará R$ 1.100 em um ano. Ignore impostos e custos.',steps:['Com taxa exigida de 10%, o preço é R$ 1.100 ÷ 1,10 = R$ 1.000.','Se a taxa exigida passa a 12%, o preço é R$ 1.100 ÷ 1,12 ≈ R$ 982,14.','O fluxo prometido não mudou; mudou o preço necessário para oferecer a nova taxa.'],conclusion:'Renda fixa pode ter perda em uma venda antes do vencimento.'},
 comparison:{headers:['Remuneração','Regra','Principal pergunta'],rows:[['Prefixada','Taxa estabelecida na compra','Posso manter até o vencimento?'],['Pós-fixada','Varia com um indexador','Qual índice e qual percentual?'],['Híbrida','Índice mais taxa','Como o preço reage antes do vencimento?']]},
 traps:['Não aplicar a tabela de renda fixa a todo investimento indistintamente.','Rentabilidade maior pode remunerar maior risco ou menor liquidez.','FGC, quando aplicável, tem condições e limites.'],recall:[{question:'Se a taxa exigida sobe, o que ocorre com o preço de um fluxo fixo?',answer:'Cai, mantidas as demais condições.'},{question:'Uma LCI e um fundo de renda fixa têm a mesma garantia?',answer:'Não. A cobertura depende do instrumento; cotas de fundos não têm FGC.'}],sources:['TESOURO_DIRETO','RECEITA_2026','FGC','ANBIMA_PD']
},
'renda-variavel': {
 objectives:['Separar participação societária, dívida e exposição derivativa.','Ler cenários de retorno e perda sem depender de rentabilidade passada.'],
 sections:[
  {id:'acoes',title:'Comprar uma ação é participar de um negócio',paragraphs:['Ao comprar ações, o investidor participa do capital de uma companhia. Seu resultado pode combinar variação do preço e proventos, mas não há uma taxa de retorno previamente assegurada. A cotação depende de expectativas sobre lucros, riscos e taxa de desconto, além de oferta e demanda. Uma empresa lucrativa pode ter ações em queda se o preço já pressupunha resultados ainda melhores.','No mercado primário, recursos de uma emissão vão para a companhia emissora; no secundário, compradores e vendedores negociam ativos existentes. IPO é a oferta pública inicial, e não qualquer venda de ações. Ações ordinárias e preferenciais têm direitos próprios; units reúnem valores mobiliários e BDRs representam certificados vinculados a ativos no exterior. Leia a estrutura antes de generalizar os direitos.']},
  {id:'derivativos',title:'Proteção e alavancagem',paragraphs:['Derivativos têm valor relacionado a outro ativo ou variável. Um contrato futuro pode reduzir a incerteza de preço de uma operação real, mas também pode ser usado para assumir exposição. Hedge é a finalidade de proteção; não é um tipo de contrato e não garante lucro. A proteção pode ser imperfeita se volume, prazo ou referência forem diferentes.','Em uma opção, o comprador paga um prêmio para adquirir um direito; o lançador assume a obrigação correspondente se houver exercício. O risco depende da posição, e não apenas do nome “opção”. Em posições alavancadas, pequenas variações do ativo podem gerar grandes efeitos sobre o capital, inclusive necessidades adicionais de recursos.']},
  {id:'coe',title:'Leia a estrutura e a tributação',paragraphs:['O COE combina exposições em uma estrutura com cenários definidos. Na modalidade de valor nominal protegido, a proteção segue as condições e o vencimento pactuados e continua sujeita ao risco do emissor. Ela não significa retorno mínimo real, liquidez antecipada assegurada ou cobertura do FGC. Na modalidade de valor nominal em risco, pode haver perda do capital investido.','Antes de comparar, identifique ativo de referência, prazo, participação na alta, limites de ganho, barreiras e custos de oportunidade. Em renda variável, imposto sobre ganho, retenção na fonte e eventuais isenções são assuntos diferentes. A regra aplicável muda conforme instrumento e operação; uma regra de ações não deve ser transferida automaticamente para ETF, FII, derivativo ou COE.']},
 ],example:{title:'Um teto de ganho muda a comparação',scenario:'Um COE hipotético paga a alta de um índice até um teto de 12%, com proteção nominal no vencimento, sujeita ao emissor.',steps:['Se o índice sobe 8%, o cenário previsto entrega 8%, antes de custos e tributos.','Se sobe 25%, o teto limita o ganho a 12%.','Se cai, a proteção pactuada não remunera automaticamente inflação nem custo de oportunidade.'],conclusion:'É preciso comparar cenários completos, não apenas o melhor cenário do anúncio.'},
 comparison:{headers:['Instrumento','Natureza','Ponto de atenção'],rows:[['Ação','Participação no capital','Resultado do negócio e preço'],['Derivativo','Exposição a uma referência','Posição, garantias e alavancagem'],['COE','Estrutura emitida por instituição','Cenários, prazo e risco do emissor']]},
 traps:['Provento não é retorno total: observe também o preço.','Hedge reduz uma exposição específica; não elimina todos os riscos.','Proteção nominal não é proteção do poder de compra.'],recall:[{question:'Quem recebe recursos numa emissão primária?',answer:'A companhia emissora.'},{question:'Um COE protegido pode oscilar antes do vencimento?',answer:'Sim. A proteção contratual não assegura o preço de saída antecipada.'}],sources:['B3','CVM_COE','BCB_COE','RECEITA_2026']
},
'fundos': {
 objectives:['Entender o que uma cota representa e quem decide a carteira.','Separar estrutura, liquidez, taxas e tratamento tributário.'],
 sections:[
  {id:'estrutura',title:'A carteira é coletiva; a decisão exige leitura',paragraphs:['Um fundo reúne recursos para investimento segundo regras definidas. O investidor adquire cotas e participa economicamente da carteira correspondente. O valor da cota reflete o patrimônio líquido dividido pela quantidade de cotas, conforme os critérios de avaliação. Se os ativos perdem valor, a cota pode cair, mesmo quando a carteira é de renda fixa.','Na estrutura da Resolução CVM 175, um fundo pode ter classes com patrimônio segregado. Subclasses podem diferenciar condições dentro da mesma classe, como taxas ou público, sem criar carteiras segregadas entre si. A responsabilidade do cotista pode ser limitada conforme o regulamento. Não presuma essa condição sem consultar os documentos.']},
  {id:'prestadores',title:'Quem faz o quê e quando o dinheiro volta',paragraphs:['O gestor toma decisões de investimento dentro da política da classe. O administrador assume atribuições de funcionamento e organização; outros prestadores cuidam de distribuição, custódia, auditoria e serviços contratados. A existência de fiscalização não equivale a garantia de rentabilidade, e cotas não têm cobertura do FGC.','Classes abertas admitem resgate conforme suas regras; nas fechadas, a saída costuma depender de venda da cota ou de eventos previstos. Na aberta, diferencie pedido de resgate, cotização e pagamento. “D+30 para cotizar, mais dois dias úteis para pagar” não significa dinheiro disponível no mesmo dia do pedido.']},
  {id:'custos',title:'Política, taxas e imposto',paragraphs:['Renda fixa, ações, cambial e multimercado descrevem estratégias e exposições, não níveis universais de segurança. Examine concentração, crédito privado, derivativos, alavancagem e ativos no exterior. Um nome conhecido ou um bom mês não substitui a leitura da política. Compare desempenho com um referencial coerente e com risco semelhante.','Taxa de administração remunera serviços previstos; taxa de performance depende das condições estipuladas. O come-cotas, quando aplicável, antecipa imposto por redução de cotas: não é uma tarifa do gestor. A tributação varia entre categorias e regimes, inclusive com exceções à tributação periódica. A classificação tributária de curto ou longo prazo não é simplesmente o tempo que o cliente pretende ficar.']},
 ],example:{title:'Valor da cota e imposto são contas diferentes',scenario:'Uma classe hipotética tem patrimônio líquido de R$ 1 milhão e 100 mil cotas. Ignore aportes, resgates e impostos nesta primeira conta.',steps:['Cota inicial: R$ 10.','Se o patrimônio sobe para R$ 1,05 milhão, a cota passa a R$ 10,50.','Uma antecipação de IR por come-cotas, quando devida, reduz a quantidade de cotas do investidor segundo a regra aplicável.'],conclusion:'Rentabilidade da carteira, quantidade de cotas e saldo líquido precisam ser distinguidos.'},
 comparison:{headers:['Termo','O que significa','Não confundir'],rows:[['Classe','Patrimônio segregado','Subclasse com carteira própria'],['Cotização','Data do valor da cota no resgate','Data do pagamento'],['Come-cotas','Antecipação de IR quando aplicável','Taxa de administração']]},
 traps:['Fundo vendido pelo banco não herda a garantia do banco.','Liquidez da carteira e prazo de resgate do cotista não são necessariamente iguais.','Taxa de performance não é promessa de superar o índice.'],recall:[{question:'Quem escolhe os ativos?',answer:'O gestor, respeitando a política e os limites.'},{question:'Por que ler o prazo de cotização?',answer:'Ele define quando se apura o valor usado no resgate; o pagamento pode ocorrer depois.'}],sources:['CVM_175','RECEITA_2026','ANBIMA_PD']
},
'fundos-imobiliarios': {
 objectives:['Distinguir exposição a imóveis e a recebíveis.','Avaliar renda distribuída, preço da cota e liquidez.'],
 sections:[
  {id:'origem',title:'De onde vem o resultado?',paragraphs:['Um FII é um veículo de investimento ligado ao mercado imobiliário. Pode ter imóveis, direitos e ativos relacionados, de acordo com sua política. Os chamados fundos de tijolo se associam à exploração de imóveis; os de papel, a títulos e recebíveis. Esses apelidos são úteis para começar, mas não substituem a leitura da carteira e do regulamento.','Em imóveis físicos, aluguel, vacância, inadimplência, despesas, localização e renegociação afetam o fluxo. Em recebíveis, avalie devedores, garantias, indexadores, prazos e estrutura. Um lastro imobiliário não impede inadimplência e não faz do papel um imóvel diretamente disponível para o cotista.']},
  {id:'retorno',title:'Rendimento distribuído não é retorno total',paragraphs:['A renda distribuída é apenas uma parte do resultado do investidor. A cota também oscila. Um rendimento aparentemente elevado pode acompanhar uma queda expressiva de preço, ou incluir efeito não recorrente. Compare distribuição, capacidade recorrente de geração de caixa e valorização ou desvalorização da posição.','Juros de mercado influenciam o custo de oportunidade e podem afetar o preço das cotas. O valor patrimonial por cota é uma referência contábil; não é compromisso de recompra nesse preço. Negociar abaixo do valor patrimonial pode refletir oportunidade, mas também problemas esperados nos ativos.']},
  {id:'saida',title:'A saída depende das regras do veículo',paragraphs:['FIIs são estruturados como fundos fechados. Em vez de resgatar cotas a qualquer momento junto ao fundo, o investidor normalmente precisa encontrar comprador no mercado secundário, quando houver negociação. Volume diário e diferença entre ofertas de compra e venda afetam a facilidade de saída.','O tratamento tributário dos rendimentos distribuídos não deve ser confundido com o do ganho na venda das cotas. Benefícios fiscais, quando presentes, dependem de requisitos legais. Antes de responder um caso, identifique o evento: distribuição, alienação, amortização ou liquidação. Não memorize uma frase genérica como “FII não paga imposto”.']},
 ],example:{title:'Receber renda e perder no total',scenario:'Uma cota foi comprada por R$ 100, distribuiu R$ 8 no período e passou a valer R$ 90. Desconsidere impostos e custos.',steps:['Resultado da renda: +R$ 8.','Variação do preço: −R$ 10.','Retorno total: (90 + 8 − 100) ÷ 100 = −2%.'],conclusion:'O yield isolado não mede a experiência completa do investidor.'},
 comparison:{headers:['Exposição','Fonte de resultado','Risco relevante'],rows:[['Imóveis','Aluguéis e valorização','Vacância e renegociação'],['Recebíveis','Juros e pagamentos de crédito','Inadimplência e indexadores'],['Cota negociada','Preço de mercado','Liquidez e oscilação']]},
 traps:['Distribuição mensal não é renda contratualmente garantida.','Desconto patrimonial não comprova que um fundo está barato.','FGC não protege cotas de FII.'],recall:[{question:'Como costuma ocorrer a saída de um FII listado?',answer:'Pela venda a outro investidor no mercado secundário.'},{question:'Qual risco aparece quando imóveis ficam vazios?',answer:'Vacância, que pode reduzir a receita e aumentar o peso das despesas.'}],sources:['CVM_175','B3','RECEITA_2026']
},
'previdencia': {
 objectives:['Comparar PGBL e VGBL pela base de tributação.','Analisar horizonte, taxas, resgate e portabilidade.'],
 sections:[
  {id:'fases',title:'Acumular hoje para financiar o futuro',paragraphs:['Previdência complementar organiza recursos para objetivos de longo prazo. Na acumulação, contribuições e rendimentos formam uma reserva; no usufruto, ela pode financiar resgates ou renda conforme o plano. Não basta escolher um produto com “aposentadoria” no nome: a estratégia da carteira, os custos e as condições da renda influenciam o resultado.','Planos abertos se relacionam com o segmento supervisionado pela Susep. Entidades fechadas atendem públicos vinculados a patrocinadores ou instituidores e são supervisionadas pela Previc. A escolha entre renda vitalícia, prazo certo e outras modalidades depende de condições contratuais, expectativa de uso dos recursos e proteção desejada aos beneficiários.']},
  {id:'bases',title:'PGBL e VGBL: entenda a base do imposto',paragraphs:['O PGBL pode permitir dedução das contribuições até 12% dos rendimentos tributáveis, observados requisitos legais, como o modelo de declaração e as condições de contribuição previdenciária. Isso adia tributação; não torna o investimento isento. No recebimento de recursos do PGBL, a base de imposto inclui o valor total sujeito à tributação.','No VGBL, não há essa dedução das contribuições, e a tributação incide sobre os rendimentos. Ele é um seguro de pessoas com cobertura por sobrevivência. O perfil tributário, a renda e o uso do benefício de dedução importam mais do que escolher um produto por costume. Regimes progressivo e regressivo são uma dimensão adicional à escolha entre PGBL e VGBL.']},
  {id:'escolha',title:'Prazo, custos e transferência',paragraphs:['No regime regressivo, o prazo de acumulação dos recursos é relevante para a alíquota; no progressivo, aplica-se a lógica da tabela progressiva e do ajuste conforme as regras. Não trate o tempo desde a abertura do plano como se todos os aportes tivessem a mesma idade. Verifique também o momento e as condições permitidas para a opção tributária.','Taxas de administração, carregamento quando existente, carências e política de investimento devem ser comparados. Portabilidade transfere recursos entre planos compatíveis sem ser um saque para a conta do participante. Não é permitida a conversão de PGBL em VGBL por portabilidade. Sacar para reaplicar pode ter efeitos tributários e de prazo diferentes.']},
 ],example:{title:'Dedução não é devolução integral',scenario:'Uma pessoa com R$ 100 mil de rendimentos tributáveis cumpre os requisitos de dedução e contribui R$ 12 mil para PGBL.',steps:['O limite de 12% corresponde a R$ 12 mil de contribuição dedutível.','Esse valor reduz a base tributável, não o imposto diretamente em R$ 12 mil.','O efeito efetivo depende da apuração do IR; no futuro, a tributação do PGBL alcança a base total aplicável.'],conclusion:'Benefício na entrada deve ser avaliado junto da tributação e dos custos na saída.'},
 comparison:{headers:['Produto','Dedução das contribuições','Base no recebimento'],rows:[['PGBL','Possível, dentro dos requisitos e limite','Valor total tributável'],['VGBL','Não usa a dedução do PGBL','Rendimentos'],['Portabilidade','Transferência entre planos compatíveis','Não equivale a saque']]},
 traps:['12% é limite de dedução da base, não rentabilidade nem desconto direto no imposto.','Previdência não é automaticamente um investimento conservador.','Não se porta PGBL para VGBL.'],recall:[{question:'VGBL permite a dedução de 12%?',answer:'Não. Essa possibilidade está associada ao PGBL, com requisitos.'},{question:'Por que conhecer a idade dos aportes?',answer:'Ela é relevante para a aplicação do regime regressivo.'}],sources:['SUSEP_PREVIDENCIA','PREVIC','RECEITA_2026']
},
'credito': {
 objectives:['Comparar propostas pelo fluxo completo e pelo CET.','Reconhecer limites de garantias e da análise cadastral.'],
 sections:[
  {id:'necessidade',title:'O crédito começa com uma finalidade',paragraphs:['Crédito antecipa recursos que serão pagos com renda futura. A análise começa por necessidade, valor, prazo e capacidade de pagamento. Empréstimo pessoal costuma ter uso livre; financiamento se vincula a uma finalidade ou bem. Produtos diferentes podem apresentar garantias e condições muito distintas.','Uma parcela que cabe no mês não prova sustentabilidade. Avalie despesas essenciais, dívidas já existentes, variação da renda e possibilidade de imprevistos. Alongar o prazo reduz a prestação em muitos casos, mas pode elevar o custo total. Compare cenários completos e preserve clareza sobre as consequências do inadimplemento.']},
  {id:'cet',title:'Por que a taxa anunciada não basta?',paragraphs:['O CET expressa o custo da operação considerando os encargos e despesas que integram seu cálculo. Juros, tributos, tarifas e seguros incidentes podem fazer duas propostas com a mesma taxa nominal terem custos diferentes. Para comparar, mantenha montante efetivamente liberado, prazo e datas tão próximos quanto possível.','No consignado, o desconto em folha reduz uma fonte de risco de recebimento, mas não elimina risco nem garante adequação ao orçamento. No crédito com garantia, a possibilidade de execução afeta a relação econômica. Taxa menor pode vir acompanhada de comprometimento de um bem importante. O custo financeiro não é a única dimensão da escolha.']},
  {id:'informacoes',title:'Cadastro, SCR e responsabilidade',paragraphs:['O Sistema de Informações de Créditos do Banco Central reúne informações para supervisão e análise de risco de crédito, dentro das regras de acesso e autorização. Não é simplesmente uma lista de inadimplentes: operações adimplentes também podem constar. Dados cadastrais, renda e histórico devem ser analisados em conjunto.','Garantias reais, aval e fiança têm estruturas jurídicas próprias. Antes de orientar um cliente, confirme o que está sendo dado em garantia e quais obrigações cada pessoa assume. A renegociação de uma dívida deve comparar saldo, encargos, prazo e capacidade de pagamento; trocar uma dívida por outra sem essa análise pode apenas adiar o problema.']},
 ],example:{title:'Menor parcela, maior desembolso',scenario:'Para o mesmo valor liberado, duas propostas hipotéticas oferecem 12 parcelas de R$ 950 ou 24 parcelas de R$ 550, sem outros pagamentos.',steps:['Total nominal da primeira: R$ 11.400.','Total nominal da segunda: R$ 13.200.','A segunda alivia o caixa mensal, mas exige mais pagamentos e maior total nominal; compare também o CET e o valor do dinheiro no tempo.'],conclusion:'A decisão exige equilibrar custo e capacidade de pagamento, não apenas minimizar a prestação.'},
 comparison:{headers:['Informação','Ajuda a entender','Limitação'],rows:[['Taxa de juros','Remuneração do capital','Não reúne todos os encargos'],['CET','Custo financeiro abrangente','Comparar fluxos equivalentes'],['Garantia','Proteção do credor','Não elimina a obrigação do devedor']]},
 traps:['SCR não é sinônimo de cadastro negativo.','Garantia não significa ausência de risco para quem toma crédito.','Somar parcelas ajuda, mas não substitui o cálculo financeiro.'],recall:[{question:'Por que comparar CET?',answer:'Porque a taxa de juros isolada não captura todos os custos da operação.'},{question:'Crédito consignado dispensa análise do orçamento?',answer:'Não. O desconto em folha não resolve excesso de endividamento.'}],sources:['BCB_SCR','BCB_SFN','ANBIMA_PD']
},
'servicos-bancarios': {
 objectives:['Distinguir conta, meio de pagamento e crédito.','Orientar uso seguro e escolha de serviços.'],
 sections:[
  {id:'contas',title:'Uma conta organiza serviços diferentes',paragraphs:['Conta de depósito, conta de pagamento e conta-salário não são nomes intercambiáveis. Elas têm finalidades, regras de movimentação e estruturas próprias. Entender o tipo de conta é o primeiro passo para avaliar saques, transferências, tarifas e eventual proteção dos recursos. Uma conta digital descreve um canal de atendimento, não toda sua natureza jurídica.','Serviços essenciais possuem regras de gratuidade e limites para as situações previstas. Um pacote pago reúne serviços, mas precisa ser avaliado frente ao uso real. A melhor orientação começa por perguntar quais transações o cliente faz, com que frequência e por quais canais, em vez de presumir que o pacote mais amplo é necessário.']},
  {id:'pagamentos',title:'Pagamento não é financiamento',paragraphs:['Pix é um arranjo de pagamentos instantâneos. A chave facilita identificar a conta, mas não é o dinheiro em si. Antes de confirmar, confira nome, instituição e valor apresentados pelo aplicativo. Transferência, boleto, débito automático e cartão resolvem situações distintas; prazos, possibilidade de agendamento e regras de contestação precisam ser conhecidos.','No cartão de crédito, comprar e pagar a fatura são etapas diferentes. Pagar apenas parte da fatura pode resultar em financiamento, sujeito às condições e às regras vigentes. Cartão de débito utiliza os recursos disponíveis; o cartão de crédito usa um limite. Um limite elevado não é acréscimo de renda nem patrimônio.']},
  {id:'seguranca',title:'Atendimento seguro e custo transparente',paragraphs:['Golpes exploram urgência e aparente autoridade. Um suposto atendente pode pedir transferência para uma “conta segura” ou instalação de acesso remoto. A reação adequada é interromper a ação e validar pelos canais oficiais, sem usar o telefone ou o link fornecido pelo contato suspeito. Senhas e códigos de autenticação não devem ser entregues ao interlocutor.','Em uma reclamação, registre o ocorrido, preserve comprovantes e explique os canais disponíveis. Não prometa devolução automática em qualquer fraude: procedimentos de análise têm requisitos e limites. Consórcio também merece distinção: é autofinanciamento em grupo, com taxas e regras de contemplação, não investimento com retorno garantido.']},
 ],example:{title:'Pacote que não acompanha o uso',scenario:'Uma pessoa paga por um pacote amplo, mas faz quase todas as operações pelo aplicativo e raramente usa atendimento presencial.',steps:['Levantar os serviços efetivamente utilizados.','Comparar limites e valores das modalidades disponíveis, inclusive serviços essenciais quando aplicáveis.','Explicar eventuais cobranças excedentes e formalizar a opção do cliente.'],conclusion:'O serviço deve ser escolhido pelo uso e pelas regras da conta, não pela quantidade de itens anunciados.'},
 comparison:{headers:['Item','Função','Não confundir com'],rows:[['Pix','Transferir ou pagar','Linha de crédito automática'],['Cartão de crédito','Pagamento com limite e fatura','Renda adicional'],['Consórcio','Autofinanciamento coletivo','Entrega imediata assegurada']]},
 traps:['A chave Pix não dispensa a conferência do destinatário.','Pagar o mínimo da fatura não significa quitar a dívida.','Conta digital não identifica, sozinha, o regime jurídico da conta.'],recall:[{question:'Como agir diante de pedido urgente para transferir a uma conta segura?',answer:'Interromper, não transferir e verificar o contato por canal oficial independente.'},{question:'Como comparar pacotes?',answer:'Pelo uso real, limites, custos e serviços gratuitos aplicáveis.'}],sources:['BCB_PIX','BCB_SFN','ANBIMA_PD']
},
'seguros': {
 objectives:['Distinguir prêmio, indenização, franquia e cobertura.','Relacionar proteção contratada a uma necessidade concreta.'],
 sections:[
  {id:'risco',title:'Seguro transfere consequências financeiras',paragraphs:['O seguro organiza a proteção contra riscos definidos em contrato. O segurado paga o prêmio, e a seguradora assume obrigações de cobertura. O prêmio é o preço do seguro; não é o valor que a pessoa recebe quando ocorre um evento. A indenização depende da cobertura, dos limites e das condições pactuadas.','A apólice e as condições contratuais mostram eventos cobertos, exclusões, vigência e deveres das partes. Um produto pode ter nome abrangente e, mesmo assim, excluir situações específicas. Por isso, o atendimento começa pela necessidade: proteger dependentes, uma dívida, um bem ou a continuidade de renda são objetivos diferentes.']},
  {id:'condicoes',title:'O que pode mudar o pagamento?',paragraphs:['Franquia é a parcela do prejuízo que fica a cargo do segurado conforme o contrato. Carência é um período em que certas coberturas ainda não produzem efeitos. Limite máximo de indenização delimita o compromisso contratual. Esses mecanismos não são equivalentes e podem existir juntos.','Informações fornecidas na contratação influenciam a aceitação e as condições. O profissional deve incentivar respostas verdadeiras, explicar dúvidas e evitar omissões para baratear o preço. Em caso de sinistro, o cliente deve seguir os procedimentos e apresentar documentos exigidos; a análise da seguradora não pode ser substituída por uma promessa informal do vendedor.']},
  {id:'produtos',title:'Proteção, acumulação e sorteio',paragraphs:['Seguro de vida se relaciona às coberturas contratadas sobre riscos pessoais. Seguro prestamista procura cumprir obrigações de uma dívida nas hipóteses previstas; não deve ser apresentado como cobertura irrestrita para qualquer perda de renda. O beneficiário e o capital segurado precisam ser compreendidos.','Título de capitalização combina componentes como formação de valor de resgate e sorteios, segundo sua modalidade e condições. Não é sinônimo de poupança nem de fundo de investimento. Compare prazo de resgate, parcela efetivamente capitalizada e regras de sorteio. Para cada produto, explique a finalidade antes de destacar um benefício comercial.']},
 ],example:{title:'Franquia em uma cobertura hipotética',scenario:'Um contrato prevê franquia dedutível de R$ 2.000 para um dano coberto de R$ 7.000, dentro do limite da apólice.',steps:['Verificar se o evento está coberto e se a franquia se aplica.','Subtrair a franquia: R$ 7.000 − R$ 2.000 = R$ 5.000.','Nesse cenário simplificado, R$ 2.000 ficam com o segurado e R$ 5.000 com a seguradora.'],conclusion:'O cálculo depende das condições específicas; não se transfere essa franquia a qualquer tipo de sinistro.'},
 comparison:{headers:['Termo','Significado','Momento'],rows:[['Prêmio','Preço da proteção','Contratação/pagamento'],['Franquia','Participação do segurado no prejuízo','Sinistro, quando aplicável'],['Indenização','Pagamento devido segundo a cobertura','Após análise do evento']]},
 traps:['Prêmio não é indenização.','Seguro prestamista não cobre toda hipótese de inadimplência.','Capitalização não deve ser comparada à poupança apenas pelo nome “reserva”.'],recall:[{question:'Por que ler exclusões?',answer:'Porque eventos parecidos podem ter tratamentos contratuais diferentes.'},{question:'Qual a diferença entre carência e franquia?',answer:'Carência é temporal; franquia é participação no prejuízo conforme as condições.'}],sources:['SUSEP','ANBIMA_PD']
},
'planejamento': {
 objectives:['Separar fluxo de caixa, patrimônio e objetivos.','Planejar reserva e aportes com hipóteses explícitas.'],
 sections:[
  {id:'diagnostico',title:'Primeiro, uma fotografia e um filme',paragraphs:['O balanço pessoal é a fotografia: ativos menos passivos mostram o patrimônio líquido em uma data. O orçamento é o filme: entradas e saídas ao longo do mês mostram se há sobra ou déficit. Uma pessoa pode ter patrimônio alto e pouco caixa disponível; outra pode ter renda alta e patrimônio líquido negativo.','Registre despesas fixas, variáveis e periódicas. Seguro anual, matrícula e manutenção não deixam de existir por não vencerem todo mês. Transformar esses gastos em provisões mensais ajuda a evitar surpresas. Diferencie renda recorrente de entradas ocasionais e evite comprometer despesas permanentes com receitas incertas.']},
  {id:'prioridades',title:'Reserva antes de otimizar cada centavo',paragraphs:['Uma reserva de emergência serve a necessidades imprevisíveis. Sua função exige disponibilidade e risco compatível com o uso urgente, não maximização de retorno. O tamanho depende de despesas essenciais, estabilidade de renda, dependentes e outras proteções. Uma regra de meses pode orientar uma conversa, mas não substitui o diagnóstico.','Dívidas também devem ser organizadas por custo e risco. Comparar amortização de uma dívida com investimento exige retorno líquido, incerteza, liquidez e condições contratuais. Não faz sentido prometer que um investimento arriscado “vai pagar” uma dívida de custo certo. Ao mesmo tempo, quitar tudo e ficar sem caixa pode criar nova necessidade de crédito.']},
  {id:'metas',title:'Transforme intenção em plano',paragraphs:['Um objetivo útil descreve valor, data e finalidade. “Quero guardar mais” não define um compromisso operacional; “quero formar R$ 12 mil em 12 meses” permite calcular aportes. Separe metas de curto, médio e longo prazo e considere inflação quando o valor é definido em poder de compra atual.','O plano deve ser revisado após mudanças de renda, família, trabalho ou preço do objetivo. A fase de acumulação tende a enfatizar aportes e formação patrimonial; a de usufruto exige atenção à retirada e à longevidade. O ciclo de vida ajuda a formular perguntas, sem justificar um portfólio automático só pela idade.']},
 ],example:{title:'Uma meta que cabe no orçamento',scenario:'Uma pessoa deseja juntar R$ 12.000 em 12 meses. Para simplificar, desconsidere rendimentos e inflação.',steps:['Aporte necessário: R$ 12.000 ÷ 12 = R$ 1.000 por mês.','Se a sobra atual é R$ 700, existe uma diferença de R$ 300.','Ajustar despesas, renda, prazo ou valor da meta; não preencher a diferença com retorno prometido.'],conclusion:'O plano precisa fechar com premissas que o cliente consegue executar.'},
 comparison:{headers:['Ferramenta','Pergunta','Exemplo'],rows:[['Orçamento','Quanto entra e sai?','Renda mensal e despesas'],['Balanço','Quanto possuo líquido?','Ativos menos dívidas'],['Meta','Quanto preciso e quando?','Reserva em 12 meses']]},
 traps:['Limite de crédito não é ativo pessoal disponível sem obrigação.','Patrimônio ilíquido não substitui automaticamente reserva.','Uma regra de idade não determina sozinha o perfil.'],recall:[{question:'Ativos de R$ 200 mil e dívidas de R$ 80 mil geram qual patrimônio líquido?',answer:'R$ 120 mil.'},{question:'Por que provisionar despesas anuais?',answer:'Para reconhecer o gasto no planejamento mensal e reduzir surpresas no vencimento.'}],sources:['ANBIMA_PD','BCB_SFN']
},
'carteiras': {
 objectives:['Relacionar ativos a objetivos e restrições.','Entender diversificação e rebalanceamento.'],
 sections:[
  {id:'alocacao',title:'A carteira começa pelo uso do dinheiro',paragraphs:['Alocação é a distribuição dos recursos entre exposições. Antes de escolher produtos, identifique objetivo, horizonte, necessidade de liquidez e capacidade de suportar perdas. Uma reserva para uma despesa próxima não deve receber a mesma lógica de uma meta para décadas, mesmo quando ambas pertencem à mesma pessoa.','Diferencie classe de ativo, produto e instituição. Ter vários produtos de um mesmo emissor ou com carteiras muito semelhantes pode manter a concentração. Da mesma forma, comprar por corretoras diferentes não altera automaticamente o risco de crédito do título: o emissor continua sendo relevante.']},
  {id:'diversificacao',title:'Diversificar é combinar riscos',paragraphs:['A diversificação funciona porque os ativos não respondem todos da mesma forma e intensidade aos mesmos eventos. O benefício depende da relação entre seus retornos e exposições, não apenas da contagem de posições. Concentração em setor, país, indexador ou prazo pode existir mesmo em uma lista longa de investimentos.','Ela reduz riscos específicos, mas não elimina choques gerais de mercado. Em crises, relações históricas podem mudar. A análise deve considerar risco de crédito, mercado e liquidez, além de custos, impostos e possibilidade real de manter a estratégia. Retorno passado, sozinho, não mede adequação.']},
  {id:'acompanhamento',title:'Rebalancear com um motivo',paragraphs:['Com o tempo, oscilações e aportes alteram os pesos da carteira. Rebalanceamento busca reaproximar a alocação de uma estratégia definida, respeitando mudanças no objetivo e no perfil. Ele pode ser realizado por novas contribuições, resgates ou trocas, sem exigir negociação constante.','Uma revisão responsável explica a razão da mudança e avalia tributos, custos, prazos e liquidez. Trocar produtos repetidamente apenas para gerar receita ao intermediário é um problema de conduta. Se as premissas do cliente mudaram, o alvo também pode mudar: rebalancear não é obedecer cegamente a um percentual antigo.']},
 ],example:{title:'O peso mudou sem novas compras',scenario:'Uma carteira começa com R$ 6.000 em renda fixa e R$ 4.000 em ações. Depois, as ações passam a R$ 6.000 e a renda fixa continua em R$ 6.000.',steps:['Valor total atual: R$ 12.000.','Pesos atuais: 50% em cada parcela.','Para voltar a 60%/40%, seriam R$ 7.200 e R$ 4.800, antes de custos e tributos; aportes podem ser outra forma de ajuste.'],conclusion:'O alvo depende da estratégia e da situação atual do cliente, não do ativo que mais subiu.'},
 comparison:{headers:['Ação','Objetivo','Cuidado'],rows:[['Alocar','Definir exposições','Partir do objetivo'],['Diversificar','Reduzir concentração','Olhar os riscos em comum'],['Rebalancear','Revisar pesos','Considerar custos e mudança de perfil']]},
 traps:['Dez produtos não garantem dez riscos independentes.','O ativo que mais rendeu não é automaticamente o melhor próximo investimento.','Rebalanceamento não é giro sem justificativa.'],recall:[{question:'A diversificação elimina o risco sistêmico?',answer:'Não. Ela pode reduzir concentração e risco específico, mas choques amplos continuam relevantes.'},{question:'Aportes podem rebalancear?',answer:'Sim, direcionando recursos às parcelas abaixo do peso desejado.'}],sources:['ANBIMA_PD','CVM_RES30','CVM']
},
'perfil': {
 objectives:['Diferenciar disposição e capacidade de assumir riscos.','Explicar risco de crédito, mercado e liquidez em casos concretos.'],
 sections:[
  {id:'riscos',title:'Nomeie o risco antes de julgar o produto',paragraphs:['Risco de crédito envolve o não cumprimento de obrigações pelo devedor. Risco de mercado envolve variação de preços e taxas. Risco de liquidez envolve dificuldade de converter a posição em recursos no prazo e nas condições desejados. Um investimento pode apresentar os três simultaneamente.','Uma debênture de uma empresa sólida ainda pode oscilar com os juros e ter poucos compradores. Um título com liquidez diária pode ter risco de crédito. A análise deve perguntar “qual perda pode ocorrer, por qual motivo e quando o cliente precisará sair?”, em vez de classificar tudo apenas como seguro ou arriscado.']},
  {id:'pessoa',title:'Querer risco não é conseguir suportá-lo',paragraphs:['Disposição é a tolerância subjetiva a perdas e oscilações. Capacidade é a condição financeira de absorvê-las sem comprometer obrigações e objetivos. Uma pessoa pode declarar entusiasmo por risco, mas depender do dinheiro para uma despesa essencial próxima. Nesse caso, a vontade não elimina a restrição financeira.','Conhecimento e experiência também importam. Entender um produto complexo exige reconhecer cenários de perda, custos e prazos. Ser jovem, ter renda elevada ou já possuir ações não comprova, isoladamente, que a pessoa compreende qualquer instrumento. O perfil deve ser analisado com informações consistentes e atuais.']},
  {id:'adequacao',title:'A recomendação precisa caber no objetivo',paragraphs:['Suitability é o processo de verificar a adequação dos produtos, serviços e operações ao cliente. Ele relaciona características do investimento às informações sobre objetivos, situação financeira e conhecimento. Um formulário ajuda, mas não substitui a responsabilidade de avaliar a situação relatada no atendimento.','Uma mudança de emprego, perda de renda ou aproximação da data da meta pode exigir revisão. Não se deve orientar o cliente a responder de determinada forma apenas para liberar um produto. Diante de incompatibilidade, ausência de informações ou cadastro desatualizado, aplique os procedimentos e restrições da regulamentação e da instituição.']},
 ],example:{title:'Arrojado para qual dinheiro?',scenario:'Um cliente aceita oscilações e acompanha o mercado, mas precisa usar R$ 30 mil para uma obrigação certa daqui a dois meses.',steps:['Identificar prazo e caráter essencial dessa parcela.','Separar tolerância geral a risco da capacidade de perda para a obrigação.','Analisar alternativas com liquidez e risco compatíveis para essa finalidade.'],conclusion:'Um perfil geral não autoriza colocar todos os objetivos na mesma exposição.'},
 comparison:{headers:['Dimensão','Pergunta','Exemplo'],rows:[['Disposição','Aceita oscilar?','Reação emocional à perda'],['Capacidade','Pode absorver a perda?','Renda, patrimônio e obrigações'],['Conhecimento','Entende o mecanismo?','Experiência e compreensão do produto']]},
 traps:['Idade não substitui análise de perfil.','Liquidez diária não significa preço estável.','Assinatura não apaga incompatibilidades nem dispensa procedimentos.'],recall:[{question:'Qual risco aparece ao precisar vender sem encontrar comprador?',answer:'Risco de liquidez.'},{question:'O que diferencia capacidade e disposição?',answer:'Capacidade é condição financeira; disposição é tolerância subjetiva.'}],sources:['CVM_RES30','CVM','ANBIMA_DISTRIBUICAO']
},
'atendimento-etica': {
 objectives:['Conduzir uma conversa clara e registrar necessidades.','Reconhecer conflitos, indícios de lavagem, uso indevido de dados e práticas ilícitas.'],
 sections:[
  {id:'escuta',title:'A boa venda começa pela escuta',paragraphs:['No atendimento, comece com perguntas abertas e depois confirme os pontos objetivos: finalidade, prazo, liquidez e experiência. Escuta ativa envolve demonstrar compreensão e verificar se a interpretação está correta. Repetir o que o cliente disse com suas próprias palavras ajuda a revelar mal-entendidos antes de apresentar um produto.','Empatia não é concordar com qualquer expectativa. Se alguém deseja retorno elevado sem risco e com saída imediata, explique os conflitos entre essas exigências. Use cenários, valores e exemplos acessíveis; peça que a pessoa explique o funcionamento de volta. Termos técnicos sem compreensão não tornam a comunicação transparente.']},
  {id:'conflitos',title:'Adequação e interesse do cliente',paragraphs:['O processo de suitability deve considerar informação atual e coerente. Alterações na vida do cliente exigem reavaliação quando relevantes. A remuneração da distribuição pode criar conflitos, que precisam ser tratados conforme regras de transparência e controles. O produto que mais remunera o vendedor não se torna adequado por esse motivo.','Giro excessivo sem interesse econômico do cliente pode caracterizar churning. Front running envolve antecipar operações próprias usando conhecimento de ordens de clientes. Uso indevido de informação relevante ainda não pública e manipulação do mercado são outras condutas a reconhecer. Não confunda especulação legítima, com informação pública e regras observadas, com práticas ilícitas.']},
  {id:'pld',title:'Conhecer o cliente e identificar operações atípicas',paragraphs:['A prevenção à lavagem de dinheiro e ao financiamento do terrorismo usa identificação, atualização cadastral, conhecimento do cliente, beneficiário final e monitoramento. A análise baseada em risco considera perfil, origem dos recursos e coerência das operações. Um valor elevado pode ser compatível com determinada atividade; valores menores e fracionados podem merecer atenção no contexto.','Atipicidade é um sinal para analisar, não prova automática de crime. O profissional deve seguir o fluxo interno e as obrigações aplicáveis, sem investigar por conta própria nem alertar o cliente sobre eventual comunicação sigilosa. Pessoa exposta politicamente não é sinônimo de criminosa; requer os procedimentos específicos previstos.']},
  {id:'dados',title:'Dados pessoais têm finalidade',paragraphs:['A LGPD estabelece princípios como finalidade, adequação e necessidade. Coletar o máximo de dados “para usar depois” pode contrariar esses princípios. O tratamento precisa de base legal apropriada; consentimento é uma das bases possíveis, não a única. Mesmo quando existe base legal, controles de segurança e minimização continuam relevantes.','Compartilhar informações financeiras por canais pessoais ou inserir dados identificáveis em ferramenta não autorizada pode expor o cliente. Em um incidente, preserve evidências e acione os responsáveis internos; não prometa apagar rastros nem ocultar o problema. Sigilo, segurança da informação e qualidade do registro protegem tanto o cliente quanto a instituição.']},
 ],example:{title:'Um pedido fora do padrão',scenario:'Uma cliente solicita várias transferências fracionadas incompatíveis com o histórico e insiste para que não sejam registradas.',steps:['Não dispensar os registros exigidos.','Reunir as informações pertinentes dentro das atribuições e encaminhar ao processo interno de análise.','Preservar a confidencialidade dos procedimentos e evitar afirmar que já há prova de crime.'],conclusion:'A postura correta combina registro, análise e sigilo; não improvisação nem acusação.'},
 comparison:{headers:['Situação','Risco ou conceito','Resposta adequada'],rows:[['Comissão orienta a venda','Conflito de interesses','Avaliar adequação e transparência'],['Operação fora do perfil','Atipicidade','Analisar pelo fluxo interno'],['Dados sem necessidade','Excesso de tratamento','Limitar à finalidade e base legal']]},
 traps:['Atípico não significa comprovadamente ilícito.','Consentimento não autoriza uso ilimitado de dados.','Uma promessa verbal pode contrariar o documento formal do produto.'],recall:[{question:'O que fazer se o cliente não compreendeu o risco?',answer:'Explicar de forma acessível, verificar compreensão e seguir os procedimentos de adequação.'},{question:'Por que não avisar sobre uma comunicação sigilosa?',answer:'Porque sua confidencialidade integra as obrigações do processo de prevenção.'}],sources:['CVM_RES30','CVM_62','ANBIMA_DISTRIBUICAO','PLANALTO_AML','PLANALTO_LGPD','PLANALTO_SIGILO']
},
'sustentabilidade': {
 objectives:['Aplicar as dimensões ambiental, social e de governança.','Distinguir integração ESG, objetivo sustentável e discurso publicitário.'],
 sections:[
  {id:'dimensoes',title:'ESG entra na análise de riscos e oportunidades',paragraphs:['A dimensão ambiental envolve temas como emissões, uso de recursos e exposição a eventos climáticos. A social trata de relações com trabalhadores, consumidores e comunidades. Governança aborda direção, controles, incentivos e prestação de contas. As dimensões se conectam: uma falha de governança pode permitir danos ambientais e sociais.','Esses fatores podem afetar receitas, custos, acesso a capital e continuidade de atividades. Uma fábrica sujeita a enchentes enfrenta risco físico; uma operação intensiva em carbono pode ser afetada por mudança tecnológica ou regulatória, caracterizando risco de transição. ESG não é apenas reputação nem uma promessa automática de retorno superior.']},
  {id:'estrategias',title:'Estratégias diferentes não devem receber o mesmo rótulo',paragraphs:['Integração ESG incorpora fatores relevantes à análise e decisão. Exclusão retira setores ou práticas segundo critérios. Seleção positiva privilegia determinadas características. Investimento temático se concentra em temas; investimento de impacto busca resultados socioambientais intencionais e mensuráveis, ao lado da lógica financeira aplicável. Engajamento procura influenciar práticas das investidas.','Essas abordagens podem coexistir. A pergunta importante é como cada uma modifica a carteira e como seus resultados são acompanhados. Um fundo pode considerar risco ambiental sem ter objetivo principal de promover sustentabilidade. Um nome verde não esclarece sozinho a estratégia utilizada.']},
  {id:'evidencias',title:'Como ler um fundo apresentado como sustentável',paragraphs:['Na identificação da ANBIMA, fundos de investimento sustentável e fundos que integram questões ESG têm requisitos e sinalizações diferentes. O sufixo IS está ligado ao objetivo sustentável, e não deve ser atribuído indistintamente a qualquer integração ESG. Confira o cadastro, o regulamento, a metodologia e os indicadores divulgados.','Greenwashing é a apresentação enganosa ou sem sustentação de atributos ambientais. Para avaliar uma alegação, procure objetivo, critério de seleção, evidência e acompanhamento. Evite concluir que uma certificação ou classificação elimina riscos de mercado, crédito e liquidez. Sustentabilidade e adequação ao cliente são análises complementares.']},
 ],example:{title:'Dois fundos com mensagens parecidas',scenario:'Um fundo usa riscos climáticos na avaliação de crédito; outro declara objetivo sustentável e acompanha indicadores relacionados à sua estratégia.',steps:['No primeiro, há integração de informação ESG à decisão.','No segundo, investigar o objetivo, a metodologia e o cumprimento dos requisitos de identificação.','Comparar documentos e evidências antes de usar o mesmo rótulo para ambos.'],conclusion:'Incorporar um fator ESG não comprova, por si só, um objetivo sustentável.'},
 comparison:{headers:['Abordagem','Pergunta central','Evidência esperada'],rows:[['Integração','Como ESG afeta a decisão?','Metodologia de análise'],['Exclusão','O que não entra na carteira?','Critérios definidos'],['Impacto','Qual mudança se pretende gerar?','Intenção e mensuração']]},
 traps:['ESG não elimina risco financeiro.','Nome do fundo não substitui documentos.','Risco físico e risco de transição não são a mesma coisa.'],recall:[{question:'Uma enchente afetando uma fábrica é qual risco climático?',answer:'Um exemplo de risco físico.'},{question:'Por que verificar indicadores?',answer:'Para avaliar se as alegações têm método e acompanhamento, e não apenas publicidade.'}],sources:['CVM_ESG','ANBIMA_PD']
},
'ativos-digitais': {
 objectives:['Separar tecnologia, representação de direitos e investimento.','Reconhecer riscos de contrato, custódia, mercado e liquidez.'],
 sections:[
  {id:'registro',title:'Blockchain é uma forma de organizar registros',paragraphs:['Uma blockchain encadeia registros e utiliza mecanismos de validação para manter uma visão compartilhada entre participantes. Redes podem diferir em acesso, governança, validação e desempenho. Distribuição de registros não significa que qualquer dado inserido seja verdadeiro: o sistema precisa de processos para lidar com informações originadas fora da rede.','Um token pode representar diferentes direitos ou utilidades. Tokenização é a representação digital dentro de determinada estrutura, não uma certificação de qualidade econômica. Antes de investir, identifique o direito, o emissor ou responsável, a possibilidade de exigir cumprimento e as condições jurídicas. A tecnologia não substitui a análise do ativo.']},
  {id:'automacao',title:'Contratos inteligentes e finanças descentralizadas',paragraphs:['Smart contracts executam instruções programadas quando condições são atendidas. Eles podem automatizar liquidação, garantias ou regras de transferência. Contudo, erros de código, permissões administrativas, dependência de dados externos e falhas na integração podem afetar o resultado. Um programa automático não se torna seguro apenas porque dispensa uma etapa manual.','DeFi usa estruturas de software e redes para oferecer funções financeiras. A redução de intermediários tradicionais pode vir acompanhada de novas dependências, como protocolos, oráculos e governança. É necessário entender como garantias são avaliadas e liquidadas, quem pode alterar regras e quais eventos podem impedir saques.']},
  {id:'custodia',title:'O risco também está no acesso',paragraphs:['A custódia pode ser realizada por um prestador ou pelo próprio usuário. Na autocustódia, o controle das chaves exige procedimentos de segurança e recuperação; perder acesso pode inviabilizar o uso dos ativos. Em custódia terceirizada, é preciso avaliar riscos e condições do prestador. Senha de um aplicativo e chave privada não são conceitos equivalentes.','Stablecoins buscam manter uma referência de valor por mecanismos que variam. Reservas, capacidade de resgate, governança e funcionamento do mecanismo importam; “stable” não garante estabilidade em qualquer cenário. Drex, criptoativos privados e Pix também não são sinônimos: têm finalidades e estruturas distintas.']},
 ],example:{title:'Um imóvel tokenizado continua exigindo análise',scenario:'Uma oferta afirma que o investimento é seguro porque representa um imóvel por tokens.',steps:['Identificar exatamente qual direito o token oferece.','Verificar o responsável, documentos, renda esperada, custos e possibilidade de saída.','Avaliar riscos do imóvel e também da plataforma, da custódia e da estrutura jurídica.'],conclusion:'A representação digital adiciona uma camada tecnológica; não apaga os riscos econômicos.'},
 comparison:{headers:['Conceito','O que descreve','Limite'],rows:[['Blockchain','Estrutura de registros','Não garante veracidade da entrada'],['Smart contract','Execução de instruções','Pode conter falhas'],['Tokenização','Representação de direitos','Não assegura liquidez ou solvência']]},
 traps:['Stablecoin não equivale automaticamente a depósito garantido.','Automação não elimina risco operacional.','Descentralização deve ser analisada na prática, inclusive governança e controle.'],recall:[{question:'O que é um oráculo nesse contexto?',answer:'Um mecanismo que fornece dados externos usados pelo contrato ou protocolo.'},{question:'Qual análise permanece após tokenizar um ativo?',answer:'Direitos, fluxo econômico, risco de crédito, mercado, liquidez e estrutura jurídica.'}],sources:['BCB_DREX','CVM','ANBIMA_PD']
},
'open-finance': {
 objectives:['Entender consentimento e compartilhamento entre instituições.','Separar circulação de dados de transferência de produtos e dinheiro.'],
 sections:[
  {id:'dados',title:'O cliente pode levar seu histórico para outra conversa',paragraphs:['Open Finance permite compartilhar informações financeiras entre participantes, com autorização do cliente e padrões definidos. A proposta é tornar o histórico mais útil para comparar serviços e desenvolver ofertas, em vez de mantê-lo isolado em uma única instituição. Isso não equivale a tornar os dados públicos.','O consentimento deve ser compreendido: quais dados, para qual finalidade e com quem serão compartilhados? Autenticação e confirmação fazem parte do processo. O cliente pode controlar e revogar autorizações conforme os procedimentos. Não é adequado pedir que forneça sua senha ao atendente da instituição que deseja receber os dados.']},
  {id:'utilidade',title:'Possibilidade não é promessa de benefício',paragraphs:['Informações adicionais podem ajudar uma instituição a entender renda, movimentação e relacionamento do cliente. Isso pode favorecer comparação e avaliação de crédito, mas não obriga aprovação nem garante taxa menor. A decisão continua sujeita a critérios, condições de mercado e análise da proposta.','O compartilhamento deve ser proporcional à finalidade. A pessoa pode ter interesse em comparar crédito sem desejar um uso amplo e indefinido de todas as informações. A conversa deve apresentar escolhas de forma clara e permitir decisão consciente, sem tratar autorização como mera formalidade.']},
  {id:'portabilidade',title:'Dados e produtos seguem caminhos diferentes',paragraphs:['Compartilhar dados não transfere automaticamente salário, dívida, investimentos ou previdência. Portabilidade é um processo próprio para movimentar relações ou posições conforme regras específicas. Cada produto possui requisitos, prazos e consequências; é necessário identificar o que efetivamente será transferido.','Open Insurance se relaciona ao compartilhamento no mercado de seguros, sob sua governança e regulamentação. Open Investment se conecta a informações de investimentos no ecossistema. Em qualquer caso, a experiência digital precisa preservar consentimento, segurança, rastreabilidade e clareza sobre quem responde pelo serviço.']},
 ],example:{title:'Compartilhar para comparar crédito',scenario:'Uma cliente autoriza outra instituição a acessar informações de sua movimentação para avaliar uma proposta.',steps:['Confirmar instituição, dados e finalidade no fluxo oficial.','Comparar CET, prazo, garantias e condições da proposta recebida.','Se quiser transferir a operação, seguir o processo próprio de portabilidade; a autorização de dados não faz isso sozinha.'],conclusion:'Dados melhores podem apoiar comparação, mas o benefício depende das condições oferecidas.'},
 comparison:{headers:['Ação','O que muda','O que não ocorre automaticamente'],rows:[['Compartilhar dados','Acesso autorizado à informação','Transferência de saldo'],['Portar crédito','Estrutura da dívida entre instituições','Aprovação sem análise'],['Revogar autorização','Compartilhamento autorizado','Apagamento de todo registro legalmente necessário']]},
 traps:['Open Finance não é compartilhamento público.','Consentimento não exige revelar senha a terceiros.','Autorizar acesso não garante crédito mais barato.'],recall:[{question:'Os dados são públicos?',answer:'Não. O compartilhamento ocorre entre participantes segundo autorização e regras.'},{question:'Compartilhamento transfere investimentos?',answer:'Não automaticamente; eventual transferência segue procedimento próprio.'}],sources:['BCB_OPEN_FINANCE','ANPD_LGPD','ANBIMA_PD']
},
 'tecnologia': {
 objectives:['Reconhecer usos e limitações de IA no atendimento.','Diferenciar inovação tecnológica de autorização regulatória.'],
 sections:[
  {id:'ia',title:'A ferramenta ajuda; a responsabilidade permanece',paragraphs:['Inteligência artificial reúne técnicas para realizar tarefas como classificação, previsão e geração de conteúdo. Machine learning aprende padrões a partir de dados. Um modelo usado para estimar inadimplência e um assistente que redige respostas podem empregar técnicas e controles diferentes. A palavra IA não revela sozinha a qualidade do resultado.','Modelos generativos podem produzir afirmações convincentes e incorretas. Antes de usar uma resposta em atendimento, verifique fonte, data, cálculo e coerência com as regras. Não atribua à ferramenta uma decisão que exige supervisão ou responsabilidade profissional. Uma resposta bem escrita ainda pode conter uma taxa antiga ou uma regra de outro produto.']},
  {id:'governanca',title:'Dados, vieses e validação',paragraphs:['A qualidade dos dados influencia o modelo. Bases incompletas ou enviesadas podem reproduzir desigualdades e gerar decisões inadequadas. Separar dados de treinamento e teste ajuda a avaliar generalização; bom desempenho histórico não garante estabilidade diante de mudanças no comportamento dos clientes ou no mercado.','Use apenas ambientes autorizados para dados de clientes, com minimização, controle de acesso e finalidade definida. A validação deve acompanhar erros, mudanças de desempenho e necessidade de revisão humana. Eficiência operacional não justifica ignorar privacidade ou deixar decisões relevantes sem possibilidade de explicação e contestação.']},
  {id:'fintechs',title:'Novos serviços, regras continuam',paragraphs:['Fintech descreve uma atuação baseada em tecnologia no setor financeiro; não é uma licença única. Uma empresa pode atuar em pagamentos, crédito, investimento ou infraestrutura, e a atividade efetivamente realizada determina as exigências aplicáveis. Instituição de pagamento e banco possuem diferenças que precisam ser compreendidas.','Sandbox regulatório permite testar inovações em condições, limites e supervisão definidos. Não é uma dispensa irrestrita de regras nem um selo de investimento seguro. Em novos meios de pagamento, analise autenticação, prevenção a fraude, continuidade do serviço e proteção de dados. Um processo rápido deve continuar compreensível para o cliente.']},
 ],example:{title:'Uma resposta bonita com uma regra errada',scenario:'Um assistente de IA redige orientação sobre resgate e inclui uma alíquota que não corresponde ao produto.',steps:['Conferir a regra na fonte oficial e identificar o erro.','Corrigir a orientação antes de apresentá-la ao cliente.','Registrar o problema no processo de qualidade e revisar os controles de uso da ferramenta.'],conclusion:'A tecnologia pode acelerar a redação, mas não substitui validação de conteúdo.'},
 comparison:{headers:['Conceito','Uso possível','Controle necessário'],rows:[['Modelo preditivo','Estimar risco ou comportamento','Qualidade de dados e validação'],['IA generativa','Apoiar texto e síntese','Conferência de fatos e privacidade'],['Sandbox','Testar inovação sob condições','Limites e supervisão']]},
 traps:['Fintech não é sinônimo de banco.','Resultado histórico elevado não prova ausência de viés.','Sandbox não elimina autorização nem supervisão aplicáveis.'],recall:[{question:'Pode inserir dados de clientes em qualquer IA gratuita?',answer:'Não. É necessário respeitar finalidade, base legal, segurança e políticas de ambientes autorizados.'},{question:'Por que revisar uma resposta fluente?',answer:'Porque fluência não comprova exatidão, atualidade ou adequação.'}],sources:['ANPD_LGPD','BCB_PIX','CVM','ANBIMA_PD']
},
}
export function readingMinutes(reading: ModuleReading) {
  const text = JSON.stringify(reading)
  return Math.max(4, Math.ceil(text.split(/\s+/).length / 150))
}


for (const [moduleId, sections] of Object.entries(deepReadingSections)) {
  const reading = moduleReadings[moduleId]
  if (reading) reading.sections.push(...sections)
}

for (const [moduleId, sections] of Object.entries(masteryReadingSections)) {
  const reading = moduleReadings[moduleId]
  if (reading) reading.sections.push(...sections)
}
